#include "ThreeDmMerge.h"
#include "ThreeDmNativeReferences.h"
#include <QDir>
#include <QFile>
#include <QCryptographicHash>
#include <QJsonDocument>
#include <QTemporaryDir>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static int checks=0;
static void require(bool v,const char* message){++checks;if(!v)throw ExchangeError(message);}
static QByteArray bytes(QString path){QFile f(path);require(f.open(QIODevice::ReadOnly),"Read frozen UV target evidence");return f.readAll();}
static QString sha(QString path){return QString::fromLatin1(QCryptographicHash::hash(bytes(path),QCryptographicHash::Sha256).toHex());}
int main(){try{ON::Begin();QDir f(QStringLiteral(OM9_UV_RHINO_DIR));QTemporaryDir tmp;require(tmp.isValid(),"Owned atomic refusal staging");auto oracle=QJsonDocument::fromJson(bytes(f.filePath("oracle.json"))).object(),actual=QJsonDocument::fromJson(bytes(f.filePath("rhino5-gui-profile-results.json"))).object(),binding=QJsonDocument::fromJson(bytes(f.filePath("actual-attempt-binding.json"))).object();
    require(actual["oracle_sha256"]==sha(f.filePath("oracle.json"))&&actual["probe_sha256"]==sha(f.filePath("rhino5-uv-reference-probe.py"))&&binding["rhino_report_sha256"]==sha(f.filePath("rhino5-gui-profile-results.json")),"Bind actual Rhino report to exact independent fixture/probe/oracle");
    auto cases=oracle["cases"].toArray(),observed=actual["cases"].toArray();require(cases.size()==8&&observed.size()==8&&!actual["ok"].toBool()&&binding["saved_files_created"].toInt()==0,"Eight observed target failures, no roundtrip or saved-output claim");QJsonArray results;
    for(int i=0;i<cases.size();++i){auto wanted=cases[i].toObject(),rhino=observed[i].toObject();auto path=f.filePath(wanted["fixture"].toString());auto original=bytes(path);require(rhino["fixture"]==wanted["fixture"]&&rhino["source_sha256"]==wanted["source_sha256"]&&sha(path)==wanted["source_sha256"],"Actual input/fixture identity binding");
        auto objects=wanted["objects"].toArray();auto owner=objects[0].toObject()["uuid"].toString(),root=objects[1].toObject()["uuid"].toString();QJsonObject ownerRow,rootRow;for(auto v:rhino["first_read"].toObject()["objects"].toArray()){auto row=v.toObject();if(row["uuid"]==owner)ownerRow=row;if(row["uuid"]==root)rootRow=row;}
        require(ownerRow["valid"].toBool()&&!rootRow["valid"].toBool()&&ownerRow["domain"].toArray()==QJsonArray{11,23}&&rootRow["domain"].toArray()==QJsonArray{31,47},"Actual Rhino keeps valid owner but cannot bind/evaluate surface-curve UV");
        auto valid=ownerRow["sample_validity"].toArray(),invalid=rootRow["sample_validity"].toArray(),points=ownerRow["samples"].toArray(),bad=rootRow["samples"].toArray();require(points.size()==17&&bad.size()==17&&valid.size()==17&&invalid.size()==17,"Complete actual raw point evidence");
        for(int j=0;j<=16;++j){auto p=points[j].toArray(),unset=bad[j].toArray();double u=j/16.;auto expected=ON_3dPoint(2*u,wanted["kind"].toInt()?2*u*(1-u):u,0);require(valid[j].toBool()&&ON_3dPoint(p[0].toDouble(),p[1].toDouble(),p[2].toDouble()).DistanceTo(expected)<=1e-12,"Independent owner line/quadratic actual samples");require(!invalid[j].toBool()&&unset.size()==3&&unset[0].toDouble()==ON_UNSET_VALUE&&unset[1].toDouble()==ON_UNSET_VALUE&&unset[2].toDouble()==ON_UNSET_VALUE,"Actual root returns native UnsetPoint, not overflow masked by probe");}
        require(!rhino["passed"].toBool()&&rhino["bad_objects"].toInt()==1&&rhino["error"].toString().contains("Rhino command failed: _-SaveAs")&&!rhino.contains("reread")&&!rhino.contains("saved_fixture"),"Target bad-object/SaveAs failure is retained separately from successful roundtrip");
        auto inv=inspectArchive(std::filesystem::path(path.toStdWString()));QJsonObject native;for(auto row:inv.document["records"].toArray())if(row.toObject()["source_uuid"]==root)native=row.toObject();require(inv.document["issues"].toArray().isEmpty()&&native["class_name"]=="ON_CurveOnSurface"&&native["curve_on_surface_native"]==wanted["native_fields"]&&native["native_reference_analysis"].toObject()["status"]=="linked","OM9 preserves and resolves exact source graph independently of actual target failure");auto graph=inv.nativeReferences->graphs.at(root);auto curve=ON_Curve::Cast(graph->geometry.at(root).get());auto expected=objects[1].toObject()["samples"].toArray();for(int j=0;j<=16;++j){auto q=expected[j].toArray();require(curve->PointAt(31+j).DistanceTo(ON_3dPoint(q[0].toDouble(),q[1].toDouble(),q[2].toDouble()))<=1e-12,"Native independent surface/UV physical composition remains exact");}
        auto target=tmp.filePath("protected.3dm");{QFile dest(target);require(dest.open(QIODevice::WriteOnly),"Protect original public output");dest.write("keep-target");}QJsonObject source{{"namespace","44556677-4455-6677-8899-445566778899"},{"snapshot",path},{"archive_sha256",wanted["source_sha256"]},{"scale_mm",1}};bool refused=false;try{writePreservedArchive(QJsonObject{{"schema_version",1},{"sources",QJsonArray{source}},{"selected",QJsonArray{QJsonObject{{"namespace",source["namespace"]},{"source_uuid",root},{"host_id","root"},{"action","unchanged"}}}}},std::filesystem::path(target.toStdWString()));}catch(const ExchangeError& e){refused=std::string(e.what()).find("CurveOnSurface")!=std::string::npos;}require(refused&&bytes(target)=="keep-target"&&bytes(path)==original,"Public V5 incompatible UV references refuse atomically without payload flattening or source mutation");results.append(QJsonObject{{"fixture",wanted["fixture"]},{"rhino_passed",false},{"native_preservation_and_refusal_passed",true}});
    }
    auto reportSha=sha(f.filePath("rhino5-gui-profile-results.json"));QFile report(QStringLiteral(OM9_UV_RHINO_RESULTS));require(report.open(QIODevice::WriteOnly),"Write actual UV reference scoped acceptance");report.write(QJsonDocument(QJsonObject{{"ok",true},{"checks",checks},{"cases",results},{"rhino_report_sha256",reportSha},{"scope","Actual invalid roots8,valid owners8,SaveAs failure8,no saved reimport; OM9 exact native retention and atomic V5 refusal verified"}}).toJson());std::cout<<checks<<" UV actual target/refusal checks passed\n";return 0;
}catch(const std::exception& e){std::cerr<<"Check "<<checks<<": "<<e.what()<<"\n";return 1;}}
