#include "ThreeDmPointCloud.h"
#include "ThreeDmArchive.h"
#include "ThreeDmMerge.h"
#include <QFile>
#include <QJsonDocument>
#include <QJsonArray>
#include <QCryptographicHash>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool value,const char* message){if(!value)throw ExchangeError(message);}
static ON_PointCloud source(){ON_PointCloud cloud;cloud.m_P.Append(ON_3dPoint(1.123456789012345,2,3));cloud.m_P.Append(ON_3dPoint(4,5.234567890123456,6));cloud.m_N.Append(ON_3dVector(2,0,0));cloud.m_N.Append(ON_3dVector(0,0,0));ON_Color color(17,31,47);color.SetAlpha(53);cloud.m_C.Append(color);cloud.m_C.Append(ON_Color(101,151,201));cloud.m_V.Append(0.123456789012345);cloud.m_V.Append(-4.234567890123456);cloud.SetOrdered(true);cloud.SetPlane(ON_Plane(ON_3dPoint(10,20,30),ON_3dVector(0,0,1)));cloud.SetUserString(L"Native cloud",L"Keep unrelated native userdata");cloud.GetBoundingBox(cloud.m_bbox,false);return cloud;}
static QString uuid(ON_UUID id){char text[37]{};ON_UuidToString(id,text);return QString::fromLatin1(text);}
static QByteArray bytes(const std::filesystem::path& path){QFile file(QString::fromStdWString(path.wstring()));require(file.open(QIODevice::ReadOnly),"read cloud exchange bytes");return file.readAll();}
static const ON_PointCloud* nativeCloud(const ArchiveInventory& archive,ON_UUID id){auto component=ON_ModelGeometryComponent::Cast(archive.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,id).ModelComponent());return component?ON_PointCloud::Cast(component->Geometry(nullptr)):nullptr;}
static void exchange(ON::LengthUnitSystem units){
    auto cloud=source();cloud.m_V.Empty();cloud.m_flags|=256;ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);ON_Layer layer;layer.SetName(L"PointCloud fields");model.AddModelComponent(layer);ON_3dmObjectAttributes attributes;attributes.m_name=L"PointCloud current fields";attributes.SetUserString(L"Cloud attribute",L"Keep attribute user text");auto root=model.AddModelGeometryComponent(&cloud,&attributes);auto intensity=source();attributes.m_name=L"Native intensity retained";auto intensityRef=model.AddModelGeometryComponent(&intensity,&attributes);attributes.SetMode(ON::idef_object);attributes.m_name=L"PointCloud member";auto member=model.AddModelGeometryComponent(&cloud,&attributes);ON_InstanceDefinition definition;definition.SetName(L"PointCloud definition");definition.AddInstanceGeometryId(member.ModelComponent()->Id());auto target=model.AddModelComponent(definition);ON_InstanceRef instance;instance.m_instance_definition_uuid=target.ModelComponent()->Id();instance.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(100,200,300));attributes.SetMode(ON::normal_object);attributes.m_name=L"Cloud root";auto block=model.AddModelGeometryComponent(&instance,&attributes);
    auto path=std::filesystem::temp_directory_path()/(units==ON::LengthUnitSystem::Millimeters?"om9-native-point-cloud-mm.3dm":"om9-native-point-cloud-cm.3dm");require(model.Write(path.c_str(),5,nullptr),"cloud exchange source write");auto original=bytes(path);auto input=inspectArchive(path);double scale=input.document["scale_mm"].toDouble();QJsonObject archiveSource{{"namespace","12345678-1234-1234-1234-123456789abc"},{"snapshot",QString::fromStdWString(path.wstring())},{"archive_sha256",input.document["archive_sha256"]},{"scale_mm",scale}};
    auto current=cloud;current.m_P[0]=ON_3dPoint(7.123456789012345,8,9);current.m_P[1]=ON_3dPoint(10,11,12);current.m_N[0]=ON_3dVector(0,2,0);current.SetOrdered(false);current.m_bbox.Destroy();auto fields=path.parent_path()/"om9-current-point-cloud.json";auto digest=writePointCloudFields(current,fields);QJsonArray matrix{-2,0,0,10,0,3,0,20,0,0,4,30,0,0,0,1};QJsonObject row{{"namespace",archiveSource["namespace"]},{"source_uuid",uuid(root.ModelComponent()->Id())},{"host_id","current-cloud"},{"action","transform"},{"geometry_matrix",matrix},{"point_cloud_fields",QString::fromStdWString(fields.wstring())},{"point_cloud_sha256",digest}};QJsonObject request{{"schema_version",1},{"sources",QJsonArray{archiveSource}},{"selected",QJsonArray{row}}};auto output=path.parent_path()/"om9-native-point-cloud-output.3dm";writePreservedArchive(request,output);auto result=inspectArchive(output);auto expected=current;ON_Xform transform=ON_Xform::IdentityTransformation;for(int i=0;i<16;++i)transform[i/4][i%4]=matrix[i].toDouble();transformNativeGeometry(expected,transform);auto actual=nativeCloud(result,root.ModelComponent()->Id());require(actual&&pointCloudFields(*actual)==pointCloudFields(expected)&&actual->m_flags==expected.m_flags&&result.document["records"].toArray().size()==1,"current cloud fields mm and native affine map exact optional arrays plane flags and selected closure");ON_wString note;require(actual->GetUserString(L"Native cloud",note)&&note==L"Keep unrelated native userdata","cloud exchange retains native user text");
    auto selected=row;selected["source_uuid"]=uuid(block.ModelComponent()->Id());selected["action"]="unchanged";selected["host_id"]="block";selected.remove("geometry_matrix");selected.remove("point_cloud_fields");selected.remove("point_cloud_sha256");auto dependency=row;dependency["source_uuid"]=uuid(member.ModelComponent()->Id());dependency["host_id"]="member";request["selected"]=QJsonArray{selected};request["dependency_overlays"]=QJsonArray{dependency};writePreservedArchive(request,output);result=inspectArchive(output);actual=nativeCloud(result,member.ModelComponent()->Id());require(actual&&pointCloudFields(*actual)==pointCloudFields(expected)&&result.document["records"].toArray().size()==2,"canonical cloud member native current fields and closure");
    ON_UUID own;ON_CreateUuid(own);QJsonObject copy{{"namespace",archiveSource["namespace"]},{"host_id","own-cloud"},{"source_uuid",uuid(member.ModelComponent()->Id())},{"output_uuid",uuid(own)},{"role","top-level"},{"member_matrix",matrix},{"independent_overlay",QJsonObject{{"action","transform"},{"point_cloud_fields",row["point_cloud_fields"]},{"point_cloud_sha256",digest}}}};selected["source_uuid"]=uuid(own);request.remove("dependency_overlays");request["selected"]=QJsonArray{selected};request["member_copies"]=QJsonArray{copy};writePreservedArchive(request,output);result=inspectArchive(output);actual=nativeCloud(result,own);require(actual&&pointCloudFields(*actual)==pointCloudFields(expected)&&result.document["records"].toArray().size()==1&&result.nativeModel->ActiveComponentCount(ON_ModelComponent::Type::InstanceDefinition)==0,"independent cloud selected copy keeps current arrays and omits ancestors");
    auto reject=[&](QJsonObject invalid){auto before=bytes(output);bool failed=false;try{writePreservedArchive(invalid,output);}catch(const ExchangeError&){failed=true;}require(failed&&before==bytes(output),"cloud invalid field or target gate rejects atomically");};request.remove("member_copies");request["selected"]=QJsonArray{row};for(auto key:{"point_cloud_sha256","point_cloud_fields"}){auto bad=row;bad[key]="invalid";auto invalid=request;invalid["selected"]=QJsonArray{bad};reject(invalid);}auto ambiguous=row;ambiguous["text_dot"]=QJsonObject{};auto invalid=request;invalid["selected"]=QJsonArray{ambiguous};reject(invalid);auto intensitySelection=selected;intensitySelection["source_uuid"]=uuid(intensityRef.ModelComponent()->Id());invalid=request;invalid["selected"]=QJsonArray{intensitySelection};reject(invalid);
    auto cleared=source();cleared.m_V.Empty();digest=writePointCloudFields(cleared,fields);auto clearRow=row;clearRow["source_uuid"]=uuid(intensityRef.ModelComponent()->Id());clearRow["point_cloud_sha256"]=digest;clearRow["geometry_matrix"]=QJsonArray{1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};request["selected"]=QJsonArray{clearRow};writePreservedArchive(request,output);require(nativeCloud(inspectArchive(output),intensityRef.ModelComponent()->Id())->m_V.Count()==0,"explicit current intensity clear permits Rhino5 without dropping source bytes");require(bytes(path)==original,"cloud native source stays immutable");
}
int main(){try{
    ON::Begin();auto cloud=source();auto fields=pointCloudFields(cloud);require(fields["schema_version"]==1&&fields["points"].toArray().size()==2&&fields["normals"].toArray().size()==2&&fields["colors"].toArray().size()==8&&fields["values"].toArray().size()==2,"PointCloud fields include complete per-point optional arrays");
    auto path=std::filesystem::temp_directory_path()/"om9-native-point-cloud-fields.json";auto hash=writePointCloudFields(cloud,path);auto copy=cloud;applyPointCloudFields(copy,path,hash);require(pointCloudFields(copy)==fields&&copy.m_bbox.m_min==cloud.m_bbox.m_min&&copy.m_bbox.m_max==cloud.m_bbox.m_max,"unchanged complete fields retain native cache and exact data");
    auto before=pointCloudFields(copy);transformNativeGeometry(copy,ON_Xform::IdentityTransformation);require(pointCloudFields(copy)==before&&copy.m_bbox.IsValid(),"identity native copy preserves serialized cloud bounding cache");
    ON_Xform matrix=ON_Xform::IdentityTransformation;matrix[0][0]=-2;matrix[1][1]=3;matrix[2][2]=4;matrix[0][3]=10;transformNativeGeometry(copy,matrix);require(copy.m_P[0].DistanceTo(ON_3dPoint(10-2*cloud.m_P[0].x,6,12))<1e-12&&(copy.m_N[0]-ON_3dVector(-2,0,0)).Length()<1e-12&&copy.m_N[1].Length()==0&&copy.m_C[0]==cloud.m_C[0]&&copy.m_V[1]==cloud.m_V[1],"cloud affine maps doubles normals and optional colors/values exactly once");
    auto hiddenPlane=cloud;hiddenPlane.m_flags&=~2U;transformNativeGeometry(hiddenPlane,ON_Xform::DiagonalTransformation(10));require(!hiddenPlane.HasPlane()&&hiddenPlane.m_plane.origin.DistanceTo(ON_3dPoint(100,200,300))<1e-12,"dormant valid plane is normalized without enabling it");
    auto modified=fields;modified["points"]=QJsonArray{QJsonArray{7.123456789012345,8,9},QJsonArray{10,11,12}};modified["normals"]=QJsonArray{QJsonArray{0,2,0},QJsonArray{0,0,0}};modified["values"]=QJsonArray{1.987654321098765,2.345678901234567};modified["ordered"]=false;
    auto write=[&](const QJsonObject& data){auto payload=QJsonDocument(data).toJson(QJsonDocument::Compact);QFile file(QString::fromStdWString(path.wstring()));require(file.open(QIODevice::WriteOnly)&&file.write(payload)==payload.size(),"stage cloud current fields");file.close();return QString::fromLatin1(QCryptographicHash::hash(payload,QCryptographicHash::Sha256).toHex());};hash=write(modified);copy=cloud;applyPointCloudFields(copy,path,hash);require(pointCloudFields(copy)==modified&&!copy.m_bbox.IsValid()&&!copy.IsOrdered(),"edited cloud current arrays replace native fields and invalidate only derived bounds");ON_wString note;require(copy.GetUserString(L"Native cloud",note)&&note==L"Keep unrelated native userdata","native cloud current edits retain unrelated userdata");
    for(auto key:{"points","normals","colors","values","plane","ordered","unknown"}){auto bad=modified;if(QString(key)=="points")bad[key]=QJsonArray{QJsonArray{1,2,"bad"}};else if(QString(key)=="normals"||QString(key)=="values")bad[key]=QJsonArray{1};else if(QString(key)=="colors")bad[key]=QJsonArray{256};else if(QString(key)=="ordered")bad[key]=1;else bad[key]=QJsonObject{};auto digest=write(bad);copy=cloud;bool rejected=false;try{applyPointCloudFields(copy,path,digest);}catch(const ExchangeError&){rejected=true;}require(rejected&&pointCloudFields(copy)==fields,"malformed cloud fields reject before native payload mutation");}
    hash=write(modified);copy=cloud;bool failed=false;try{applyPointCloudFields(copy,path,QString(64,'0'));}catch(const ExchangeError&){failed=true;}require(failed&&pointCloudFields(copy)==fields,"cloud field file hash mismatch preserves source payload");ON_Point wrong(1,2,3);failed=false;try{applyPointCloudFields(wrong,path,hash);}catch(const ExchangeError&){failed=true;}require(failed,"cloud fields refuse wrong native class");
    exchange(ON::LengthUnitSystem::Millimeters);exchange(ON::LengthUnitSystem::Centimeters);std::cout<<"Native PointCloud fields, identity, dormant plane, mm/cm member/copy and atomic gates passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
