#include "ThreeDmArchive.h"
#include "ThreeDmInventory.h"
#include "ThreeDmMerge.h"
#include "ThreeDmHatch.h"
#include <QJsonArray>
#include <QFile>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool ok,const char* message){if(!ok)throw ExchangeError(message);}
static QString id(ON_UUID value){char text[37]{};ON_UuidToString(value,text);return QString::fromLatin1(text);}
static const ON_Hatch* hatch(const ArchiveInventory& a,ON_UUID uuid){auto component=ON_ModelGeometryComponent::Cast(a.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,uuid).ModelComponent());return component?ON_Hatch::Cast(component->Geometry(nullptr)):nullptr;}
static QByteArray bytes(const std::filesystem::path& path){QFile file(QString::fromStdWString(path.wstring()));require(file.open(QIODevice::ReadOnly),"test file read");return file.readAll();}
int main(){try{ON::Begin();for(auto units:{ON::LengthUnitSystem::Millimeters,ON::LengthUnitSystem::Centimeters}){
    ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);ON_Layer layer;layer.SetName(L"Current hatches");model.AddModelComponent(layer);ON_DimStyle style;style.SetName(L"Explicit current style");auto styleRef=model.AddModelComponent(style);model.m_settings.SetCurrentDimensionStyleId(styleRef.ModelComponent()->Id());
    ON_HatchPattern solid;solid.SetName(L"Native solid");auto solidRef=model.AddModelComponent(solid);ON_HatchPattern pattern;pattern.SetName(L"Native lines");pattern.AddHatchLine(ON_HatchLine(0.3));auto patternRef=model.AddModelComponent(pattern);
    ON_NurbsCurve loop;require(ON_Circle(ON_xy_plane,5).GetNurbForm(loop),"rational current loop");loop.ChangeDimension(2);ON_SimpleArray<const ON_Curve*> loops;loops.Append(&loop);ON_Hatch original;require(original.Create(ON_Plane(ON_3dPoint(10,20,30),ON_3dVector(0,0,1)),loops,patternRef.ModelComponent()->Index(),0.345,2.5),"current hatch create");original.SetBasePoint(ON_2dPoint(1,2));original.SetUserString(L"Keep",L"Native current");ON_3dmObjectAttributes attr;attr.m_name=L"Current hatch";auto ref=model.AddModelGeometryComponent(&original,&attr);auto uuid=ref.ModelComponent()->Id();
    auto path=std::filesystem::temp_directory_path()/(units==ON::LengthUnitSystem::Millimeters?"om9-hatch-current-mm.3dm":"om9-hatch-current-cm.3dm");require(model.Write(path.c_str(),5,nullptr),"current source write");auto immutable=bytes(path);auto source=inspectArchive(path);QString ns="00000000-0000-4000-8000-000000000099";
    QJsonObject fields{{"plane",QJsonArray{40,50,60,0,1,0,0,0,1,1,0,0,1,0,0,-40}},{"base_point",QJsonArray{3.125,4.25}},{"rotation",-0.456789123},{"scale",0.0000123456789},{"pattern_uuid",id(solidRef.ModelComponent()->Id())}};
    QJsonObject selected{{"namespace",ns},{"source_uuid",id(uuid)},{"host_id","current-hatch"},{"action","transform"},{"geometry_matrix",QJsonArray{1,0,0,5,0,1,0,6,0,0,1,7,0,0,0,1}},{"hatch_fields",fields}};
    QJsonObject request{{"schema_version",1},{"sources",QJsonArray{QJsonObject{{"namespace",ns},{"snapshot",QString::fromStdWString(path.wstring())},{"archive_sha256",source.document["archive_sha256"]},{"scale_mm",source.document["scale_mm"]}}}},{"selected",QJsonArray{selected}}};auto output=path.parent_path()/"om9-hatch-current-output.3dm";writePreservedArchive(request,output);auto checked=inspectArchive(output);auto after=hatch(checked,uuid);require(after&&after->PatternScale()==fields["scale"].toDouble()&&after->PatternRotation()==fields["rotation"].toDouble()&&after->BasePoint2d()==ON_2dPoint(3.125,4.25),"complete current hatch doubles applied before own transform");require(after->Plane().origin.DistanceTo(ON_3dPoint(45,56,67))<1e-12&&after->LoopCount()==1&&ON_NurbsCurve::Cast(after->Loop(0)->Curve())->IsRational(),"current plane plus own translation retains rational loop");auto chosen=ON_HatchPattern::Cast(checked.nativeModel->ComponentFromIndex(ON_ModelComponent::Type::HatchPattern,after->PatternIndex()).ModelComponent());require(chosen&&chosen->Id()==solidRef.ModelComponent()->Id()&&checked.nativeModel->ActiveComponentCount(ON_ModelComponent::Type::HatchPattern)==1,"current pattern selection closes exact chosen table UUID");
    for(auto invalid:{QJsonObject{},QJsonObject{{"plane",QJsonArray{}},{"base_point",QJsonArray{}},{"rotation",0},{"scale",1},{"pattern_uuid",id(solidRef.ModelComponent()->Id())}}}){auto bad=selected;bad["hatch_fields"]=invalid;auto malformed=request;malformed["selected"]=QJsonArray{bad};auto sentinel=bytes(output);bool rejected=false;try{writePreservedArchive(malformed,output);}catch(const ExchangeError&){rejected=true;}require(rejected&&bytes(output)==sentinel,"malformed current hatch fields reject atomically");}
    fields["pattern_uuid"]=id(ON_HatchPattern::Grid60.Id());selected["hatch_fields"]=fields;request["selected"]=QJsonArray{selected};writePreservedArchive(request,output);auto system=inspectArchive(output);auto systemHatch=hatch(system,uuid);require(systemHatch&&systemHatch->PatternIndex()>=0,"selected system hatch pattern materializes table index");auto systemPattern=ON_HatchPattern::Cast(system.nativeModel->ComponentFromIndex(ON_ModelComponent::Type::HatchPattern,systemHatch->PatternIndex()).ModelComponent());require(systemPattern&&systemPattern->Id()==ON_HatchPattern::Grid60.Id()&&hatchPatternFacts(*systemPattern)==hatchPatternFacts(ON_HatchPattern::Grid60),"materialized system pattern retains exact UUID and line fields");
    auto gradient=original;gradient.SetGradientType(ON_GradientType::Linear);auto gradientBefore=hatchFacts(gradient);bool rejectedGradient=false;try{applyHatchFields(gradient,fields,model);}catch(const ExchangeError&){rejectedGradient=true;}require(rejectedGradient&&hatchFacts(gradient)==gradientBefore,"unverified gradient cannot receive ordinary current fields");rejectedGradient=false;try{hatchCurrentFields(gradient,model);}catch(const ExchangeError&){rejectedGradient=true;}require(rejectedGradient,"gradient cannot advertise ordinary current field schema");
    auto gradientRef=model.AddModelGeometryComponent(&gradient,&attr);require(!gradientRef.IsEmpty(),"gradient fixture add");auto gradientPath=path.parent_path()/(units==ON::LengthUnitSystem::Millimeters?"om9-hatch-current-gradient-mm.3dm":"om9-hatch-current-gradient-cm.3dm");require(model.Write(gradientPath.c_str(),80,nullptr),"gradient fixture write");auto gradientInventory=inspectArchive(gradientPath);bool unavailable=false;for(auto v:gradientInventory.document["records"].toArray()){auto r=v.toObject();if(r["source_uuid"]==id(gradientRef.ModelComponent()->Id()))unavailable=r.contains("hatch_current_unavailable")&&!r.contains("hatch_current");}require(unavailable,"gradient source remains retained without ordinary current fields");
    auto tiny=original;transformNativeGeometry(tiny,ON_Xform::DiagonalTransformation(0.000001));require(tiny.PatternScale()==original.PatternScale()*0.000001,"tiny conformal scale cannot silently retain native setter's previous value");require(bytes(path)==immutable,"current hatch input immutable");std::cout<<"current native hatch fields/plane/pattern/tiny scale mm/cm PASS\n";
}return 0;}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
