#include "ThreeDmArchive.h"
#include "ThreeDmInventory.h"
#include "ThreeDmMerge.h"
#include "ThreeDmHatch.h"
#include <QJsonArray>
#include <QJsonDocument>
#include <QFile>
#include <QProcess>
#include <QTemporaryDir>
#include <QDir>
#include <algorithm>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool ok,const char* text){if(!ok)throw ExchangeError(text);}
static QString id(ON_UUID value){char v[37]{};ON_UuidToString(value,v);return QString::fromLatin1(v);}
static QString text(const ON_wString& value){ON_String utf8(value);return QString::fromUtf8(utf8.Array());}
static QByteArray bytes(const std::filesystem::path& p){QFile f(QString::fromStdWString(p.wstring()));require(f.open(QIODevice::ReadOnly),"legacy Hatch test file read");return f.readAll();}
static QJsonArray strings(const ON_Object& object){QJsonArray result;ON_ClassArray<ON_UserString> values;object.GetUserStrings(values);for(int i=0;i<values.Count();++i)result.append(QJsonObject{{"key",text(values[i].m_key)},{"value",text(values[i].m_string_value)}});return result;}
static QJsonArray sorted(QJsonArray values){std::vector<QJsonObject> objects;for(auto value:values)objects.push_back(value.toObject());std::sort(objects.begin(),objects.end(),[](auto a,auto b){return a["uuid"].toString()<b["uuid"].toString();});QJsonArray result;for(auto object:objects)result.append(object);return result;}
static QJsonObject expected(const ONX_Model& model){
    QJsonArray hatches,patterns,definitions,instances;ONX_ModelComponentIterator table(model,ON_ModelComponent::Type::HatchPattern);
    for(auto c=table.FirstComponent();c;c=table.NextComponent()){auto p=ON_HatchPattern::Cast(c);require(p,"modern native HatchPattern");auto row=hatchPatternFacts(*p);row["uuid"]=id(p->Id());row["name"]=text(p->Name());row["user_strings"]=strings(*p);patterns.append(row);}
    ONX_ModelComponentIterator geometry(model,ON_ModelComponent::Type::ModelGeometry);
    for(auto c=geometry.FirstComponent();c;c=geometry.NextComponent()){auto gc=ON_ModelGeometryComponent::Cast(c);auto g=gc->Geometry(nullptr);auto a=gc->Attributes(nullptr);if(auto instance=ON_InstanceRef::Cast(g)){QJsonArray matrix;for(int i=0;i<16;++i)matrix.append(instance->m_xform[i/4][i%4]);instances.append(QJsonObject{{"uuid",id(c->Id())},{"definition_uuid",id(instance->m_instance_definition_uuid)},{"matrix",matrix}});}
        auto h=ON_Hatch::Cast(g);if(!h)continue;auto current=hatchCurrentFields(*h,model);current["uuid"]=id(c->Id());current["name"]=text(a->m_name);QJsonArray loops;
        for(int i=0;i<h->LoopCount();++i){auto loop=h->Loop(i);auto n=ON_NurbsCurve::Cast(loop->Curve());require(n,"modern exact native NURBS loop");QJsonArray cvs,knots;for(int j=0;j<n->CVCount();++j){QJsonArray cv;for(int k=0;k<n->CVSize();++k)cv.append(n->CV(j)[k]);cvs.append(cv);}for(int j=0;j<n->KnotCount();++j)knots.append(n->Knot(j));loops.append(QJsonObject{{"type",static_cast<int>(loop->Type())},{"class_name",n->ClassId()->ClassName()},{"dimension",n->Dimension()},{"order",n->Order()},{"rational",n->IsRational()},{"cvs",cvs},{"knots",knots},{"user_strings",strings(*n)}});}
        current["native_loops"]=hatchLoopInventory(*h);current["loops"]=loops;current["user_strings"]=strings(*h);current["attribute_user_strings"]=strings(*a);QJsonArray userdata;for(auto d=h->FirstUserData();d;d=d->Next())userdata.append(QJsonObject{{"class_uuid",id(d->ClassId()->Uuid())},{"userdata_uuid",id(d->m_userdata_uuid)}});current["userdata"]=userdata;hatches.append(current);
    }
    ONX_ModelComponentIterator defs(model,ON_ModelComponent::Type::InstanceDefinition);for(auto c=defs.FirstComponent();c;c=defs.NextComponent()){auto def=ON_InstanceDefinition::Cast(c);QJsonArray members;for(int i=0;i<def->InstanceGeometryIdList().Count();++i)members.append(id(def->InstanceGeometryIdList()[i]));definitions.append(QJsonObject{{"uuid",id(c->Id())},{"members",members}});}
    return QJsonObject{{"hatches",sorted(hatches)},{"patterns",sorted(patterns)},{"definitions",sorted(definitions)},{"instances",sorted(instances)}};
}
static void save(const QString& path,const QJsonObject& value){QFile f(path);require(f.open(QIODevice::WriteOnly|QIODevice::Truncate),"legacy evidence write");auto data=QJsonDocument(value).toJson(QJsonDocument::Indented);require(f.write(data)==data.size(),"legacy evidence bytes write");}
static int cases=0;
static void legacy(const std::filesystem::path& source,const std::filesystem::path& dir,const QString& label){
    auto inputBytes=bytes(source);auto before=inspectArchive(source);auto want=expected(*before.nativeModel);auto output=dir/("legacy-"+std::to_string(cases)+".3dm"),report=dir/("legacy-"+std::to_string(cases)+".json");QProcess p;p.start(QString::fromUtf8(OM9_LEGACY_HATCH_READER_EXE),QStringList{QString::fromStdWString(source.wstring()),QString::fromStdWString(output.wstring()),QString::fromStdWString(report.wstring())});require(p.waitForStarted(10000)&&p.waitForFinished(30000)&&p.exitStatus()==QProcess::NormalExit&&p.exitCode()==0,"independent SDK2013 Hatch process must finish successfully");auto proof=QJsonDocument::fromJson(bytes(report)).object();require(proof["sdk_version"]==201307115&&proof["source_version"]==50&&proof["gradient_api_available"]==false,"independent legacy SDK version/API identity");auto fields=proof;for(auto key:{"sdk_version","source_version","gradient_api_available","stale_attribute_owners","attribute_owner_repairs"})fields.remove(key);for(auto key:fields.keys())fields[key]=sorted(fields[key].toArray());
    // SDK2013 stores movable base point in its typed ON_HatchExtra userdata;
    // the modern reader consumes that known legacy representation into the
    // current field. Verify the decoded base above and require exactly one
    // expected extension. Every unrelated userdata identity stays compared.
    QJsonArray normalizedHatches;for(auto value:fields["hatches"].toArray()){auto h=value.toObject();QJsonArray data;int extensions=0;for(auto d:h["userdata"].toArray()){auto item=d.toObject();if(item["class_uuid"]=="3ff7007c-3d04-463f-84e3-132aceb91062"&&item["userdata_uuid"]==item["class_uuid"])++extensions;else data.append(item);}require(extensions==1,"legacy typed movable base-point extension must decode exactly once");h["userdata"]=data;normalizedHatches.append(h);}fields["hatches"]=normalizedHatches;
    if(fields!=want){std::cerr<<"expected "<<QJsonDocument(want).toJson(QJsonDocument::Compact).constData()<<"\nlegacy "<<QJsonDocument(fields).toJson(QJsonDocument::Compact).constData()<<'\n';}require(fields==want,"independent legacy exact Hatch/plane/base/scale/UUID/NURBS/pattern/graph fields");auto after=inspectArchive(output);if(expected(*after.nativeModel)!=want){QDir().mkpath(QString::fromUtf8(OM9_LEGACY_HATCH_EVIDENCE_DIR));save(QString::fromUtf8(OM9_LEGACY_HATCH_EVIDENCE_DIR)+"/mismatch.json",QJsonObject{{"label",label},{"expected",want},{"after",expected(*after.nativeModel)}});}require(after.document["source_version"]==50&&after.document["scale_mm"]==before.document["scale_mm"]&&expected(*after.nativeModel)==want,"legacy decode/reencode exact Hatch fields and graph");require(bytes(source)==inputBytes,"legacy Hatch source bytes immutable");
    QDir().mkpath(QString::fromUtf8(OM9_LEGACY_HATCH_EVIDENCE_DIR));save(QString::fromUtf8(OM9_LEGACY_HATCH_EVIDENCE_DIR)+"/case-"+QString::number(cases)+".json",QJsonObject{{"label",label},{"expected",want},{"legacy_report",proof},{"after",expected(*after.nativeModel)}});++cases;std::cout<<label.toStdString()<<": exact SDK2013 Hatch fields and reencode PASS\n";
}
int main(){try{ON::Begin();QTemporaryDir temporary;require(temporary.isValid(),"legacy Hatch temporary directory");auto dir=std::filesystem::path(temporary.path().toStdWString());
    for(auto units:{ON::LengthUnitSystem::Millimeters,ON::LengthUnitSystem::Centimeters}){
        ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);ON_Layer layer;layer.SetName(L"Legacy Hatch layer");model.AddModelComponent(layer);ON_DimStyle style;style.SetName(L"Explicit legacy Hatch style");auto styleRef=model.AddModelComponent(style);model.m_settings.SetCurrentDimensionStyleId(styleRef.ModelComponent()->Id());ON_HatchPattern pattern;pattern.SetFillType(ON_HatchPattern::HatchFillType::Lines);pattern.SetName(L"Legacy lines");pattern.SetDescription(L"Line-frame and signed dash proof");pattern.SetUserString(L"Pattern",L"Native shared text");for(int i=0;i<2;++i){ON_SimpleArray<double> dashes;dashes.Append(3.25);dashes.Append(-1.75);dashes.Append(0);pattern.AddHatchLine(ON_HatchLine(i?1.234567891:0.345678912,ON_2dPoint(0.375,0.625),ON_2dVector(0.5,1.25),dashes));}auto patternRef=model.AddModelComponent(pattern);ON_NurbsCurve outer,inner;require(ON_Circle(ON_xy_plane,5).GetNurbForm(outer)&&ON_Circle(ON_xy_plane,1).GetNurbForm(inner),"legacy rational loop create");outer.ChangeDimension(2);inner.ChangeDimension(2);outer.SetUserString(L"Loop",L"Rational outer");inner.SetUserString(L"Loop",L"Rational inner");ON_SimpleArray<const ON_Curve*> loops;loops.Append(&outer);loops.Append(&inner);ON_Hatch h;require(h.Create(ON_Plane(ON_3dPoint(10,20,30),ON_3dVector(1,2,3)),loops,patternRef.ModelComponent()->Index(),-0.456789123,2.345678912),"legacy tilted hatch create");h.SetBasePoint(ON_2dPoint(1.25,2.75));h.SetUserString(L"Hatch",L"Native independent reader");ON_3dmObjectAttributes attrs;attrs.m_name=L"Legacy source hatch";attrs.SetUserString(L"Attribute",L"Native attribute text");auto ref=model.AddModelGeometryComponent(&h,&attrs);auto uuid=ref.ModelComponent()->Id();auto path=dir/(units==ON::LengthUnitSystem::Millimeters?"source-mm.3dm":"source-cm.3dm");require(model.Write(path.c_str(),5,nullptr),"modern native legacy input write");auto immutable=bytes(path);auto source=inspectArchive(path);QString unit=units==ON::LengthUnitSystem::Millimeters?"mm":"cm",ns="00000000-0000-4000-8000-000000000111";legacy(path,dir,unit+" source");
        QJsonObject selected{{"namespace",ns},{"source_uuid",id(uuid)},{"host_id","legacy-hatch"},{"action","unchanged"}};QJsonObject request{{"schema_version",1},{"sources",QJsonArray{QJsonObject{{"namespace",ns},{"snapshot",QString::fromStdWString(path.wstring())},{"archive_sha256",source.document["archive_sha256"]},{"scale_mm",source.document["scale_mm"]}}}},{"selected",QJsonArray{selected}}};auto output=dir/"modern.3dm";writePreservedArchive(request,output);legacy(output,dir,unit+" normalized selected");
        auto fields=source.document["records"].toArray()[0].toObject()["hatch_current"].toObject();fields["plane"]=QJsonArray{40,50,60,0,1,0,0,0,1,1,0,0,1,0,0,-40};fields["base_point"]=QJsonArray{3.125,4.25};fields["rotation"]=-0.987654321;fields["scale"]=0.0000123456789;QJsonArray matrix{1,0,0,5,0,1,0,6,0,0,1,7,0,0,0,1};selected["action"]="transform";selected["geometry_matrix"]=matrix;
        for(auto builtin:{&ON_HatchPattern::Solid,&ON_HatchPattern::Grid60,&ON_HatchPattern::HatchDash}){fields["pattern_uuid"]=id(builtin->Id());selected["hatch_fields"]=fields;request["selected"]=QJsonArray{selected};writePreservedArchive(request,output);legacy(output,dir,unit+" current "+text(builtin->Name()));}
        fields["pattern_uuid"]=id(patternRef.ModelComponent()->Id());selected["hatch_fields"]=fields;matrix=QJsonArray{-2,0.5,0,5,0,3,0.25,6,0,0,4,7,0,0,0,1};selected["geometry_matrix"]=matrix;request["selected"]=QJsonArray{selected};writePreservedArchive(request,output);legacy(output,dir,unit+" current reflected/sheared affine");
        for(bool follow:{false,true}){ON_UUID memberId,definitionId,instanceId;ON_CreateUuid(memberId);ON_CreateUuid(definitionId);ON_CreateUuid(instanceId);QJsonObject copy{{"namespace",ns},{"source_uuid",id(uuid)},{"output_uuid",id(memberId)},{"host_id","legacy-copied-member"},{"follow_canonical",follow},{"member_matrix",matrix}};if(!follow){copy["follow_canonical"]=true;copy["independent_overlay"]=QJsonObject{{"action","transform"},{"hatch_fields",fields}};}
            QJsonObject definition{{"namespace",ns},{"source_uuid",id(definitionId)},{"host_id","legacy-definition"},{"name","Legacy native Hatch definition"},{"member_uuids",QJsonArray{id(memberId)}}};QJsonObject instance{{"namespace",ns},{"source_uuid",id(instanceId)},{"host_id","legacy-instance"},{"role","top-level"},{"instance_definition_uuid",id(definitionId)},{"instance_matrix",QJsonArray{1,0,0,100,0,1,0,200,0,0,1,300,0,0,0,1}}};auto copied=request;copied["selected"]=QJsonArray{};if(follow)copied["selected"]=QJsonArray{selected};copied["member_copies"]=QJsonArray{copy};copied["new_definitions"]=QJsonArray{definition};copied["new_instances"]=QJsonArray{instance};writePreservedArchive(copied,output);legacy(output,dir,unit+(follow?" canonical copied block":" independent copied block"));}
        // Genuine repeated definitions share one canonical native Hatch member.
        auto memberAttrs=attrs;memberAttrs.SetMode(ON::idef_object);auto shared=model.AddModelGeometryComponent(&h,&memberAttrs);QJsonArray roots;
        for(int i=0;i<2;++i){ON_InstanceDefinition def;def.SetName(i?L"Legacy shared B":L"Legacy shared A");def.AddInstanceGeometryId(shared.ModelComponent()->Id());def.SetBoundingBox(h.BoundingBox());auto target=model.AddModelComponent(def);ON_InstanceRef instance;instance.m_instance_definition_uuid=target.ModelComponent()->Id();instance.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(100+i*400,200+i*400,300+i*400));instance.m_bbox=h.BoundingBox();instance.m_bbox.Transform(instance.m_xform);auto instanceRef=model.AddModelGeometryComponent(&instance,&attrs);roots.append(QJsonObject{{"namespace",ns},{"source_uuid",id(instanceRef.ModelComponent()->Id())},{"host_id",QString("legacy-shared-%1").arg(i)},{"action","unchanged"}});}
        auto sharedPath=dir/"shared-source.3dm";require(model.Write(sharedPath.c_str(),5,nullptr),"legacy shared fixture write");auto sharedInventory=inspectArchive(sharedPath);QJsonObject sharedEdit{{"namespace",ns},{"source_uuid",id(shared.ModelComponent()->Id())},{"host_id","legacy-shared-canonical"},{"action","transform"},{"hatch_fields",fields},{"geometry_matrix",matrix}};auto sharedRequest=request;sharedRequest["sources"]=QJsonArray{QJsonObject{{"namespace",ns},{"snapshot",QString::fromStdWString(sharedPath.wstring())},{"archive_sha256",sharedInventory.document["archive_sha256"]},{"scale_mm",sharedInventory.document["scale_mm"]}}};sharedRequest["selected"]=roots;sharedRequest["dependency_overlays"]=QJsonArray{sharedEdit};writePreservedArchive(sharedRequest,output);legacy(output,dir,unit+" genuine shared canonical definitions");
        auto gradient=h;gradient.SetGradientType(ON_GradientType::Linear);ON_SimpleArray<ON_ColorStop> colors;colors.Append(ON_ColorStop(ON_Color(17,31,47),0));colors.Append(ON_ColorStop(ON_Color(101,151,201),1));require(gradient.SetGradientColors(colors)&&gradient.SetGradientEndPoints(ON_3dPoint(10,20,30),ON_3dPoint(40,50,60))&&gradient.SetGradientRepeat(2.5),"gradient native fields create");auto gradientRef=model.AddModelGeometryComponent(&gradient,&attrs);auto gradientId=gradientRef.ModelComponent()->Id();auto newer=dir/"gradient80.3dm",staged5=dir/"gradient50.3dm";require(model.Write(newer.c_str(),80,nullptr)&&model.Write(staged5.c_str(),5,nullptr),"gradient deliberate version80/50 probes");auto native80=inspectArchive(newer),native50=inspectArchive(staged5);auto find=[&](const ArchiveInventory& archive){return ON_Hatch::Cast(ON_ModelGeometryComponent::Cast(archive.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,gradientId).ModelComponent())->Geometry(nullptr));};auto sourceGradient=find(native80),stagedGradient=find(native50);require(sourceGradient&&stagedGradient&&sourceGradient->GetGradientType()==ON_GradientType::Linear&&stagedGradient->GetGradientType()==ON_GradientType::None,"modern version5 serialization loses gradient before legacy decoder");ON_SimpleArray<ON_ColorStop> kept,lost;sourceGradient->GetGradientColors(kept);stagedGradient->GetGradientColors(lost);require(kept.Count()==2&&lost.Count()==0&&sourceGradient->GetGradientRepeat()==2.5&&stagedGradient->GetGradientRepeat()==0,"gradient colors/repeat lost at version5 boundary");legacy(staged5,dir,unit+" deliberately staged gradient already lost in modern version5");
        auto gradientRequest=request;gradientRequest["sources"]=QJsonArray{QJsonObject{{"namespace",ns},{"snapshot",QString::fromStdWString(newer.wstring())},{"archive_sha256",native80.document["archive_sha256"]},{"scale_mm",native80.document["scale_mm"]}}};gradientRequest["selected"]=QJsonArray{QJsonObject{{"namespace",ns},{"source_uuid",id(gradientId)},{"host_id","gradient-proof"},{"action","unchanged"}}};auto sentinel=bytes(output);bool refused=false;try{writePreservedArchive(gradientRequest,output);}catch(const ExchangeError&){refused=true;}require(refused&&bytes(output)==sentinel,"production gradient selection refuses before destination replacement");
        auto rawPath=dir/("raw-"+unit.toStdString()+".3dm"),rawReport=dir/("raw-"+unit.toStdString()+".json");QProcess raw;raw.start(QString::fromUtf8(OM9_LEGACY_HATCH_READER_EXE),QStringList{QString::fromStdWString(staged5.wstring()),QString::fromStdWString(rawPath.wstring()),QString::fromStdWString(rawReport.wstring()),"--raw-attributes"});require(raw.waitForStarted(10000)&&raw.waitForFinished(30000)&&raw.exitStatus()==QProcess::NormalExit&&raw.exitCode()==0,"raw legacy relocation probe process");auto rawProof=QJsonDocument::fromJson(bytes(rawReport)).object();auto rawArchive=inspectArchive(rawPath);auto beforeRaw=expected(*native50.nativeModel),afterRaw=expected(*rawArchive.nativeModel);require(rawProof["stale_attribute_owners"].toInt()>0&&rawProof["attribute_owner_repairs"]==0,"raw SDK2013 exposes attribute table relocation owners");int lostAttributes=0;auto oldRows=beforeRaw["hatches"].toArray(),newRows=afterRaw["hatches"].toArray();require(oldRows.size()==newRows.size(),"raw relocation preserves Hatch count");for(int i=0;i<oldRows.size();++i){auto a=oldRows[i].toObject(),b=newRows[i].toObject();if(a["attribute_user_strings"]!=b["attribute_user_strings"])++lostAttributes;a.remove("attribute_user_strings");b.remove("attribute_user_strings");require(a==b,"raw relocation loss must be isolated to attribute userdata");}require(lostAttributes>0,"raw SDK2013 writer skips misowned attribute userdata");save(QString::fromUtf8(OM9_LEGACY_HATCH_EVIDENCE_DIR)+"/raw-relocation-"+unit+".json",QJsonObject{{"raw_report",rawProof},{"expected",beforeRaw},{"raw_after",afterRaw},{"lost_attribute_rows",lostAttributes},{"repaired_case",cases-1}});
        save(QString::fromUtf8(OM9_LEGACY_HATCH_EVIDENCE_DIR)+"/gradient-"+unit+".json",QJsonObject{{"source_version",80},{"staged_version",50},{"source_gradient_type",static_cast<int>(sourceGradient->GetGradientType())},{"staged_gradient_type",static_cast<int>(stagedGradient->GetGradientType())},{"source_color_count",kept.Count()},{"staged_color_count",lost.Count()},{"source_repeat",sourceGradient->GetGradientRepeat()},{"staged_repeat",stagedGradient->GetGradientRepeat()},{"production_rejects_atomically",true}});
        require(bytes(path)==immutable,"all legacy tests preserve source bytes");
    }
    require(cases==20,"legacy Hatch complete20 native cases");std::cout<<"independent SDK201307115 Hatch20 cases and gradient loss probes PASS\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
