#include "ThreeDmArchive.h"
#include <BRep_Tool.hxx>
#include <TopoDS.hxx>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool ok,const char* text){if(!ok)throw ExchangeError(text);}
int main(){try{ON::Begin();ONX_Model m;m.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);
ON_Layer layer;layer.SetName(L"Blocks");m.AddModelComponent(layer);
ON_3dmObjectAttributes a;a.SetMode(ON::idef_object);a.SetColorSource(ON::color_from_parent);a.m_name=L"Point";
ON_Point p(1,2,3);auto pr=m.AddModelGeometryComponent(&p,&a);
ON_InstanceDefinition inner;inner.SetName(L"Inner");inner.AddInstanceGeometryId(pr.ModelComponent()->Id());auto ir=m.AddModelComponent(inner);
ON_InstanceRef nested;nested.m_instance_definition_uuid=ir.ModelComponent()->Id();nested.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(10,0,0));auto nr=m.AddModelGeometryComponent(&nested,&a);
ON_InstanceDefinition outer;outer.SetName(L"Outer");outer.AddInstanceGeometryId(nr.ModelComponent()->Id());auto outerRef=m.AddModelComponent(outer);
ON_InstanceRef instance;instance.m_instance_definition_uuid=outerRef.ModelComponent()->Id();instance.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(0,20,0));instance.m_xform[3][0]=1e-18;
ON_3dmObjectAttributes top;top.m_name=L"Placement";top.m_color=ON_Color(11,22,33);top.SetColorSource(ON::color_from_object);top.SetMode(ON::locked_object);m.AddModelGeometryComponent(&instance,&top);
instance.m_xform=ON_Xform::IdentityTransformation;instance.m_xform[0][0]=-2;instance.m_xform[1][1]=3;instance.m_xform[2][2]=4;m.AddModelGeometryComponent(&instance,&top);
auto path=std::filesystem::temp_directory_path()/"om9-nested-blocks.3dm";require(m.Write(path.c_str(),5,nullptr),"fixture write");auto result=readArchive(path);require(result.items.size()==2,"definition geometry must not duplicate instances");
auto point=BRep_Tool::Pnt(TopoDS::Vertex(std::get<TopoDS_Shape>(result.items[0].geometry)));require(point.Distance(gp_Pnt(11,22,3))<1e-8,"nested transform composition");
point=BRep_Tool::Pnt(TopoDS::Vertex(std::get<TopoDS_Shape>(result.items[1].geometry)));require(point.Distance(gp_Pnt(-22,6,12))<1e-8,"nonuniform reflected transform");
for(auto& item:result.items)require(item.locked&&item.color==std::array<int,3>{11,22,33},"parent color and lock");
auto output=path.parent_path()/"om9-nested-blocks-roundtrip.3dm";writeArchive5(result,output);require(readArchive(output).items.size()==2,"flattened roundtrip");
auto rejects=[&](ONX_Model& invalid,const char* filename,const char* message){auto file=path.parent_path()/filename;require(invalid.Write(file.c_str(),5,nullptr),"invalid fixture write");bool rejected=false;try{readArchive(file);}catch(const ExchangeError& e){rejected=std::string(e.what()).find(message)!=std::string::npos;}require(rejected,message);};
ONX_Model missing;missing.AddModelComponent(layer);ON_InstanceRef missingRef;ON_CreateUuid(missingRef.m_instance_definition_uuid);missing.AddModelGeometryComponent(&missingRef,&top);rejects(missing,"om9-missing-block.3dm","Missing block definition");
ONX_Model cyclic;cyclic.AddModelComponent(layer);ON_UUID cycleId;ON_CreateUuid(cycleId);ON_InstanceRef cycleRef;cycleRef.m_instance_definition_uuid=cycleId;auto cycleMember=cyclic.AddModelGeometryComponent(&cycleRef,&a);ON_InstanceDefinition cycleDefinition;cycleDefinition.SetName(L"Cycle");cycleDefinition.SetId(cycleId);cycleDefinition.AddInstanceGeometryId(cycleMember.ModelComponent()->Id());cyclic.AddModelComponent(cycleDefinition);cyclic.AddModelGeometryComponent(&cycleRef,&top);rejects(cyclic,"om9-cycle-block.3dm","Cyclic block definition");
ON_InstanceDefinition shared;shared.SetName(L"Shared member definition");shared.AddInstanceGeometryId(pr.ModelComponent()->Id());auto sharedRef=m.AddModelComponent(shared);ON_InstanceRef sharedInstance;sharedInstance.m_instance_definition_uuid=sharedRef.ModelComponent()->Id();sharedInstance.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(30,0,0));m.AddModelGeometryComponent(&sharedInstance,&top);require(m.Write((path.parent_path()/"om9-shared-block-members.3dm").c_str(),5,nullptr),"shared member fixture write");
ONX_Model mixed;mixed.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);mixed.AddModelComponent(layer);
ON_3dPoint corners[8]={ON_3dPoint(0,0,0),ON_3dPoint(2,0,0),ON_3dPoint(2,3,0),ON_3dPoint(0,3,0),ON_3dPoint(0,0,4),ON_3dPoint(2,0,4),ON_3dPoint(2,3,4),ON_3dPoint(0,3,4)};
std::unique_ptr<ON_Brep> box(ON_BrepBox(corners));require(box&&box->IsValid(),"mixed block box valid");require(box->SolidOrientation()==2,"synthetic ON_BrepBox source has unspecified SDK orientation, not declared outward");auto boxRef=mixed.AddModelGeometryComponent(box.get(),&a);
ON_Mesh mesh;mesh.SetVertex(0,ON_3dPoint(0,0,0));mesh.SetVertex(1,ON_3dPoint(2,0,0));mesh.SetVertex(2,ON_3dPoint(0,3,0));mesh.SetTriangle(0,0,1,2);mesh.ComputeVertexNormals();require(mesh.IsValid(),"mixed block mesh valid");auto meshRef=mixed.AddModelGeometryComponent(&mesh,&a);
ON_InstanceDefinition mixedDefinition;mixedDefinition.SetName(L"Mixed shear");mixedDefinition.AddInstanceGeometryId(boxRef.ModelComponent()->Id());mixedDefinition.AddInstanceGeometryId(meshRef.ModelComponent()->Id());auto mixedRef=mixed.AddModelComponent(mixedDefinition);
ON_InstanceRef shear;shear.m_instance_definition_uuid=mixedRef.ModelComponent()->Id();shear.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(10,20,30));shear.m_xform[0][1]=0.5;mixed.AddModelGeometryComponent(&shear,&top);
auto mixedPath=path.parent_path()/"om9-mixed-shear-block.3dm";require(mixed.Write(mixedPath.c_str(),5,nullptr),"mixed shear fixture write");require(readArchive(mixedPath).items.size()==2,"mixed shear members expanded");
ON_InstanceDefinition sharedMixed;sharedMixed.SetName(L"Shared mixed reflected");sharedMixed.AddInstanceGeometryId(boxRef.ModelComponent()->Id());sharedMixed.AddInstanceGeometryId(meshRef.ModelComponent()->Id());auto sharedMixedRef=mixed.AddModelComponent(sharedMixed);
ON_InstanceRef reflectedMixed;reflectedMixed.m_instance_definition_uuid=sharedMixedRef.ModelComponent()->Id();reflectedMixed.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(40,50,60));reflectedMixed.m_xform[0][0]=-2;reflectedMixed.m_xform[1][1]=3;reflectedMixed.m_xform[2][2]=4;mixed.AddModelGeometryComponent(&reflectedMixed,&top);
auto sharedMixedPath=path.parent_path()/"om9-shared-mixed-shear-block.3dm";require(mixed.Write(sharedMixedPath.c_str(),5,nullptr),"shared mixed shear fixture write");auto sharedMixedRead=readArchive(sharedMixedPath);require(sharedMixedRead.items.size()==4,"shared mixed geometry expands both affine placements");unsigned sharedBoxes=0,sharedMeshes=0;for(auto& item:sharedMixedRead.items){if(auto shape=std::get_if<TopoDS_Shape>(&item.geometry)){++sharedBoxes;require(!shape->IsNull(),"shared mixed CAD conversion");}else if(std::holds_alternative<MeshData>(item.geometry))++sharedMeshes;}require(sharedBoxes==2&&sharedMeshes==2,"shared mixed fixture keeps CAD and mesh types");
ONX_Model retained;retained.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);retained.AddModelComponent(layer);
auto retainedPoint=retained.AddModelGeometryComponent(&p,&a);ON_TextDot retainedDot(ON_3dPoint(4,5,6),L"Native retained member",L"");auto retainedText=retained.AddModelGeometryComponent(&retainedDot,&a);
ON_InstanceDefinition retainedDefinition;retainedDefinition.SetName(L"Retained members");retainedDefinition.AddInstanceGeometryId(retainedPoint.ModelComponent()->Id());retainedDefinition.AddInstanceGeometryId(retainedText.ModelComponent()->Id());auto retainedDef=retained.AddModelComponent(retainedDefinition);
ON_InstanceRef retainedInstance;retainedInstance.m_instance_definition_uuid=retainedDef.ModelComponent()->Id();retainedInstance.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(10,20,30));retained.AddModelGeometryComponent(&retainedInstance,&top);
require(retained.Write((path.parent_path()/"om9-retained-block-members.3dm").c_str(),5,nullptr),"retained member fixture write");
ONX_Model curveModel;curveModel.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);curveModel.AddModelComponent(layer);
ON_NurbsCurve curve(2,true,3,4);double curveKnots[5]={0,0,0.3,1,1};for(int i=0;i<5;++i)curve.SetKnot(i,curveKnots[i]);
curve.SetCV(0,ON_4dPoint(0,0,0,1));curve.SetCV(1,ON_4dPoint(4,6,0,2));curve.SetCV(2,ON_4dPoint(2,-0.5,0,0.5));curve.SetCV(3,ON_4dPoint(6,0,0,1));require(curve.IsValid(),"rational shared curve fixture valid");
auto curveMember=curveModel.AddModelGeometryComponent(&curve,&a);
ON_Point alternativePoint(9,8,7);auto alternativeMember=curveModel.AddModelGeometryComponent(&alternativePoint,&a);ON_InstanceDefinition alternativeDefinition;alternativeDefinition.SetName(L"Alternative point");alternativeDefinition.AddInstanceGeometryId(alternativeMember.ModelComponent()->Id());curveModel.AddModelComponent(alternativeDefinition);
for(auto name:{L"Curve A",L"Curve B"}){ON_InstanceDefinition curveDefinition;curveDefinition.SetName(name);curveDefinition.AddInstanceGeometryId(curveMember.ModelComponent()->Id());auto curveDef=curveModel.AddModelComponent(curveDefinition);ON_InstanceRef curveInstance;curveInstance.m_instance_definition_uuid=curveDef.ModelComponent()->Id();curveInstance.m_xform=ON_Xform::IdentityTransformation;curveModel.AddModelGeometryComponent(&curveInstance,&top);}
auto curvePath=path.parent_path()/"om9-shared-rational-curve.3dm";require(curveModel.Write(curvePath.c_str(),5,nullptr),"shared rational curve fixture write");require(readArchive(curvePath).items.size()==2,"shared rational curve expands both placements");
ONX_Model references;references.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);references.AddModelComponent(layer);
auto referencePoint=references.AddModelGeometryComponent(&p,&a);auto referenceBox=references.AddModelGeometryComponent(box.get(),&a);auto referenceMesh=references.AddModelGeometryComponent(&mesh,&a);
ON_InstanceDefinition referenceA;referenceA.SetName(L"Reference A");referenceA.AddInstanceGeometryId(referencePoint.ModelComponent()->Id());auto referenceARef=references.AddModelComponent(referenceA);
ON_InstanceDefinition referenceB;referenceB.SetName(L"Reference B");referenceB.AddInstanceGeometryId(referenceBox.ModelComponent()->Id());referenceB.AddInstanceGeometryId(referenceMesh.ModelComponent()->Id());references.AddModelComponent(referenceB);
ON_InstanceRef memberReference;memberReference.m_instance_definition_uuid=referenceARef.ModelComponent()->Id();memberReference.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(20,30,40));auto memberReferenceRef=references.AddModelGeometryComponent(&memberReference,&a);
ON_InstanceDefinition referenceC;referenceC.SetName(L"Reference C");referenceC.AddInstanceGeometryId(memberReferenceRef.ModelComponent()->Id());auto referenceCRef=references.AddModelComponent(referenceC);
ON_3dmObjectAttributes referenceTop=top;referenceTop.SetMode(ON::normal_object);referenceTop.m_name=L"Rigid reference";ON_InstanceRef referenceRoot;referenceRoot.m_instance_definition_uuid=referenceARef.ModelComponent()->Id();referenceRoot.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(10,20,30));references.AddModelGeometryComponent(&referenceRoot,&referenceTop);
referenceTop.m_name=L"Affine reference";referenceRoot.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(100,200,300));referenceRoot.m_xform[0][1]=0.5;references.AddModelGeometryComponent(&referenceRoot,&referenceTop);
referenceTop.m_name=L"Nested reference";referenceRoot.m_instance_definition_uuid=referenceCRef.ModelComponent()->Id();referenceRoot.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(5,6,7));references.AddModelGeometryComponent(&referenceRoot,&referenceTop);
require(references.Write((path.parent_path()/"om9-reference-edit.3dm").c_str(),5,nullptr),"reference-edit fixture write");
std::cout<<"nested and mixed shear blocks PASS\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
