#include "ThreeDmArchive.h"
#include <BRepPrimAPI_MakeBox.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <fstream>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
void require(bool v,const char* msg){if(!v)throw std::runtime_error(msg);}
int main(){try{ON::Begin();auto root=std::filesystem::temp_directory_path()/"om9-3dm-native";std::filesystem::create_directories(root);
    ExchangeModel model;ExchangeItem item;item.name="Jewelry α";item.layer="Metal::Gold";item.color={255,120,12};item.visible=false;item.locked=true;item.geometry=BRepPrimAPI_MakeBox(10,10,10).Shape();model.items.push_back(item);writeArchive5(model,root/"box.3dm");auto result=readArchive(root/"box.3dm");require(result.items.size()==1,"count");require(result.items[0].name==item.name&&result.items[0].layer==item.layer,"unicode/layer names");require(result.items[0].color==item.color,"color");require(!result.items[0].visible,"visibility");require(result.items[0].locked,"lock metadata");
    std::ifstream f(root/"box.3dm",std::ios::binary);std::string header(32,'\0');f.read(header.data(),32);require(header.find("5")!=std::string::npos,"Rhino 5 header");
    std::cerr<<"metadata PASS\n";ONX_Model inch;ON_Layer defaultLayer;defaultLayer.SetName(L"Default");inch.AddModelComponent(defaultLayer);inch.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Inches);ON_LineCurve line(ON_3dPoint(0,0,0),ON_3dPoint(1,0,0));ON_3dmObjectAttributes a;inch.AddModelGeometryComponent(&line,&a);require(inch.Write((root/"inch.3dm").c_str(),5,nullptr),"fixture write");std::cerr<<"inch written\n";auto converted=readArchive(root/"inch.3dm");GProp_GProps length;BRepGProp::LinearProperties(std::get<TopoDS_Shape>(converted.items[0].geometry),length);require(std::abs(length.Mass()-25.4)<1e-7,"inch scale");
    inch.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::None);inch.Write((root/"unitless.3dm").c_str(),5,nullptr);bool rejected=false;try{readArchive(root/"unitless.3dm");}catch(const ExchangeError&){rejected=true;}require(rejected,"unitless must reject");require(readArchive(root/"unitless.3dm",2).scaleMm==2,"explicit units");
    std::ofstream(root/"bad.3dm",std::ios::binary)<<"bad";rejected=false;try{readArchive(root/"bad.3dm");}catch(const ExchangeError&){rejected=true;}require(rejected,"malformed input");
    ONX_Model nested;ON_Layer parent;parent.SetName(L"Parent");parent.SetVisible(false);parent.SetLocked(true);auto pr=nested.AddModelComponent(parent);ON_Layer child;child.SetName(L"Child");child.SetParentId(pr.ModelComponent()->Id());auto cr=nested.AddModelComponent(child);ON_3dmObjectAttributes ca;ca.m_layer_index=ON_Layer::Cast(cr.ModelComponent())->Index();nested.AddModelGeometryComponent(&line,&ca);require(nested.Write((root/"nested.3dm").c_str(),5,nullptr),"nested fixture");auto nr=readArchive(root/"nested.3dm");require(!nr.items[0].visible&&nr.items[0].locked,"ancestor layer states");
    ONX_Model annotation;annotation.AddModelComponent(defaultLayer);ON_TextDot dot(ON_3dPoint(0,0,0),L"Unsupported note",L"");annotation.AddModelGeometryComponent(&dot,&a);annotation.Write((root/"unsupported.3dm").c_str(),5,nullptr);rejected=false;try{readArchive(root/"unsupported.3dm");}catch(const ExchangeError&){rejected=true;}require(rejected,"unsupported annotation rejected");
    ONX_Model extrusionModel;extrusionModel.m_settings.m_ModelUnitsAndTolerances.m_absolute_tolerance=1e-7;extrusionModel.AddModelComponent(defaultLayer);ON_ArcCurve profile(ON_Circle(ON_xy_plane,4));std::unique_ptr<ON_Extrusion> extrusion(ON_Extrusion::CreateFrom3dCurve(profile,nullptr,10,true));require(bool(extrusion),"extrusion fixture");extrusionModel.AddModelGeometryComponent(extrusion.get(),&a);require(extrusionModel.Write((root/"extrusion.3dm").c_str(),5,nullptr),"extrusion archive");auto er=readArchive(root/"extrusion.3dm");GProp_GProps volume;BRepGProp::VolumeProperties(std::get<TopoDS_Shape>(er.items[0].geometry),volume,1e-10);std::cerr.precision(17);std::cerr<<"extrusion volume "<<volume.Mass()<<" expected "<<160*ON_PI<<"\n";require(std::abs(volume.Mass()-160*ON_PI)<1e-4,"extrusion solid volume");
    auto invalid=exportBrep(BRepPrimAPI_MakeBox(1,1,1).Shape(),1e-6);invalid->m_T[0].m_c2i=-1;rejected=false;try{importBrep(*invalid,1e-6);}catch(const ExchangeError&){rejected=true;}require(rejected,"invalid trim rejected");
    std::cout<<"OM9-FILE-012 archive PASS; fixtures "<<root<<'\n';return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
