#include "ThreeDmInventory.h"
#include <iostream>
#include <fstream>
#include <BRepPrimAPI_MakeBox.hxx>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool v,const char* m){if(!v)throw ExchangeError(m);}
int main(){try{ON::Begin();ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);
ON_Layer layer;layer.SetName(L"Mixed");model.AddModelComponent(layer);ON_Material material;material.SetName(L"Gold");ON_Texture texture;texture.m_image_file_reference.SetFullPath(L"Z:/untrusted-do-not-open/missing.png",false);material.m_textures.Append(texture);model.AddModelComponent(material);ON_Group group;group.SetName(L"Group");model.AddModelComponent(group);ON_DimStyle style;style.SetName(L"Dimensions");model.AddModelComponent(style);
ON_3dmObjectAttributes a;a.SetUserString(L"AttributeTest",L"retained");ON_Point point(1,2,3);point.SetUserString(L"Test",L"retained");model.AddModelGeometryComponent(&point,&a);ON_TextDot dot(ON_3dPoint(4,5,6),L"Note",L"");model.AddModelGeometryComponent(&dot,&a);ON_PointCloud cloud;cloud.m_P.Append(ON_3dPoint(7,8,9));model.AddModelGeometryComponent(&cloud,&a);
auto brep=exportBrep(BRepPrimAPI_MakeBox(2,3,4).Shape(),1e-6);model.AddModelGeometryComponent(brep.get(),&a);
ON_3dmObjectAttributes member;member.SetMode(ON::idef_object);auto pointRef=model.AddModelGeometryComponent(&point,&member);ON_InstanceDefinition definition;definition.SetName(L"Embedded");definition.AddInstanceGeometryId(pointRef.ModelComponent()->Id());auto definitionRef=model.AddModelComponent(definition);ON_InstanceRef instance;instance.m_instance_definition_uuid=definitionRef.ModelComponent()->Id();model.AddModelGeometryComponent(&instance,&a);
auto path=std::filesystem::temp_directory_path()/"om9-inventory.3dm";require(model.Write(path.c_str(),5,nullptr),"fixture write");auto inventory=inspectArchive(path);auto json=inventory.document;
require(json["schema_version"].toInt()==1,"schema");require(json["records"].toArray().size()==6,"all geometry inventoried");require(json["components"].toArray().size()>=5,"component tables inventoried");require(json["archive_sha256"].toString().size()==64,"source hash");
bool text=false,points=false,user=false;for(auto r:json["records"].toArray()){auto o=r.toObject();require(!o["source_uuid"].toString().isEmpty(),"identity");text|=o["class_name"].toString()=="ON_TextDot";points|=o["class_name"].toString()=="ON_PointCloud";user|=o["user_strings"].toArray().size()>0;}
require(text&&points&&user,"mixed types and userdata accounted for");require(json["source_version"].toInt()==50||json["source_version"].toInt()==5,"source version");require(json["resources"].isArray()&&json["issues"].isArray(),"report arrays");
require(json["records"].toArray()[0].toObject()["attribute_user_strings"].toArray().size()==1,"attribute user text inventoried");
require(json["resources"].toArray().size()>=1&&json["resources"].toArray()[0].toObject()["resolution"]=="not opened","external resources inventoried without opening");
bool role=false,dependency=false;for(auto value:json["records"].toArray()){auto row=value.toObject();role|=row["role"]=="definition-member";dependency|=row["dependencies"].toArray().size()>0;}require(role&&dependency,"block identity graph");require(json["issues"].toArray().isEmpty(),"valid dependency graph");
ONX_Model missing;missing.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);ON_CreateUuid(instance.m_instance_definition_uuid);missing.AddModelGeometryComponent(&instance,&a);auto missingPath=path.parent_path()/"om9-inventory-missing.3dm";require(missing.Write(missingPath.c_str(),5,nullptr),"missing fixture write");require(!inspectArchive(missingPath).document["issues"].toArray().isEmpty(),"missing dependency reported");
std::ofstream(path.parent_path()/"om9-inventory-bad.3dm")<<"bad";bool rejected=false;try{inspectArchive(path.parent_path()/"om9-inventory-bad.3dm");}catch(const ExchangeError&){rejected=true;}require(rejected,"bad archive rejected");
auto oversized=path.parent_path()/"om9-inventory-oversized.3dm";std::ofstream(oversized)<<"x";std::filesystem::resize_file(oversized,512ULL*1024*1024+1);rejected=false;try{inspectArchive(oversized);}catch(const ExchangeError&){rejected=true;}std::filesystem::remove(oversized);require(rejected,"512 MiB bound enforced");
model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::None);auto unitless=path.parent_path()/"om9-inventory-unitless.3dm";require(model.Write(unitless.c_str(),5,nullptr),"unitless write");rejected=false;try{inspectArchive(unitless);}catch(const ExchangeError& e){rejected=std::string(e.what()).find("unitless/custom units")!=std::string::npos;}require(rejected,"unitless prompt marker");require(inspectArchive(unitless,2).document["scale_mm"].toDouble()==2,"explicit scale");
std::cout<<"inventory PASS; fixture "<<path<<'\n';return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
