#include "ThreeDmArchive.h"
#include "ThreeDmInventory.h"
#include "ThreeDmMerge.h"
#include "ThreeDmHatch.h"
#include <QJsonArray>
#include <QJsonDocument>
#include <QFile>
#include <QProcess>
#include <QTemporaryDir>
#include <QDir>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool v,const char* s){if(!v)throw ExchangeError(s);}
static QByteArray bytes(const std::filesystem::path& p){QFile f(QString::fromStdWString(p.wstring()));require(f.open(QIODevice::ReadOnly),"legacy loop input read");return f.readAll();}
static void save(const QString& path,const QJsonObject& o){QFile f(path);require(f.open(QIODevice::WriteOnly|QIODevice::Truncate),"legacy loop proof write");auto data=QJsonDocument(o).toJson();require(f.write(data)==data.size(),"legacy loop proof bytes");}
static QJsonObject edit(QJsonObject n){
    auto kind=n["class_name"].toString();
    if(kind=="ON_NurbsCurve"){auto cvs=n["cvs"].toArray();for(int i=0;i<cvs.size();++i){auto cv=cvs[i].toArray();cv[0]=cv[0].toDouble()*1.5;cv[1]=cv[1].toDouble()*0.75;if(i==1&&n["rational"].toBool())for(int k=0;k<cv.size();++k)cv[k]=cv[k].toDouble()*2;cvs[i]=cv;}n["cvs"]=cvs;auto knots=n["knots"].toArray();for(int i=0;i<knots.size();++i)knots[i]=11+3*knots[i].toDouble();n["knots"]=knots;auto d=n["domain"].toArray();n["domain"]=QJsonArray{11+3*d[0].toDouble(),11+3*d[1].toDouble()};}
    else if(kind=="ON_ArcCurve"){n["radius"]=n["radius"].toDouble()*1.25;n["domain"]=QJsonArray{17,39};}
    else if(kind=="ON_LineCurve"||kind=="ON_PolylineCurve"){auto points=n["points"].toArray();for(int i=0;i<points.size();++i){auto p=points[i].toArray();p[0]=p[0].toDouble()*1.5;p[1]=p[1].toDouble()*0.75;points[i]=p;}n["points"]=points;}
    else if(kind=="ON_PolyCurve"){auto children=n["segments"].toArray();for(int i=0;i<children.size();++i)children[i]=edit(children[i].toObject());n["segments"]=children;}
    return n;
}
static QJsonObject expected(const ArchiveInventory& a){QJsonObject out;for(auto v:a.document["records"].toArray()){auto r=v.toObject();if(r["class_name"]!="ON_Hatch")continue;auto uuid=ON_UuidFromString(r["source_uuid"].toString().toLatin1().constData());auto hatch=ON_Hatch::Cast(ON_ModelGeometryComponent::Cast(a.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,uuid).ModelComponent())->Geometry(nullptr));require(hatch,"native Hatch expected source");out[r["source_uuid"].toString()]=QJsonObject{{"fields",hatchCurrentFields(*hatch,*a.nativeModel)},{"loops",r["hatch_loop_native"]},{"name",r["name"]},{"user_strings",r["user_strings"]},{"attribute_user_strings",r["attribute_user_strings"]}};}return out;}
static QJsonObject graph(const ArchiveInventory& a){QJsonObject definitions,instances;for(auto v:a.document["components"].toArray()){auto r=v.toObject();if(r["class_name"]=="ON_InstanceDefinition")definitions[r["source_uuid"].toString()]=r["member_uuids"];}for(auto v:a.document["records"].toArray()){auto r=v.toObject();if(r["class_name"]=="ON_InstanceRef")instances[r["source_uuid"].toString()]=QJsonObject{{"definition_uuid",r["instance_definition_uuid"]},{"matrix",r["instance_matrix"]}};}return {{"definitions",definitions},{"instances",instances}};}
static QJsonObject graph(const QJsonObject& proof){QJsonObject definitions,instances;for(auto v:proof["definitions"].toArray()){auto r=v.toObject();definitions[r["uuid"].toString()]=r["members"];}for(auto v:proof["instances"].toArray()){auto r=v.toObject();instances[r["uuid"].toString()]=QJsonObject{{"definition_uuid",r["definition_uuid"]},{"matrix",r["matrix"]}};}return {{"definitions",definitions},{"instances",instances}};}
static QString id(ON_UUID v){char s[37]{};ON_UuidToString(v,s);return QString::fromLatin1(s);}
static int cases=0;
static void legacy(const std::filesystem::path& input,const std::filesystem::path& dir,const QString& label){
    auto immutable=bytes(input);auto before=inspectArchive(input);auto want=expected(before);auto suffix=std::to_string(cases);auto output=dir/("old-"+suffix+".3dm"),report=dir/("old-"+suffix+".json");QProcess p;p.start(QString::fromUtf8(OM9_LEGACY_HATCH_READER_EXE),QStringList{QString::fromStdWString(input.wstring()),QString::fromStdWString(output.wstring()),QString::fromStdWString(report.wstring())});require(p.waitForStarted(10000)&&p.waitForFinished(30000),"legacy native loop process must terminate");if(p.exitCode()!=0)std::cerr<<p.readAllStandardError().constData();require(p.exitStatus()==QProcess::NormalExit&&p.exitCode()==0,"independent Rhino5 reader must accept exact native loop classes");
    auto proof=QJsonDocument::fromJson(bytes(report)).object();require(proof["sdk_version"]==201307115&&proof["source_version"]==50&&!proof["gradient_api_available"].toBool(),"legacy loop SDK identity");QJsonObject decoded;
    for(auto v:proof["hatches"].toArray()){auto h=v.toObject();QJsonObject fields;for(auto k:{"plane","base_point","rotation","scale","pattern_uuid"})fields[k]=h[k];decoded[h["uuid"].toString()]=QJsonObject{{"fields",fields},{"loops",h["native_loops"]},{"name",h["name"]},{"user_strings",h["user_strings"]},{"attribute_user_strings",h["attribute_user_strings"]}};}
    auto after=inspectArchive(output);auto actual=expected(after);if(decoded!=want||actual!=want){save(QString::fromUtf8(OM9_LEGACY_LOOP_EVIDENCE_DIR)+"/mismatch.json",{{"label",label},{"wanted",want},{"decoded",decoded},{"after",actual}});}
    require(graph(proof)==graph(before)&&graph(after)==graph(before),"legacy typed loop block graph and placements exact");require(decoded==want,"legacy exact loop classes, child parameters and metadata decode");require(actual==want,"legacy exact loop classes, child parameters and metadata reencode");require(after.document["source_version"]==50&&after.document["scale_mm"]==before.document["scale_mm"]&&bytes(input)==immutable,"legacy loop version/units/source immutability");
    save(QString::fromUtf8(OM9_LEGACY_LOOP_EVIDENCE_DIR)+QString("/case-%1.json").arg(cases),{{"label",label},{"expected",want},{"legacy",proof},{"reread",actual}});++cases;std::cout<<label.toStdString()<<" legacy typed loops PASS\n";
}
int main(){try{ON::Begin();QTemporaryDir staging;require(staging.isValid(),"legacy loop staging");auto dir=std::filesystem::path(staging.path().toStdWString());QDir().mkpath(QString::fromUtf8(OM9_LEGACY_LOOP_EVIDENCE_DIR));
    for(auto unit:{"mm","cm"}){auto input=std::filesystem::temp_directory_path()/(std::string("om9-hatch-loops-")+unit+".3dm");legacy(input,dir,QString(unit)+" original four native root types");auto a=inspectArchive(input);QString ns="00000000-0000-4000-8000-000000000155";QJsonArray selected;
        for(auto v:a.document["records"].toArray()){auto r=v.toObject();selected.append(QJsonObject{{"namespace",ns},{"source_uuid",r["source_uuid"]},{"host_id",r["source_uuid"]},{"action","unchanged"}});}
        QJsonObject request{{"schema_version",1},{"sources",QJsonArray{QJsonObject{{"namespace",ns},{"snapshot",QString::fromStdWString(input.wstring())},{"archive_sha256",a.document["archive_sha256"]},{"scale_mm",a.document["scale_mm"]}}}},{"selected",selected}};auto output=dir/"current.3dm";writePreservedArchive(request,output);legacy(output,dir,QString(unit)+" normalized all native loops");
        for(int i=0;i<selected.size();++i){auto s=selected[i].toObject(),row=a.document["records"].toArray()[i].toObject();auto fields=row["hatch_current"].toObject(),loops=row["hatch_loop_current"].toObject();auto values=loops["loops"].toArray();auto loop=values[0].toObject();loop["curve"]=edit(loop["curve"].toObject());values[0]=loop;loops["loops"]=values;fields["loops"]=loops;fields["base_point"]=QJsonArray{3.125,4.25};fields["rotation"]=-0.987654321;fields["scale"]=0.0000123456789;s["hatch_fields"]=fields;s["action"]="transform";s["geometry_matrix"]=QJsonArray{1,0,0,5,0,1,0,6,0,0,1,7,0,0,0,1};selected[i]=s;}
        request["selected"]=selected;writePreservedArchive(request,output);legacy(output,dir,QString(unit)+" edited native CV weight knot domain radius points and children");
        auto zero=request;auto zeroSelected=selected;for(int i=0;i<zeroSelected.size();++i){auto row=zeroSelected[i].toObject();auto fields=row["hatch_fields"].toObject();fields["base_point"]=QJsonArray{0,0};row["hatch_fields"]=fields;zeroSelected[i]=row;}zero["selected"]=zeroSelected;writePreservedArchive(zero,output);legacy(output,dir,QString(unit)+" zero movable base with exact typed loops");
        for(bool canonical:{false,true}){QJsonArray copies,members;ON_UUID definitionId,instanceId;ON_CreateUuid(definitionId);ON_CreateUuid(instanceId);
            for(auto v:selected){auto row=v.toObject();ON_UUID outputId;ON_CreateUuid(outputId);QJsonObject copy{{"namespace",ns},{"source_uuid",row["source_uuid"]},{"output_uuid",id(outputId)},{"host_id",id(outputId)},{"follow_canonical",true},{"member_matrix",QJsonArray{1,0,0,2,0,1,0,3,0,0,1,4,0,0,0,1}}};if(!canonical)copy["independent_overlay"]=QJsonObject{{"action","transform"},{"hatch_fields",row["hatch_fields"]}};copies.append(copy);members.append(id(outputId));}
            auto block=request;block["selected"]=canonical?selected:QJsonArray{};block["member_copies"]=copies;block["new_definitions"]=QJsonArray{QJsonObject{{"namespace",ns},{"source_uuid",id(definitionId)},{"host_id",id(definitionId)},{"name","Independent legacy typed loops"},{"member_uuids",members}}};block["new_instances"]=QJsonArray{QJsonObject{{"namespace",ns},{"source_uuid",id(instanceId)},{"host_id",id(instanceId)},{"role","top-level"},{"instance_definition_uuid",id(definitionId)},{"instance_matrix",QJsonArray{1,0,0,100,0,1,0,200,0,0,1,300,0,0,0,1}}}};writePreservedArchive(block,output);legacy(output,dir,QString(unit)+(canonical?" canonical typed copies in block":" independent typed copies in block"));
        }
    }require(cases==12,"twelve independent full loop archives");std::cout<<"legacy twelve loop archives with five child classes and block graphs PASS\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
