#include "ThreeDmArchive.h"
#include <BRepPrimAPI_MakeBox.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <fstream>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
void require(bool v,const char* msg){if(!v)throw std::runtime_error(msg);}
int main(){try{ON::Begin();auto root=std::filesystem::temp_directory_path()/"om9-3dm-native";std::filesystem::create_directories(root);
    ExchangeModel model;ExchangeItem item;item.name="Jewelry α";item.layer="Metal::Gold";item.color={255,120,12};item.visible=false;item.locked=true;item.geometry=BRepPrimAPI_MakeBox(10,10,10).Shape();model.items.push_back(item);writeArchive5(model,root/"box.3dm");auto result=readArchive(root/"box.3dm");require(result.items.size()==1,"count");require(result.items[0].name==item.name&&result.items[0].layer==item.layer,"unicode/layer names");require(result.items[0].color==item.color,"color");require(!result.items[0].visible,"visibility");require(result.items[0].locked,"lock metadata");
    std::ifstream f(root/"box.3dm",std::ios::binary);std::string header(32,'\0');f.read(header.data(),32);require(header.find("5")!=std::string::npos,"Rhino 5 header");
    std::cerr<<"metadata PASS\n";ONX_Model inch;ON_Layer defaultLayer;defaultLayer.SetName(L"Default");inch.AddModelComponent(defaultLayer);inch.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Inches);ON_LineCurve line(ON_3dPoint(0,0,0),ON_3dPoint(1,0,0));ON_3dmObjectAttributes a;inch.AddModelGeometryComponent(&line,&a);require(inch.Write((root/"inch.3dm").c_str(),5,nullptr),"fixture write");std::cerr<<"inch written\n";auto converted=readArchive(root/"inch.3dm");GProp_GProps length;BRepGProp::LinearProperties(std::get<TopoDS_Shape>(converted.items[0].geometry),length);require(std::abs(length.Mass()-25.4)<1e-7,"inch scale");
    inch.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::None);inch.Write((root/"unitless.3dm").c_str(),5,nullptr);bool rejected=false;try{readArchive(root/"unitless.3dm");}catch(const ExchangeError&){rejected=true;}require(rejected,"unitless must reject");require(readArchive(root/"unitless.3dm",2).scaleMm==2,"explicit units");
    std::ofstream(root/"bad.3dm",std::ios::binary)<<"bad";rejected=false;try{readArchive(root/"bad.3dm");}catch(const ExchangeError&){rejected=true;}require(rejected,"malformed input");
    ONX_Model nested;ON_Layer parent;parent.SetName(L"Parent");parent.SetVisible(false);parent.SetLocked(true);auto pr=nested.AddModelComponent(parent);ON_Layer child;child.SetName(L"Child");child.SetParentId(pr.ModelComponent()->Id());auto cr=nested.AddModelComponent(child);ON_3dmObjectAttributes ca;ca.m_layer_index=ON_Layer::Cast(cr.ModelComponent())->Index();nested.AddModelGeometryComponent(&line,&ca);require(nested.Write((root/"nested.3dm").c_str(),5,nullptr),"nested fixture");auto nr=readArchive(root/"nested.3dm");require(!nr.items[0].visible&&nr.items[0].locked,"ancestor layer states");
    ONX_Model annotation;annotation.AddModelComponent(defaultLayer);ON_TextDot dot(ON_3dPoint(0,0,0),L"Unsupported note",L"");annotation.AddModelGeometryComponent(&dot,&a);annotation.Write((root/"unsupported.3dm").c_str(),5,nullptr);rejected=false;try{readArchive(root/"unsupported.3dm");}catch(const ExchangeError&){rejected=true;}require(rejected,"unsupported annotation rejected");
    ONX_Model extrusionModel;extrusionModel.m_settings.m_ModelUnitsAndTolerances.m_absolute_tolerance=1e-7;extrusionModel.AddModelComponent(defaultLayer);ON_ArcCurve profile(ON_Circle(ON_xy_plane,4));std::unique_ptr<ON_Extrusion> extrusion(ON_Extrusion::CreateFrom3dCurve(profile,nullptr,10,true));require(bool(extrusion),"extrusion fixture");extrusionModel.AddModelGeometryComponent(extrusion.get(),&a);require(extrusionModel.Write((root/"extrusion.3dm").c_str(),5,nullptr),"extrusion archive");auto er=readArchive(root/"extrusion.3dm");GProp_GProps volume;BRepGProp::VolumeProperties(std::get<TopoDS_Shape>(er.items[0].geometry),volume,1e-10);std::cerr.precision(17);std::cerr<<"extrusion volume "<<volume.Mass()<<" expected "<<160*ON_PI<<"\n";require(std::abs(volume.Mass()-160*ON_PI)<1e-4,"extrusion solid volume");
    auto invalid=exportBrep(BRepPrimAPI_MakeBox(1,1,1).Shape(),1e-6);invalid->m_T[0].m_c2i=-1;rejected=false;try{importBrep(*invalid,1e-6);}catch(const ExchangeError&){rejected=true;}require(rejected,"invalid trim rejected");
    ExchangeModel signedModel;ExchangeItem signedItem;signedItem.name="Mirrored α";signedItem.layer="Metal::Gold";signedItem.color={12,78,160};signedItem.visible=false;signedItem.locked=true;signedItem.geometry=BRepPrimAPI_MakeBox(gp_Pnt(20,30,40),2,3,4).Shape().Reversed();signedModel.items.push_back(signedItem);auto inwardPath=root/"inward-document.3dm";writeArchive5(signedModel,inwardPath);
    ONX_Model signedArchive;require(signedArchive.Read(inwardPath.c_str()),"signed raw archive read");int reflectedRoots=0,inwardFlat=0;
    ONX_ModelComponentIterator signedObjects(signedArchive,ON_ModelComponent::Type::ModelGeometry);
    for(auto component=signedObjects.FirstComponent();component;component=signedObjects.NextComponent()){
        auto object=ON_ModelGeometryComponent::Cast(component);auto geometry=object->Geometry(nullptr);auto attrs=object->Attributes(nullptr);
        if(auto brep=ON_Brep::Cast(geometry))if(brep->SolidOrientation()==-1){if(!attrs->IsInstanceDefinitionObject())++inwardFlat;const_cast<ON_Brep*>(brep)->Flip();}
        if(auto instance=ON_InstanceRef::Cast(geometry))if(instance->m_xform.Determinant()<0)++reflectedRoots;
    }
    require(inwardFlat==0&&reflectedRoots==1,"Rhino document insertion must not normalize a flat inward placement");
    auto normalizedPath=root/"inward-document-normalized.3dm";require(writeModelRhino5(signedArchive,normalizedPath),"document normalization simulation write");auto signedResult=readArchive(normalizedPath);require(signedResult.items.size()==1,"signed placement count");const auto& received=signedResult.items[0];require(received.name==signedItem.name&&received.layer==signedItem.layer&&received.color==signedItem.color&&!received.visible&&received.locked,"signed placement metadata");
    GProp_GProps signedVolume;BRepGProp::VolumeProperties(std::get<TopoDS_Shape>(received.geometry),signedVolume,1e-10);require(std::abs(signedVolume.Mass()+24)<1e-7,"negative placement survives inward document normalization");
    // Mirroring the placement again makes it outward; its logical user label
    // must survive independently of the current transform determinant.
    for(auto component=signedObjects.FirstComponent();component;component=signedObjects.NextComponent()){
        auto object=ON_ModelGeometryComponent::Cast(component);if(auto instance=ON_InstanceRef::Cast(object->Geometry(nullptr))){auto editedInstance=const_cast<ON_InstanceRef*>(instance);editedInstance->m_xform=ON_Xform::IdentityTransformation;auto definition=ON_InstanceDefinition::Cast(signedArchive.ComponentFromId(ON_ModelComponent::Type::InstanceDefinition,instance->m_instance_definition_uuid).ModelComponent());require(definition,"generated definition lookup");editedInstance->m_bbox=definition->BoundingBox();auto attributes=const_cast<ON_3dmObjectAttributes*>(object->Attributes(nullptr));attributes->m_name=L"";attributes->SetMode(ON::normal_object);attributes->SetUserString(L"OpenMatrix9.Locked",L"0");}
    }
    auto editedPath=root/"signed-placement-mirrored-again.3dm";require(writeModelRhino5(signedArchive,editedPath),"edited signed placement write");auto edited=readArchive(editedPath);require(edited.items.size()==1&&edited.items[0].name.empty(),"edited signed placement retains empty logical label");require(!edited.items[0].locked,"placement unlock is not overridden by member metadata");BRepGProp::VolumeProperties(std::get<TopoDS_Shape>(edited.items[0].geometry),signedVolume,1e-10);require(std::abs(signedVolume.Mass()-24)<1e-7,"second reflection becomes outward");
    ONX_Model flatInward;flatInward.AddModelComponent(defaultLayer);ON_3dmObjectAttributes flatAttributes;auto flatBrep=exportBrep(std::get<TopoDS_Shape>(signedItem.geometry),1e-6);flatInward.AddModelGeometryComponent(flatBrep.get(),&flatAttributes);auto protectedPath=root/"inward-preservation-refused.3dm";std::ofstream(protectedPath,std::ios::binary)<<"unchanged target";rejected=false;try{writeModelRhino5(flatInward,protectedPath);}catch(const ExchangeError&){rejected=true;}require(rejected,"unsafe inward preservation export must refuse");std::ifstream protectedInput(protectedPath,std::ios::binary);require(std::string(std::istreambuf_iterator<char>(protectedInput),{})=="unchanged target","inward refusal protects target bytes");
    // Rhino normalizes inward definition members too, regardless of role flags.
    for(bool flagged:{false,true}){
        ONX_Model inwardMember;inwardMember.AddModelComponent(defaultLayer);auto attributes=flatAttributes;if(flagged)attributes.SetMode(ON::idef_object);
        auto member=inwardMember.AddModelGeometryComponent(flatBrep.get(),&attributes);ON_InstanceDefinition definition;definition.SetName(L"Inward member");definition.SetInstanceDefinitionType(ON_InstanceDefinition::IDEF_UPDATE_TYPE::Static);definition.AddInstanceGeometryId(member.ModelComponent()->Id());inwardMember.AddModelComponent(definition);
        std::ofstream(protectedPath,std::ios::binary)<<"unchanged target";rejected=false;try{writeModelRhino5(inwardMember,protectedPath);}catch(const ExchangeError& error){rejected=std::string(error.what()).find("inward")!=std::string::npos;}
        require(rejected,"unsafe inward definition member must refuse regardless of role flags");std::ifstream input(protectedPath,std::ios::binary);require(std::string(std::istreambuf_iterator<char>(input),{})=="unchanged target","inward member refusal protects target bytes");
    }
    ON_3dPoint corners[8]={ON_3dPoint(0,0,0),ON_3dPoint(2,0,0),ON_3dPoint(2,3,0),ON_3dPoint(0,3,0),ON_3dPoint(0,0,4),ON_3dPoint(2,0,4),ON_3dPoint(2,3,4),ON_3dPoint(0,3,4)};
    std::unique_ptr<ON_Brep> unknown(ON_BrepBox(corners));unknown->Flip();require(unknown->SolidOrientation()==2,"Unknown inward guard fixture");
    ONX_Model unknownInward;unknownInward.AddModelComponent(defaultLayer);auto unknownRef=unknownInward.AddModelGeometryComponent(unknown.get(),&flatAttributes);
    auto retained=ON_Brep::Cast(ON_ModelGeometryComponent::Cast(unknownRef.ModelComponent())->Geometry(nullptr));auto crc=retained->DataCRC(0);
    std::ofstream(protectedPath,std::ios::binary)<<"unchanged target";rejected=false;try{writeModelRhino5(unknownInward,protectedPath);}catch(const ExchangeError& error){rejected=std::string(error.what()).find("inward")!=std::string::npos;}
    require(rejected,"Unknown inward native solid must refuse unsafe Rhino5 preservation");std::ifstream unknownInput(protectedPath,std::ios::binary);require(std::string(std::istreambuf_iterator<char>(unknownInput),{})=="unchanged target","Unknown inward refusal protects target bytes");
    require(retained->SolidOrientation()==2&&retained->DataCRC(0)==crc,"Unknown direction guard cannot alter source payload or cache");
    // Disjoint shells now classify correctly, but inward V5 export must still
    // refuse the known legacy writer reversal. Mixed signs remain unresolved.
    ON_Brep disconnected(*unknown),distant(*unknown);require(distant.Transform(ON_Xform::TranslationTransformation(ON_3dVector(10,0,0))),"Distant solid transform");disconnected.Append(distant);
    require(disconnected.IsValid()&&disconnected.SolidOrientation()==2&&resolvedBrepOrientation(disconnected,1e-7)==-1,"Native-valid disjoint inward shells now classify correctly");
    ONX_Model unclassified;unclassified.AddModelComponent(defaultLayer);auto unresolvedRef=unclassified.AddModelGeometryComponent(&disconnected,&flatAttributes);
    auto unresolved=ON_Brep::Cast(ON_ModelGeometryComponent::Cast(unresolvedRef.ModelComponent())->Geometry(nullptr));auto unresolvedCrc=unresolved->DataCRC(0);
    char unknownUuid[37]{};ON_UuidToString(unresolvedRef.ModelComponent()->Id(),unknownUuid);
    rejected=false;try{writeModelRhino5(unclassified,protectedPath);}catch(const ExchangeError& error){rejected=std::string(error.what()).find("inward")!=std::string::npos;}
    require(rejected,"Classified multi-shell inward source refuses legacy V5 sign reversal");
    require(unresolved->IsValid()&&unresolved->SolidOrientation()==2&&unresolved->DataCRC(0)==unresolvedCrc,"Unresolved classification retains valid native source");
    distant.Flip();ON_Brep mixed(*unknown);mixed.Append(distant);require(mixed.IsValid()&&mixed.IsSolid(),"Mixed winding native closed shells");
    ONX_Model mixedModel;mixedModel.AddModelComponent(defaultLayer);auto mixedRef=mixedModel.AddModelGeometryComponent(&mixed,&flatAttributes);ON_UuidToString(mixedRef.ModelComponent()->Id(),unknownUuid);
    rejected=false;try{writeModelRhino5(mixedModel,protectedPath);}catch(const ExchangeError& error){auto message=std::string(error.what());rejected=message.find("resolve BRep solid orientation")!=std::string::npos&&message.find(unknownUuid)!=std::string::npos;}
    require(rejected,"Unresolved mixed winding reports classification and source UUID");std::ifstream finalProtectedInput(protectedPath,std::ios::binary);require(std::string(std::istreambuf_iterator<char>(finalProtectedInput),{})=="unchanged target","All sign guard refusals leave target unchanged");
    std::cout<<"OM9-FILE-012 archive PASS; fixtures "<<root<<'\n';return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
