#include "ThreeDmMerge.h"
#include "ThreeDmArchive.h"
#include <QFile>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool value,const char* message){if(!value)throw ExchangeError(message);}
static QString id(ON_UUID value){char text[37]{};ON_UuidToString(value,text);return QString::fromLatin1(text);}
static QByteArray bytes(const std::filesystem::path& path){QFile file(QString::fromStdWString(path.wstring()));require(file.open(QIODevice::ReadOnly),"read archive");return file.readAll();}
static void reject(QJsonObject request,const std::filesystem::path& path){auto before=bytes(path);bool failed=false;try{writePreservedArchive(request,path);}catch(const ExchangeError&){failed=true;}require(failed&&before==bytes(path),"invalid TextDot edit must reject atomically");}
static void run(ON::LengthUnitSystem units){
    ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);ON_Layer layer;layer.SetName(L"TextDot native");model.AddModelComponent(layer);
    ON_TextDot dot(ON_3dPoint(1.123456789012345,2,3),L"Original native",L"");dot.SetHeightInPoints(19);dot.SetBold(true);dot.SetItalic(true);dot.SetAlwaysOnTop(true);dot.SetTransparent(true);dot.SetUserString(L"Native note",L"Keep source userdata");
    ON_3dmObjectAttributes attributes;attributes.m_name=L"TextDot fields";attributes.SetUserString(L"Attribute note",L"Keep attributes");auto root=model.AddModelGeometryComponent(&dot,&attributes);attributes.SetMode(ON::idef_object);auto member=model.AddModelGeometryComponent(&dot,&attributes);
    ON_InstanceDefinition definition;definition.SetName(L"TextDot definition");definition.AddInstanceGeometryId(member.ModelComponent()->Id());auto target=model.AddModelComponent(definition);ON_InstanceRef instance;instance.m_instance_definition_uuid=target.ModelComponent()->Id();instance.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(10,20,30));attributes.SetMode(ON::normal_object);auto block=model.AddModelGeometryComponent(&instance,&attributes);
    auto path=std::filesystem::temp_directory_path()/(units==ON::LengthUnitSystem::Millimeters?"om9-native-text-dot-mm.3dm":"om9-native-text-dot-cm.3dm");require(model.Write(path.c_str(),5,nullptr),"write TextDot source");auto original=bytes(path);auto input=inspectArchive(path);
    QJsonObject source{{"namespace","12345678-1234-1234-1234-123456789abc"},{"snapshot",QString::fromStdWString(path.wstring())},{"archive_sha256",input.document["archive_sha256"]},{"scale_mm",input.document["scale_mm"]}};
    QJsonObject fields{{"point",QJsonArray{4.123456789012345,5,6}},{"primary_text",QString::fromUtf8("Duy \xE2\x99\xA5\nRhino 5")},{"secondary_text",""},{"font_face","Tahoma"},{"height_in_points",23},{"bold",false},{"italic",true},{"always_on_top",false},{"transparent",false}};
    QJsonArray matrix{0,-1,0,10,1,0,0,20,0,0,1,30,0,0,0,1};QJsonObject row{{"namespace",source["namespace"]},{"source_uuid",id(root.ModelComponent()->Id())},{"host_id","dot"},{"action","transform"},{"geometry_matrix",matrix},{"text_dot",fields}};
    QJsonObject request{{"schema_version",1},{"sources",QJsonArray{source}},{"selected",QJsonArray{row}}};auto output=path.parent_path()/"om9-native-text-dot-output.3dm";writePreservedArchive(request,output);
    auto verify=[&](ON_UUID uuid,ON_3dPoint expected){auto result=inspectArchive(output);auto component=ON_ModelGeometryComponent::Cast(result.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,uuid).ModelComponent());auto actual=component?ON_TextDot::Cast(component->Geometry(nullptr)):nullptr;require(actual&&actual->CenterPoint().DistanceTo(expected)<1e-12,"TextDot edited double anchor composed once");require(ON_wString(actual->PrimaryText())==ON_wString(fields["primary_text"].toString().toStdWString().c_str())&&ON_wString(actual->FontFace())==L"Tahoma"&&actual->HeightInPoints()==23&&!actual->Bold()&&actual->Italic()&&!actual->AlwaysOnTop()&&!actual->Transparent(),"TextDot primary text font height flags native roundtrip");ON_wString note;require(actual->GetUserString(L"Native note",note)&&note==L"Keep source userdata"&&component->Attributes(nullptr)->GetUserString(L"Attribute note",note)&&note==L"Keep attributes","TextDot independent native and attribute userdata retained");return result;};
    verify(root.ModelComponent()->Id(),ON_3dPoint(5,24.123456789012345,36));
    auto originalComponent=ON_ModelGeometryComponent::Cast(input.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,root.ModelComponent()->Id()).ModelComponent());auto expected=*ON_TextDot::Cast(originalComponent->Geometry(nullptr));double scale=input.document["scale_mm"].toDouble();if(scale!=1)transformNativeGeometry(expected,ON_Xform::DiagonalTransformation(scale));auto textOnly=nativeGeometryFacts(expected)["text_dot"].toObject();textOnly["primary_text"]="Only changed text";expected.SetPrimaryText(L"Only changed text");auto textOnlyRow=row;textOnlyRow["text_dot"]=textOnly;textOnlyRow["geometry_matrix"]=QJsonArray{1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};auto textOnlyRequest=request;textOnlyRequest["selected"]=QJsonArray{textOnlyRow};writePreservedArchive(textOnlyRequest,output);auto textOnlyResult=inspectArchive(output);auto textOnlyComponent=ON_ModelGeometryComponent::Cast(textOnlyResult.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,root.ModelComponent()->Id()).ModelComponent());require(textOnlyComponent&&textOnlyComponent->Geometry(nullptr)->DataCRC(0)==expected.DataCRC(0),"primary text edit retains implicit font representation and unrelated native fields");
    auto dependency=row;dependency["source_uuid"]=id(member.ModelComponent()->Id());dependency["host_id"]="member";auto selected=row;selected["source_uuid"]=id(block.ModelComponent()->Id());selected["host_id"]="block";selected["action"]="unchanged";selected.remove("text_dot");selected.remove("geometry_matrix");request["selected"]=QJsonArray{selected};request["dependency_overlays"]=QJsonArray{dependency};writePreservedArchive(request,output);auto editedMember=verify(member.ModelComponent()->Id(),ON_3dPoint(5,24.123456789012345,36));require(editedMember.document["records"].toArray().size()==2,"TextDot member exact selected closure");
    ON_UUID ownId;ON_CreateUuid(ownId);QJsonObject copy{{"namespace",source["namespace"]},{"source_uuid",id(member.ModelComponent()->Id())},{"output_uuid",id(ownId)},{"host_id","own-member"},{"role","top-level"},{"member_matrix",matrix},{"independent_overlay",QJsonObject{{"action","transform"},{"text_dot",fields}}}};auto copyRoot=selected;copyRoot["source_uuid"]=id(ownId);request.remove("dependency_overlays");request["member_copies"]=QJsonArray{copy};request["selected"]=QJsonArray{copyRoot};writePreservedArchive(request,output);auto independent=verify(ownId,ON_3dPoint(5,24.123456789012345,36));require(independent.document["records"].toArray().size()==1&&independent.nativeModel->ActiveComponentCount(ON_ModelComponent::Type::InstanceDefinition)==0,"independent TextDot copy omits original definition");
    request.remove("member_copies");request["selected"]=QJsonArray{row};for(auto key:{"point","primary_text","font_face","height_in_points","bold","secondary_text","unknown"}){auto bad=fields;if(QString(key)=="point")bad[key]=QJsonArray{1,2,"bad"};else if(QString(key)=="height_in_points")bad[key]=2;else if(QString(key)=="bold")bad[key]=1;else if(QString(key)=="secondary_text")bad[key]="Newer-only text";else if(QString(key)=="primary_text")bad[key]=" Silently trimmed ";else bad[key]=QJsonObject{};auto edit=row;edit["text_dot"]=bad;auto invalid=request;invalid["selected"]=QJsonArray{edit};reject(invalid,output);}
    auto wrong=row;wrong["source_uuid"]=id(block.ModelComponent()->Id());request["selected"]=QJsonArray{wrong};reject(request,output);require(bytes(path)==original,"TextDot source stays immutable");
}
int main(){try{ON::Begin();run(ON::LengthUnitSystem::Millimeters);run(ON::LengthUnitSystem::Centimeters);std::cout<<"Native TextDot fields mm/cm, member/copy, Unicode, exact setters, userdata and atomic guards passed\n";return 0;}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
