#include "ThreeDmInventory.h"
#include "ThreeDmNativeReferences.h"
#include "ThreeDmCurveOnSurface.h"
#include "ThreeDmArchive.h"
#include "opennurbs_polyedgecurve.h"
#include <QFile>
#include <QDir>
#include <QFileInfo>
#include <QTemporaryDir>
#include <QCryptographicHash>
#include <QJsonDocument>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static int checks=0;
static void require(bool v,const char* text){++checks;if(!v)throw ExchangeError(text);}
static QJsonObject readJson(QString path){QFile f(path);require(f.open(QIODevice::ReadOnly),"Read independent frozen oracle/report");return QJsonDocument::fromJson(f.readAll()).object();}
static QString sha(QString path){QFile f(path);require(f.open(QIODevice::ReadOnly),"Open source/saved bytes");return QString::fromLatin1(QCryptographicHash::hash(f.readAll(),QCryptographicHash::Sha256).toHex());}
static QJsonObject record(const ArchiveInventory& inv,const QString& uuid){for(auto v:inv.document["records"].toArray())if(v.toObject()["source_uuid"]==uuid)return v.toObject();throw ExchangeError("Missing root UUID");}
int main(){try{ON::Begin();QDir root(QStringLiteral(OM9_STANDALONE_FROZEN));auto oracle=readJson(root.filePath("oracle.json"));auto actual=readJson(root.filePath("rhino5-gui-profile-results.json"));
    require(!actual["ok"].toBool()&&oracle["cases"].toArray().size()==12&&actual["cases"].toArray().size()==12,"Actual target failure has all12 cases, not a probe abort");
    require(sha(root.filePath("oracle.json"))==actual["oracle_sha256"],"Actual target report binds exact independent oracle");
    auto cases=oracle["cases"].toArray(),targetCases=actual["cases"].toArray();QJsonArray evidence,decoded;
    for(int i=0;i<cases.size();++i){auto wanted=cases[i].toObject(),measured=targetCases[i].toObject();auto uuid=wanted["objects"].toArray()[1].toObject()["uuid"].toString();auto saved=root.filePath(QFileInfo(measured["saved_fixture"].toString()).fileName());ONX_Model model;require(model.Read(std::filesystem::path(saved.toStdWString()).c_str(),nullptr),"Decode actual target SaveAs model");auto component=ON_ModelGeometryComponent::Cast(model.ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(uuid.toLatin1().constData())).ModelComponent());auto curve=component?ON_Curve::Cast(component->Geometry(nullptr)):nullptr;require(curve,"Saved native reference identity exists");QJsonObject row{{"fixture",wanted["fixture"]},{"source_class",wanted["root_class"]},{"saved_class",curve->ClassId()->ClassName()},{"saved_dimension",curve->Dimension()},{"saved_valid",curve->IsValid()}};try{row["saved_fields"]=nativeCurveTreeFields(*curve);}catch(const ExchangeError& e){row["field_error"]=e.what();}decoded.append(row);}
    QFile decodedFile(QStringLiteral(OM9_STANDALONE_RESULTS)+".decoded.json");require(decodedFile.open(QIODevice::WriteOnly),"Write decoded target evidence");decodedFile.write(QJsonDocument(QJsonObject{{"cases",decoded}}).toJson());decodedFile.close();
    for(int i=0;i<cases.size();++i){auto wanted=cases[i].toObject(),measured=targetCases[i].toObject();auto uuid=wanted["objects"].toArray()[1].toObject()["uuid"].toString(),owner=wanted["objects"].toArray()[0].toObject()["uuid"].toString();
        require(wanted["fixture"]==measured["fixture"]&&sha(root.filePath(wanted["fixture"].toString()))==wanted["source_sha256"]&&wanted["source_sha256"]==measured["source_sha256"],"Source byte binding");
        auto saved=root.filePath(QFileInfo(measured["saved_fixture"].toString()).fileName());require(sha(saved)==measured["saved_sha256"],"Actual Rhino SaveAs byte binding");
        for(auto phase:{"first_read","reread"}){auto measurement=measured[phase].toObject();require(!measurement["passed"].toBool()&&measured["bad_objects"].toInt()==1,"Actual Rhino rejects reference root in both document reads");bool invalid=false,ownerGood=false;
            for(auto v:measurement["objects"].toArray()){auto obj=v.toObject();if(obj["uuid"]==uuid){invalid=!obj["valid"].toBool()&&obj["samples"].toArray().size()==17;for(auto sample:obj["samples"].toArray())for(auto coord:sample.toArray())invalid=invalid&&coord.toDouble()==ON_UNSET_VALUE;for(auto valid:obj["sample_validity"].toArray())invalid=invalid&&!valid.toBool();}if(obj["uuid"]==owner)ownerGood=obj["valid"].toBool();}
            require(invalid&&ownerGood,"UnsetPoint reference root with valid independent owner is captured, not a threshold discrepancy");}
        QJsonObject sourceFields;
        for(auto file:{root.filePath(wanted["fixture"].toString()),saved}){const bool original=file!=saved;auto inv=inspectArchive(std::filesystem::path(file.toStdWString()));auto row=record(inv,uuid);require(row["class_name"]==(original?wanted["root_class"]:QJsonValue("ON_PolyEdgeSegment")),"Actual target keeps segment class but flattens single-segment PolyEdgeCurve");
            auto native=ON_ModelGeometryComponent::Cast(inv.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(uuid.toLatin1().constData())).ModelComponent());auto source=ON_Curve::Cast(native->Geometry(nullptr));auto fields=nativeCurveTreeFields(*source);
            auto expectedFields=wanted["native_reference_fields"].toObject();if(!original&&wanted["root_class"]=="ON_PolyEdgeCurve"){auto outer=expectedFields;expectedFields=outer["segments"].toArray()[0].toObject();expectedFields["object_references"]=outer["object_references"];expectedFields["user_strings"]=outer["user_strings"];expectedFields["userdata"]=outer["userdata"];}
            const bool sourceReversed=expectedFields.value("reversed").toBool();if(!original)expectedFields["reversed"]=false;
            require(fields==expectedFields,"Decode actual target class flattening and reversal loss; all other reference fields exact");
            require(row["poly_edge_native"].toObject()==fields&&row["dependencies"].toArray().contains(owner)&&row["capability"]=="retained","Standalone typed inventory and owner closure; no generic editable claim");
            require(row["native_reference_analysis"].toObject()["status"]=="linked"&&inv.document["issues"].toArray().isEmpty(),"Standalone native resolver links owner without mutating archive");
            auto graph=inv.nativeReferences->graphs.at(uuid);auto curve=ON_Curve::Cast(graph->geometry.at(uuid).get());require(curve&&curve->IsValid()&&curve->ClassId()==source->ClassId(),"Exact resolved native class is valid");
            const auto crc=source->DataCRC(0);auto points=wanted["objects"].toArray()[1].toObject()["samples"].toArray();for(int j=0;j<17;++j){auto p=points[!original&&sourceReversed?16-j:j].toArray();require(curve->PointAt(31+j).DistanceTo(ON_3dPoint(p[0].toDouble(),p[1].toDouble(),p[2].toDouble()))<=1e-12,"Independent17-point native mapping; saved reversed cases explicitly follow observed reversal loss, not original-shape equivalence");}
            require(source->DataCRC(0)==crc&&source->Dimension()==0,"Immutable source proxy remains deferred and unchanged");
            QFile protectedFile(root.filePath("../../../build/standalone-protected.3dm"));auto protectedPath=std::filesystem::path(protectedFile.fileName().toStdWString());require(protectedFile.open(QIODevice::WriteOnly),"Create protected test target");protectedFile.write("keep-target");protectedFile.close();bool refused=false;try{writeModelRhino5(*inv.nativeModel,protectedPath);}catch(const ExchangeError& e){refused=std::string(e.what()).find("standalone PolyEdge")!=std::string::npos;}require(refused,"Direct public writer refuses actual Rhino5 standalone PolyEdge target failure");require(protectedFile.open(QIODevice::ReadOnly)&&protectedFile.readAll()=="keep-target","Target refusal is atomic");protectedFile.close();
            auto prepared=readArchive(std::filesystem::path(file.toStdWString()),1,true);bool retained=false;for(auto& item:prepared.items)if(item.sourceUuid==uuid.toStdString())retained=item.retained;require(retained,"Public preservation reader retains root and valid owner instead of aborting on deferred proxy");
            inv=ArchiveInventory{};require(curve->PointAt(39).IsValid()&&graph->source,"Graph owns borrowed target lifetime after inventory release");
        }
        evidence.append(QJsonObject{{"fixture",wanted["fixture"]},{"root_uuid",uuid},{"native_linked",true},{"rhino5_reference_invalid",true},{"saved_class_changed",wanted["root_class"]=="ON_PolyEdgeCurve"},{"saved_reversal_lost",wanted["fixture"].toString().contains("reversed-1")},{"other_reference_fields_exact",true}});
    }
    QTemporaryDir invalidFolder;require(invalidFolder.isValid(),"Owned invalid-reference fixture folder");
    for(int rootIndex:{0,6})for(int kind=0;kind<3;++kind){auto wanted=cases[rootIndex].toObject();auto uuid=wanted["objects"].toArray()[1].toObject()["uuid"].toString();ONX_Model model;require(model.Read(std::filesystem::path(root.filePath(wanted["fixture"].toString()).toStdWString()).c_str(),nullptr),"Read independent source for malformed owner fixture");auto component=ON_ModelGeometryComponent::Cast(model.ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(uuid.toLatin1().constData())).ModelComponent());auto curve=const_cast<ON_Curve*>(ON_Curve::Cast(component->Geometry(nullptr)));auto poly=ON_PolyEdgeCurve::Cast(curve);auto segment=poly?poly->SegmentCurve(0):ON_PolyEdgeSegment::Cast(curve);require(segment,"Standalone reference segment exists");segment->m_object_id=kind==0?ON_nil_uuid:kind==1?ON_UuidFromString("00000000-0000-4000-8000-000000002901"):component->Id();
        auto path=std::filesystem::path(invalidFolder.filePath(QString("invalid-%1-%2.3dm").arg(rootIndex).arg(kind)).toStdWString());require(model.Write(path.c_str(),5,nullptr),"Write invalid logical owner without target admission");auto inv=inspectArchive(path);auto row=record(inv,uuid);require(row["native_reference_analysis"].toObject()["status"]=="invalid"&&!inv.nativeReferences->graphs.contains(uuid)&&!inv.document["issues"].toArray().isEmpty(),"Nil/missing/cyclic standalone owner must be invalid before host mutation");}
    auto bounded=inspectArchive(std::filesystem::path(root.filePath(cases[0].toObject()["fixture"].toString()).toStdWString()));NativeReferenceLimits limits;limits.nodes=0;auto limited=resolveNativeReferences(bounded.nativeModel,bounded.document["records"].toArray(),limits);auto uuid=cases[0].toObject()["objects"].toArray()[1].toObject()["uuid"].toString();require(limited->diagnostics[uuid].toObject()["status"]=="limit"&&limited->graphs.empty(),"Standalone uses aggregate graph budget and never exposes partial graph");
    QFile result(QStringLiteral(OM9_STANDALONE_RESULTS));require(result.open(QIODevice::WriteOnly),"Write standalone native evidence");result.write(QJsonDocument(QJsonObject{{"ok",true},{"checks",checks},{"cases",evidence},{"malformed_owner_controls",6},{"aggregate_limit_controls",1},{"full_exchange_complete",false}}).toJson());std::cout<<"Standalone native reference/target guard PASS "<<checks<<" checks\n";return 0;
}catch(const std::exception& e){std::cerr<<"Standalone reference failure: "<<e.what()<<'\n';return 1;}}
