#include "ThreeDmArchive.h"
#include "ThreeDmInventory.h"
#include "ThreeDmPointCloud.h"
#include <QFile>
#include <QJsonArray>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool value,const char* message){if(!value)throw ExchangeError(message);}
static const ON_PointCloud* cloudOf(const ExchangeItem& item){return std::visit([](const auto& geometry)->const ON_PointCloud*{if constexpr(std::is_same_v<std::decay_t<decltype(geometry)>,ON_PointCloud>)return &geometry;else return nullptr;},item.geometry);}
static QByteArray bytes(const std::filesystem::path& path){QFile file(QString::fromStdWString(path.wstring()));require(file.open(QIODevice::ReadOnly),"fixture bytes");return file.readAll();}
int main(){try{ON::Begin();
    for(auto units:{ON::LengthUnitSystem::Millimeters,ON::LengthUnitSystem::Centimeters}){
        ON_PointCloud cloud;cloud.m_P.Append(ON_3dPoint(1.123456789012345,2,3));cloud.m_P.Append(ON_3dPoint(4,5.234567890123456,6));cloud.m_N.Append(ON_3dVector(2,1,0));cloud.m_N.Append(ON_3dVector());ON_Color color(17,31,47);color.SetAlpha(53);cloud.m_C.Append(color);cloud.m_C.Append(ON_Color(101,151,201));cloud.SetPlane(ON_Plane(ON_3dPoint(10,20,30),ON_3dVector(0,0,1)));cloud.SetOrdered(true);cloud.SetUserString(L"Source only",L"Geometry-only omits userdata");
        ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);ON_Layer layer;layer.SetName(L"Cloud geometry");model.AddModelComponent(layer);ON_3dmObjectAttributes attributes;attributes.SetMode(ON::idef_object);attributes.m_name=L"Cloud";auto member=model.AddModelGeometryComponent(&cloud,&attributes);
        ON_Point point(7,8,9);auto vertex=model.AddModelGeometryComponent(&point,&attributes);ON_Mesh mesh;mesh.SetVertex(0,ON_3dPoint(0,0,0));mesh.SetVertex(1,ON_3dPoint(1,0,0));mesh.SetVertex(2,ON_3dPoint(0,1,0));mesh.SetTriangle(0,0,1,2);auto triangle=model.AddModelGeometryComponent(&mesh,&attributes);
        ON_InstanceDefinition inner;inner.SetName(L"Inner cloud");inner.AddInstanceGeometryId(member.ModelComponent()->Id());inner.AddInstanceGeometryId(vertex.ModelComponent()->Id());inner.AddInstanceGeometryId(triangle.ModelComponent()->Id());auto innerRef=model.AddModelComponent(inner);
        ON_InstanceRef nested;nested.m_instance_definition_uuid=innerRef.ModelComponent()->Id();nested.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(10,20,30));auto nestedRef=model.AddModelGeometryComponent(&nested,&attributes);ON_InstanceDefinition outer;outer.SetName(L"Outer cloud");outer.AddInstanceGeometryId(nestedRef.ModelComponent()->Id());auto outerRef=model.AddModelComponent(outer);
        ON_InstanceRef root;root.m_instance_definition_uuid=outerRef.ModelComponent()->Id();root.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(100,200,300));root.m_xform[0][0]=-2;root.m_xform[0][1]=0.5;root.m_xform[1][1]=3;root.m_xform[2][2]=4;attributes.SetMode(ON::normal_object);attributes.m_name=L"Affine cloud";auto rootRef=model.AddModelGeometryComponent(&root,&attributes);attributes.m_name=L"Intensity";cloud.m_V.Append(0.123456789012345);cloud.m_V.Append(-4.234567890123456);model.AddModelGeometryComponent(&cloud,&attributes);
        auto path=std::filesystem::temp_directory_path()/(units==ON::LengthUnitSystem::Millimeters?"om9-cloud-geometry-mm.3dm":"om9-cloud-geometry-cm.3dm");require(model.Write(path.c_str(),5,nullptr),"geometry cloud fixture write");auto original=bytes(path);char id[37]{};ON_UuidToString(rootRef.ModelComponent()->Id(),id);auto result=readArchive(path,0,false,false,id);require(result.items.size()==3,"cloud CAD and mesh expand nested affine exactly once");auto transformed=cloudOf(result.items[0]);require(transformed,"geometry-only retains typed native cloud");auto expected=cloud;expected.m_V.Empty();transformNativeGeometry(expected,root.m_xform*nested.m_xform);const double scale=units==ON::LengthUnitSystem::Centimeters?10:1;if(scale!=1)transformNativeGeometry(expected,ON_Xform(scale));require(pointCloudFields(*transformed)==pointCloudFields(expected),"all current fields normalize native affine then mm without float conversion");require(std::holds_alternative<TopoDS_Shape>(result.items[1].geometry)&&std::holds_alternative<MeshData>(result.items[2].geometry),"mixed native geometry types");
        require(transformed->m_P[0].DistanceTo(ON_3dPoint(88.75308642197531*scale,266*scale,432*scale))<1e-10,"independent analytical double point affine composition");require((transformed->m_N[0]-ON_3dVector(-2,1,0)).Length()<1e-12&&transformed->m_N[1]==ON_3dVector(),"independent analytical inverse-transpose nonprincipal normal and zero");require(transformed->m_plane.origin.DistanceTo(ON_3dPoint(80*scale,320*scale,540*scale))<1e-10,"independent analytical plane origin composition");
        auto output=path.parent_path()/"om9-cloud-geometry-output.3dm";writeArchive5(result,output);auto reread=readArchive(output);require(reread.items.size()==3&&pointCloudFields(*cloudOf(reread.items[0]))==pointCloudFields(expected),"geometry-only exact cloud roundtrip");auto inventory=inspectArchive(output);require(inventory.document["source_version"]==50&&inventory.document["scale_mm"]==1,"geometry-only output is Rhino5 mm");for(auto record:inventory.document["records"].toArray()){auto row=record.toObject();require(row["class_name"]!="ON_InstanceRef"&&row["user_strings"].toArray().isEmpty()&&row["userdata"].toArray().isEmpty()&&row["attribute_user_strings"].toArray().isEmpty(),"geometry-only flattens definitions and strips native userdata");}
        auto all=readArchive(path);auto sentinel=bytes(output);bool rejected=false;try{writeArchive5(all,output);}catch(const ExchangeError& error){rejected=std::string(error.what()).find("intensity")!=std::string::npos;}require(rejected&&bytes(output)==sentinel,"Rhino5 intensity loss rejected before touching destination");require(bytes(path)==original,"geometry fixture immutable");
        std::cout<<(scale==1?"mm":"cm")<<": cloud mixed nested affine native doubles and intensity atomic gate PASS\n";
    }return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
