#include "ThreeDmArchive.h"
#include "ThreeDmInventory.h"
#include "ThreeDmMerge.h"
#include "ThreeDmHatch.h"
#include "opennurbs_polyedgecurve.h"
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QTemporaryDir>
#include <memory>
#include <vector>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
class LoopPluginData : public ON_UserData {
    ON_OBJECT_DECLARE(LoopPluginData);
public:
    LoopPluginData(){m_userdata_uuid=ON_CLASS_ID(LoopPluginData);m_application_uuid=ON_UuidFromString("15d1b5b7-1e47-4a96-bd6a-1e851d68b080");m_userdata_copycount=1;}
    bool Archive()const override{return true;}
    bool Write(ON_BinaryArchive& a)const override{return a.WriteInt(42);}
    bool Read(ON_BinaryArchive& a)override{int n=0;return a.ReadInt(&n)&&n==42;}
    bool GetDescription(ON_wString& s)override{s=L"Nested plugin data proof";return true;}
};
ON_OBJECT_IMPLEMENT(LoopPluginData,ON_UserData,"299fd0e1-ec04-4dc9-8e6a-36d246554f79");
static void require(bool ok,const char* message){if(!ok)throw ExchangeError(message);}
static QString id(ON_UUID value){char text[37]{};ON_UuidToString(value,text);return QString::fromLatin1(text);}
static QByteArray bytes(const std::filesystem::path& p){QFile f(QString::fromStdWString(p.wstring()));require(f.open(QIODevice::ReadOnly),"loop file read");return f.readAll();}
static void save(const std::filesystem::path& p,const QByteArray& data){QFile f(QString::fromStdWString(p.wstring()));require(f.open(QIODevice::WriteOnly|QIODevice::Truncate)&&f.write(data)==data.size(),"owned loop fixture/evidence write");}
static ON_Hatch makeHatch(const ON_Curve& curve,int pattern){ON_SimpleArray<const ON_Curve*> loops;loops.Append(&curve);ON_Hatch h;require(h.Create(ON_xy_plane,loops,pattern,0.123,2),"native loop fixture");h.SetBasePoint(ON_2dPoint(1.25,2.5));return h;}
static ON_NurbsCurve circle(){ON_NurbsCurve n;require(ON_Circle(ON_xy_plane,5).GetNurbForm(n),"loop NURBS circle");n.ChangeDimension(2);return n;}
static ON_PolylineCurve polyline(){ON_Polyline points;for(auto p:{ON_3dPoint(-5,-5,0),ON_3dPoint(5,-5,0),ON_3dPoint(5,5,0),ON_3dPoint(-5,5,0),ON_3dPoint(-5,-5,0)})points.Append(p);ON_PolylineCurve c(points);c.ChangeDimension(2);return c;}
static std::unique_ptr<ON_PolyCurve> mixed(){auto owned=std::make_unique<ON_PolyCurve>();auto& c=*owned;
    auto line=new ON_LineCurve(ON_3dPoint(-5,-5,0),ON_3dPoint(5,-5,0));line->ChangeDimension(2);line->SetDomain(2,7);line->SetUserString(L"Child",L"Original native line");require(c.Append(line),"append native line");
    auto n=new ON_NurbsCurve(2,false,2,2);n->SetCV(0,ON_3dPoint(5,-5,0));n->SetCV(1,ON_3dPoint(5,5,0));n->SetKnot(0,11);n->SetKnot(1,13);n->SetUserString(L"Child",L"Original native NURBS");require(c.Append(n),"append native NURBS");
    auto nested=new ON_PolyCurve;auto top=new ON_LineCurve(ON_3dPoint(5,5,0),ON_3dPoint(-5,5,0));top->ChangeDimension(2);require(nested->Append(top),"nested line");ON_Polyline left;left.Append(ON_3dPoint(-5,5,0));left.Append(ON_3dPoint(-5,-5,0));auto side=new ON_PolylineCurve(left);side->ChangeDimension(2);side->SetUserString(L"Child",L"Original native polyline");require(nested->Append(side)&&c.Append(nested),"nested native polycurve");
    double t[]{101,111,151,211};require(c.SetParameterization(t)&&c.IsValid()&&c.IsClosed(),"polycurve independent segment domains");return owned;
}
static const ON_Hatch* native(const ArchiveInventory& a,ON_UUID v){auto c=ON_ModelGeometryComponent::Cast(a.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,v).ModelComponent());return c?ON_Hatch::Cast(c->Geometry(nullptr)):nullptr;}
int main(){try{ON::Begin();ONX_Model model;ON_HatchPattern pattern;pattern.SetName(L"Loop audit solid");auto p=model.AddModelComponent(pattern);
    auto n=circle();require(n.AttachUserData(new LoopPluginData),"attach nested plugin data");auto h=makeHatch(n,p.ModelComponent()->Index());auto ordinary=makeHatch(circle(),p.ModelComponent()->Index());auto fields=hatchCurrentFields(ordinary,model);bool rejected=false;try{applyHatchFields(h,fields,model);}catch(const ExchangeError& e){rejected=std::string(e.what()).find("loop")!=std::string::npos;}require(rejected,"nested loop plugin userdata must reject scalar editing before data loss");
    rejected=false;try{hatchCurrentFields(h,model);}catch(const ExchangeError&){rejected=true;}require(rejected,"nested loop plugin userdata cannot advertise safe current fields");
    auto inactive=ordinary;inactive.SetGradientType(ON_GradientType::None);require(inactive.GetUserData(ON_UuidFromString("0c1ad613-4efa-4f47-a147-4d79d77fcb0c")),"inactive gradient data exists");rejected=false;try{hatchCurrentFields(inactive,model);}catch(const ExchangeError& e){rejected=std::string(e.what()).find("gradient")!=std::string::npos;}require(rejected,"inactive native gradient userdata cannot advertise Rhino5 fields");
    QTemporaryDir temp;require(temp.isValid(),"loop temporary dir");auto dir=std::filesystem::path(temp.path().toStdWString());int cases=0;
    for(auto unit:{ON::LengthUnitSystem::Millimeters,ON::LengthUnitSystem::Centimeters}){
        auto unitName=unit==ON::LengthUnitSystem::Millimeters?"mm":"cm";
        ONX_Model source;source.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(unit);ON_Layer layer;layer.SetName(L"Loop types");source.AddModelComponent(layer);ON_DimStyle style;style.SetName(L"Explicit loop style");auto d=source.AddModelComponent(style);source.m_settings.SetCurrentDimensionStyleId(d.ModelComponent()->Id());ON_HatchPattern solid(ON_HatchPattern::Solid);solid.ClearIndex();auto pattern=source.AddModelComponent(solid);
        std::vector<std::unique_ptr<ON_Curve>> curves;curves.push_back(std::make_unique<ON_NurbsCurve>(circle()));auto arc=std::make_unique<ON_ArcCurve>(ON_Circle(ON_xy_plane,5),11,23);arc->ChangeDimension(2);curves.push_back(std::move(arc));curves.push_back(std::make_unique<ON_PolylineCurve>(polyline()));curves.push_back(mixed());
        require(!pattern.IsEmpty(),"native loop pattern registration");QJsonArray selected;std::vector<ON_UUID> ids;
        for(auto& c:curves){c->SetUserString(L"Loop",L"Native curve metadata");auto value=makeHatch(*c,pattern.ModelComponent()->Index());ON_3dmObjectAttributes a;a.m_name=L"Native loop";auto g=source.AddModelGeometryComponent(&value,&a);require(!g.IsEmpty(),"native loop model registration");ids.push_back(g.ModelComponent()->Id());selected.append(QJsonObject{{"namespace","00000000-0000-4000-8000-000000000132"},{"source_uuid",id(ids.back())},{"host_id",QString::number(ids.size())},{"action","unchanged"}});require(hatchLoopInventory(value)[0].toObject()["curve"].toObject()["class_name"]==c->ClassId()->ClassName(),"inventory preserves exact loop class");}
        auto path=dir/(unit==ON::LengthUnitSystem::Millimeters?"types-mm.3dm":"types-cm.3dm");require(source.Write(path.c_str(),5,nullptr),"native loop source write");auto immutable=bytes(path);auto inv=inspectArchive(path);QJsonObject request{{"schema_version",1},{"sources",QJsonArray{QJsonObject{{"namespace","00000000-0000-4000-8000-000000000132"},{"snapshot",QString::fromStdWString(path.wstring())},{"archive_sha256",inv.document["archive_sha256"]},{"scale_mm",inv.document["scale_mm"]}}}},{"selected",selected}};auto output=dir/"types-output.3dm";writePreservedArchive(request,output);auto checked=inspectArchive(output);
        for(auto v:ids){require(native(inv,v)&&native(checked,v),"source/output exact hatch identity exists");auto before=*native(inv,v);auto scale=inv.document["scale_mm"].toDouble();if(scale!=1)transformHatchNative(before,ON_Xform::DiagonalTransformation(scale),inv.nativeModel.get());auto want=hatchLoopInventory(before),actual=hatchLoopInventory(*native(checked,v));if(want!=actual)std::cerr<<QJsonDocument(want).toJson(QJsonDocument::Compact).constData()<<"\n"<<QJsonDocument(actual).toJson(QJsonDocument::Compact).constData()<<'\n';require(want==actual,"exact native subtype/domain/CV/weight/knot/parameters/child strings survive mm/cm output");++cases;}
        auto bad=mixed();require(bad->SegmentCurve(2)->AttachUserData(new LoopPluginData),"nested parent data attach");auto unsafe=makeHatch(*bad,pattern.ModelComponent()->Index());auto unsafeId=source.AddModelGeometryComponent(&unsafe,nullptr).ModelComponent()->Id();auto unsafePath=dir/"unsafe.3dm";require(source.Write(unsafePath.c_str(),5,nullptr),"opaque loop retained v5 source");auto unsafeInventory=inspectArchive(unsafePath);bool unavailable=false;for(auto row:unsafeInventory.document["records"].toArray())if(row.toObject()["source_uuid"]==id(unsafeId))unavailable=row.toObject().contains("hatch_current_unavailable")&&row.toObject().contains("hatch_loop_native");require(unavailable,"nested unknown loop remains inventoried with unsafe current adapter unavailable");
        auto sentinel=bytes(output);request["sources"]=QJsonArray{QJsonObject{{"namespace","00000000-0000-4000-8000-000000000132"},{"snapshot",QString::fromStdWString(unsafePath.wstring())},{"archive_sha256",unsafeInventory.document["archive_sha256"]},{"scale_mm",unsafeInventory.document["scale_mm"]}}};request["selected"]=QJsonArray{QJsonObject{{"namespace","00000000-0000-4000-8000-000000000132"},{"source_uuid",id(unsafeId)},{"host_id","unsafe"},{"action","unchanged"}}};rejected=false;try{writePreservedArchive(request,output);}catch(const ExchangeError& e){std::cout<<"unsafe preflight: "<<e.what()<<std::endl;rejected=std::string(e.what()).find("loop")!=std::string::npos;}require(rejected&&bytes(output)==sentinel,"unchanged nested plugin loop export rejects atomically");require(bytes(path)==immutable,"loop inputs immutable");
        save(std::filesystem::temp_directory_path()/(std::string("om9-hatch-loops-")+unitName+".3dm"),immutable);save(std::filesystem::temp_directory_path()/(std::string("om9-hatch-loops-unsafe-")+unitName+".3dm"),bytes(unsafePath));
        save(std::filesystem::temp_directory_path()/(std::string("om9-hatch-loops-proof-")+unitName+".json"),QJsonDocument(QJsonObject{{"source",inv.document},{"output",checked.document},{"unsafe_source",unsafeInventory.document},{"atomic_rejection",true}}).toJson());
    }
    auto refs=mixed();refs->SegmentCurve(2)->SetUserString(L"Target",L"00000000-0000-4000-8000-000000000132");auto refHatch=makeHatch(*refs,p.ModelComponent()->Index());rejected=false;try{hatchCurrentFields(refHatch,model);}catch(const ExchangeError&){rejected=true;}require(rejected,"unresolved child user text references cannot silently leave closure");
    auto safe=mixed();auto parent=makeHatch(*safe,p.ModelComponent()->Index());auto before=hatchLoopInventory(parent);applyHatchFields(parent,fields,model);require(before==hatchLoopInventory(parent),"scalar fields preserve child types and metadata exactly");
    std::unique_ptr<ON_Curve> deep=std::make_unique<ON_NurbsCurve>(circle());for(int i=0;i<64;++i){auto wrapper=std::make_unique<ON_PolyCurve>();require(wrapper->Append(deep.get()),"owned nested budget fixture");deep.release();deep=std::move(wrapper);}ON_Hatch bounded;bounded.SetPlane(ON_xy_plane);bounded.SetPatternIndex(p.ModelComponent()->Index());bounded.AddLoop(new ON_HatchLoop(deep.release(),ON_HatchLoop::ltOuter));rejected=false;try{hatchLoopInventory(bounded);}catch(const ExchangeError& e){rejected=std::string(e.what()).find("limit")!=std::string::npos;}require(rejected,"valid native tree exceeding64 inventory levels rejects explicitly");
    ON_CurveProxy proxy;auto proxySource=circle();proxy.SetProxyCurve(&proxySource);ON_Write3dmBufferArchive stream(0,1024*1024,50,ON::Version());require(!proxy.Write(stream),"standalone CurveProxy SDK serialization is unavailable");
    auto referenceId=ON_UuidFromString("00000000-0000-4000-8000-000000000132");auto edge=new ON_PolyEdgeCurve;require(edge->Create(&proxySource,referenceId),"PolyEdge fixture points to native source");require(edge->SegmentCurve(0)->Dimension()==2,"reference curve retains source dimension");ON_Write3dmBufferArchive referenceArchive(0,1024*1024,50,ON::Version());require(referenceArchive.WriteObject(*edge->SegmentCurve(0)),"PolyEdgeSegment serializes reference data");ON_Read3dmBufferArchive referenceRead(referenceArchive.SizeOfArchive(),referenceArchive.Buffer(),false,50,ON::Version());ON_Object* decoded=nullptr;require(referenceRead.ReadObject(&decoded)==1,"PolyEdgeSegment reference decode");std::unique_ptr<ON_Object> ownsDecoded(decoded);auto unresolved=ON_PolyEdgeSegment::Cast(decoded);require(unresolved&&!unresolved->ProxyCurve()&&unresolved->Dimension()==0,"decoded PolyEdgeSegment requires explicit reference resolution");
    ON_Hatch edgeHatch;edgeHatch.SetPlane(ON_xy_plane);edgeHatch.SetPatternIndex(p.ModelComponent()->Index());edgeHatch.AddLoop(new ON_HatchLoop(edge,ON_HatchLoop::ltOuter));rejected=false;try{validateHatchRhino5Data(edgeHatch);}catch(const ExchangeError& e){rejected=std::string(e.what()).find("ON_PolyEdgeCurve")!=std::string::npos;}require(rejected,"exact class gate cannot accept PolyEdgeCurve as ordinary PolyCurve");
    auto surf=new ON_NurbsSurface(2,false,2,2,2,2);for(int i=0;i<2;++i)for(int j=0;j<2;++j)surf->SetCV(i,j,ON_3dPoint(i,j,0));for(int i=0;i<2;++i){surf->SetKnot(i,0,0);surf->SetKnot(i,1,1);}require(surf->IsValid(),"valid dimension2 native surface fixture");auto parameter=new ON_ArcCurve(ON_Circle(ON_Plane(ON_3dPoint(0.5,0.5,0),ON_3dVector::ZAxis),0.25));parameter->ChangeDimension(2);auto onSurface=new ON_CurveOnSurface(parameter,nullptr,surf);require(onSurface->IsValid()&&onSurface->Dimension()==2,"CurveOnSurface can be dimension2; cannot globally declare inapplicable");ON_Hatch surfaceHatch;surfaceHatch.SetPlane(ON_xy_plane);surfaceHatch.SetPatternIndex(p.ModelComponent()->Index());surfaceHatch.AddLoop(new ON_HatchLoop(onSurface,ON_HatchLoop::ltOuter));require(surfaceHatch.IsValid()&&onSurface->IsClosed(),"valid closed native dimension2 CurveOnSurface Hatch loop");rejected=false;try{validateHatchRhino5Data(surfaceHatch);}catch(const ExchangeError& e){rejected=std::string(e.what()).find("ON_CurveOnSurface")!=std::string::npos;}require(rejected,"CurveOnSurface needs its own child surface/curve adapter");
    QJsonArray registered;for(auto name:{"ON_ArcCurve","ON_LineCurve","ON_NurbsCurve","ON_PolylineCurve","ON_PolyCurve","ON_CurveProxy","ON_CurveOnSurface","ON_PolyEdgeSegment","ON_PolyEdgeCurve"}){auto c=ON_ClassId::ClassId(name);require(c,"all nine native curve subclasses registered");registered.append(QJsonObject{{"class_name",name},{"class_uuid",id(c->Uuid())}});}save(std::filesystem::temp_directory_path()/"om9-hatch-loops-sdk-probes.json",QJsonDocument(QJsonObject{{"registered_curve_classes",registered},{"curve_proxy_write",false},{"polyedge_segment_read_dimension",0},{"polyedge_curve_exact_gate",true},{"curve_on_surface_valid_closed_dimension2_loop",true}}).toJson());
    require(cases==8,"four native root types mm/cm");std::cout<<"Hatch loop8 subtype mm/cm roundtrips; recursive userdata/refs/inactive gradients/atomic guards PASS\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
