#include "ThreeDmInventory.h"
#include "ThreeDmNativeReferences.h"
#include "opennurbs_polyedgecurve.h"
#include <QDir>
#include <QFile>
#include <QJsonDocument>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
static QString uuid(ON_UUID id){char s[37]{};ON_UuidToString(id,s);return QString::fromLatin1(s);}
static int edgeMappingCases(QDir dir){int count=0;for(bool consistent:{true,false})for(bool reversed:{false,true}){
    ONX_Model model;ON_Layer layer;layer.SetName(L"Parametric owner");model.AddModelComponent(layer);
    ON_3dPoint corners[8]={ON_3dPoint(0,0,0),ON_3dPoint(2,0,0),ON_3dPoint(2,3,0),ON_3dPoint(0,3,0),ON_3dPoint(0,0,4),ON_3dPoint(2,0,4),ON_3dPoint(2,3,4),ON_3dPoint(0,3,4)};
    auto brep=ON_BrepBox(corners);require(brep&&brep->IsValid(),"Valid parametric topology");auto& edge=brep->m_E[0];require(edge.SetDomain(11,23)&&brep->IsValid(),"Independent Brep edge evaluation parameter domain");auto added=model.AddManagedModelGeometryComponent(brep,nullptr);auto c3=edge.EdgeCurveOf();
    auto ref=new ON_PolyEdgeCurve;require(ref->Create(c3,added.ModelComponent()->Id()),"Create exact native reference");auto segment=ref->SegmentCurve(0);segment->m_component_index=edge.ComponentIndex();segment->m_edge_domain=ON_Interval(15,21);
    ON_Interval proxy(edge.RealCurveParameter(15),edge.RealCurveParameter(21));require(proxy.IsIncreasing(),"Independent affine edge to C3 domain");if(!consistent)proxy=edge.ProxyCurveDomain();require(segment->SetProxyCurveDomain(proxy),"Native proxy interval inside real owner");if(reversed)segment->Reverse();segment->SetDomain(31,47);ref->SetDomain(31,47);
    auto uv=new ON_LineCurve(ON_3dPoint(0,0,0),ON_3dPoint(1,1,0));uv->ChangeDimension(2);uv->SetDomain(31,47);auto root=new ON_CurveOnSurface(uv,ref,new ON_PlaneSurface(ON_xy_plane));require(root->IsValid(),"Native validity alone does not prove reference parameter consistency");auto component=model.AddManagedModelGeometryComponent(root,nullptr);
    auto path=std::filesystem::path(dir.filePath(QString("edge-consistent-%1-reversed-%2.3dm").arg(consistent).arg(reversed)).toStdWString());require(model.Write(path.c_str(),5,nullptr),"Write semantic consistency fixture");auto archive=inspectArchive(path,1);auto id=uuid(component.ModelComponent()->Id());auto analysis=archive.nativeReferences->diagnostics[id].toObject();
    require(analysis["status"]==(consistent?"linked":"invalid"),"Native edge/proxy domains must represent the same affine parameter interval");
    if(consistent){auto graph=archive.nativeReferences->graphs.at(id);auto linked=ON_CurveOnSurface::Cast(graph->geometry.at(id).get());auto child=ON_PolyEdgeCurve::Cast(linked->m_c3)->SegmentCurve(0);for(int i=0;i<5;++i){auto t=31+16*i/4.;require(child->PointAt(t).DistanceTo(child->BrepEdge()->PointAt(child->EdgeParameter(t)))<1e-12,"Native geometry and topological EdgeParameter agree across strict subdomain");}}
    else require(!archive.nativeReferences->graphs.contains(id)&&analysis["message"].toString().contains("parameter"),"Inconsistent parameter fields refuse without exposing a graph");++count;
}return count;}
int main(){try{ON::Begin();QDir dir(QStringLiteral(OM9_REFERENCE_INTEGRITY_DIR));require(QDir().mkpath(dir.path()),"Evidence directory");
    ONX_Model model;ON_Layer layer;layer.SetName(L"Shared owners");model.AddModelComponent(layer);
    auto target=new ON_LineCurve(ON_3dPoint(0,0,0),ON_3dPoint(1,2,3));target->SetDomain(11,23);auto owner=model.AddManagedModelGeometryComponent(target,nullptr);require(!owner.IsEmpty(),"Add real shared target");QJsonArray roots;
    for(int i=0;i<3;++i){auto ref=new ON_PolyEdgeCurve;require(ref->Create(target,owner.ModelComponent()->Id()),"Create shared reference");auto uv=new ON_LineCurve(ON_3dPoint(0,0,0),ON_3dPoint(1,1,0));uv->ChangeDimension(2);uv->SetDomain(11,23);auto root=new ON_CurveOnSurface(uv,ref,new ON_PlaneSurface(ON_xy_plane));require(root->IsValid(),"Valid root");auto component=model.AddManagedModelGeometryComponent(root,nullptr);roots.append(uuid(component.ModelComponent()->Id()));}
    auto file=std::filesystem::path(dir.filePath("shared-owner.3dm").toStdWString());require(model.Write(file.c_str(),5,nullptr),"Write real shared-owner source");auto archive=inspectArchive(file,1);require(archive.nativeReferences->graphs.size()==3,"Three linked root graphs");
    const ON_Curve* shared=nullptr;std::shared_ptr<NativeReferenceGraph> survivor;
    for(auto id:roots){auto graph=archive.nativeReferences->graphs.at(id.toString());auto root=ON_CurveOnSurface::Cast(graph->geometry.at(id.toString()).get());require(root&&root->IsValid(),"Actual native root valid");auto segment=ON_PolyEdgeCurve::Cast(root->m_c3)->SegmentCurve(0);if(!shared)shared=segment->ProxyCurve();else require(segment->ProxyCurve()==shared,"Shared source owner must be cloned exactly once across root graphs");survivor=graph;}
    for(const auto& [id,graph]:archive.nativeReferences->graphs)require(graph->geometry.size()==2,"Each shared graph retains exactly its own root and required owner closure");
    NativeReferenceLimits limits;limits.cloneBytes=1;auto bounded=resolveNativeReferences(archive.nativeModel,archive.document["records"].toArray(),limits);
    require(bounded->graphs.empty(),"Aggregate SDK-accounted byte limit must refuse before native cloning");
    for(auto value:bounded->diagnostics)require(value.toObject()["status"]=="limit","Budget refusal is distinct from invalid geometry");
    const auto records=archive.document["records"].toArray();size_t needed=0;
    for(const auto& [key,geometry]:archive.nativeReferences->graphs.begin()->second->geometry)needed+=geometry->SizeOf();
    for(auto id:roots)if(id.toString()!=archive.nativeReferences->graphs.begin()->first){auto component=ON_ModelGeometryComponent::Cast(archive.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(id.toString().toLatin1().constData())).ModelComponent());needed+=component->Geometry(nullptr)->SizeOf();}
    limits={};limits.cloneBytes=needed;auto exact=resolveNativeReferences(archive.nativeModel,records,limits);require(exact->graphs.size()==3&&exact->statistics["clone_attempts"].toInt()==4&&exact->statistics["sdk_accounted_clone_bytes"].toDouble()==needed&&exact->statistics["shared_cache_hits"].toInt()==2,"Exact shared aggregate byte budget includes four unique native clones");
    limits.cloneBytes=needed-1;auto shortByOne=resolveNativeReferences(archive.nativeModel,records,limits);require(shortByOne->graphs.size()==2,"One-byte-short aggregate budget refuses only the last graph");
    limits={};limits.owners=3;auto ownerLimit=resolveNativeReferences(archive.nativeModel,records,limits);require(ownerLimit->graphs.size()==2&&ownerLimit->statistics["clone_attempts"]==3,"Aggregate clone count cannot reset between roots");
    limits={};limits.nodes=0;auto noNodes=resolveNativeReferences(archive.nativeModel,records,limits);require(noNodes->graphs.empty()&&noNodes->statistics["visited_nodes"]==0,"Aggregate node quota checked before traversal");
    limits={};limits.depth=0;auto noDepth=resolveNativeReferences(archive.nativeModel,records,limits);require(noDepth->graphs.empty()&&noDepth->statistics["clone_attempts"]==0,"Depth quota checked before cloning");
    auto before=shared->PointAt(17);archive={};require(before.DistanceTo(shared->PointAt(17))<1e-12&&survivor->geometry.contains(uuid(owner.ModelComponent()->Id())),"Surviving root owns shared targets after sibling/inventory release");
    auto firstId=roots[0].toString();auto firstComponent=ON_ModelGeometryComponent::Cast(model.ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(firstId.toLatin1().constData())).ModelComponent());auto first=ON_Curve::Cast(firstComponent->Geometry(nullptr));
    auto nestedRef=new ON_PolyEdgeCurve;require(nestedRef->Create(first,firstComponent->Id()),"Real nested curve-owner source");auto uv=new ON_LineCurve(ON_3dPoint(0,0,0),ON_3dPoint(1,1,0));uv->ChangeDimension(2);uv->SetDomain(11,23);auto nestedRoot=new ON_CurveOnSurface(uv,nestedRef,new ON_PlaneSurface(ON_xy_plane));require(nestedRoot->IsValid(),"Native nested fixture valid");auto nestedId=uuid(model.AddManagedModelGeometryComponent(nestedRoot,nullptr).ModelComponent()->Id());
    auto nestedFile=std::filesystem::path(dir.filePath("nested-owner.3dm").toStdWString());require(model.Write(nestedFile.c_str(),5,nullptr),"Write nested shared-owner source");auto nestedArchive=inspectArchive(nestedFile,1);require(nestedArchive.nativeReferences->graphs.size()==4,"Four valid roots including nested CurveOnSurface owner");auto nestedGraph=nestedArchive.nativeReferences->graphs.at(nestedId);require(nestedGraph->geometry.size()==3&&nestedArchive.nativeReferences->statistics["clone_attempts"]==5,"Nested graph retains exactly root plus transitive shared target closure");
    auto nestedCurve=ON_CurveOnSurface::Cast(nestedGraph->geometry.at(nestedId).get());auto proxy=ON_PolyEdgeCurve::Cast(nestedCurve->m_c3)->SegmentCurve(0);require(proxy->ProxyCurve()==nestedArchive.nativeReferences->graphs.at(firstId)->geometry.at(firstId).get(),"Nested owner root itself reused without a new native clone");auto nestedPoint=proxy->PointAt(17);nestedArchive={};require(proxy->PointAt(17).DistanceTo(nestedPoint)<1e-12&&nestedCurve->IsValid(),"Nested closure survives release of all sibling graphs");
    const auto mapping=edgeMappingCases(dir);
    QFile report(dir.filePath("results.json"));require(report.open(QIODevice::WriteOnly),"Report");report.write(QJsonDocument(QJsonObject{{"ok",true},{"shared_roots",3},{"shared_target_identity",true},{"lifetime",true},{"budget_cases",6},{"edge_mapping_cases",mapping},{"unique_clones",4},{"nested_clones",5},{"nested_closure",3},{"accounted_bytes",static_cast<double>(needed)}}).toJson());std::cout<<"Reference graph integrity PASS\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
