#include "ThreeDmMerge.h"
#include "ThreeDmArchive.h"
#include <QFile>
#include <iostream>
#include <cmath>
#include <BRepAdaptor_Curve.hxx>
#include <TopoDS.hxx>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool value,const char* message){if(!value)throw ExchangeError(message);}
static QString uuid(const ON_UUID& value){char text[37]{};ON_UuidToString(value,text);return QString::fromLatin1(text);}
static QByteArray bytes(const std::filesystem::path& path){QFile file(QString::fromStdWString(path.wstring()));require(file.open(QIODevice::ReadOnly),"read output");return file.readAll();}
static void reject(const QJsonObject& request,const std::filesystem::path& path){auto before=bytes(path);bool failed=false;try{writePreservedArchive(request,path);}catch(const ExchangeError&){failed=true;}require(failed&&before==bytes(path),"invalid native transform must reject atomically");}
static const ON_ModelGeometryComponent* geometry(const ArchiveInventory& archive,ON_UUID identity){return ON_ModelGeometryComponent::Cast(archive.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,identity).ModelComponent());}
static void run(ON::LengthUnitSystem units){
    const ON_3dVector diagonalNormal(std::sqrt(2.0),std::sqrt(2.0),0),expectedNormal(-4/std::sqrt(13.0),6/std::sqrt(13.0),0);
    ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);ON_Layer layer;layer.SetName(L"Native retained");model.AddModelComponent(layer);
    ON_3dmObjectAttributes attributes;attributes.m_name=L"Native cloud";attributes.SetUserString(L"UserText",L"keep attributes");
    ON_PointCloud cloud;cloud.m_P.Append(ON_3dPoint(1,2,3));cloud.m_P.Append(ON_3dPoint(4,5,6));cloud.m_N.Append(ON_3dVector(1,0,0));cloud.m_N.Append(diagonalNormal);cloud.m_C.Append(ON_Color(17,31,47));cloud.m_C.Append(ON_Color(101,151,201));cloud.SetUserString(L"Cloud note",L"keep native point userdata");auto cloudRef=model.AddModelGeometryComponent(&cloud,&attributes);
    ON_TextDot dot(ON_3dPoint(5,6,7),L"Native primary",L"Native secondary");dot.SetUserString(L"Dot note",L"keep both text fields");attributes.m_name=L"Native dot";auto dotRef=model.AddModelGeometryComponent(&dot,&attributes);
    auto path=std::filesystem::temp_directory_path()/(units==ON::LengthUnitSystem::Millimeters?"om9-native-retained-transform-mm.3dm":"om9-native-retained-transform-cm.3dm");require(model.Write(path.c_str(),5,nullptr),"native transform source write");auto original=bytes(path);auto input=inspectArchive(path);double scale=input.document["scale_mm"].toDouble();
    QJsonObject source{{"namespace","12345678-1234-1234-1234-123456789abc"},{"snapshot",QString::fromStdWString(path.wstring())},{"archive_sha256",input.document["archive_sha256"]},{"scale_mm",scale}};
    QJsonArray matrix{0,-3,0,10,2,0,0,20,0,0,4,30,0,0,0,1};
    QJsonObject selection{{"namespace",source["namespace"]},{"source_uuid",uuid(cloudRef.ModelComponent()->Id())},{"host_id","cloud"},{"action","transform"},{"geometry_matrix",matrix}};
    QJsonObject dotSelection=selection;dotSelection["source_uuid"]=uuid(dotRef.ModelComponent()->Id());dotSelection["host_id"]="dot";
    QJsonObject request{{"schema_version",1},{"sources",QJsonArray{source}},{"selected",QJsonArray{selection,dotSelection}}};auto output=path.parent_path()/"om9-native-retained-transformed.3dm";
    writePreservedArchive(request,output);auto result=inspectArchive(output);require(result.document["records"].toArray().size()==2&&result.document["issues"].toArray().isEmpty(),"retained selected closure and class inventory");
    auto component=geometry(result,cloudRef.ModelComponent()->Id());auto actual=component?ON_PointCloud::Cast(component->Geometry(nullptr)):nullptr;require(actual&&actual->m_P.Count()==2&&actual->m_N.Count()==2&&actual->m_C.Count()==2,"native cloud counts and optional fields retained");
    require(actual->m_P[0].DistanceTo(ON_3dPoint(10-6*scale,20+2*scale,30+12*scale))<1e-8&&actual->m_P[1].DistanceTo(ON_3dPoint(10-15*scale,20+8*scale,30+24*scale))<1e-8,"cloud affine points after unit normalization exactly once");
    require((actual->m_N[0]-ON_3dVector(0,1,0)).Length()<1e-10&&(actual->m_N[1]-expectedNormal).Length()<1e-10,"cloud inverse transpose normals rotate under nonuniform affine transform");
    require(actual->m_C[0]==cloud.m_C[0]&&actual->m_C[1]==cloud.m_C[1],"cloud per-point colors retained");ON_wString text;require(actual->GetUserString(L"Cloud note",text)&&text==L"keep native point userdata"&&component->Attributes(nullptr)->GetUserString(L"UserText",text)&&text==L"keep attributes","cloud geometry and attribute userdata retained");
    auto sourceDot=ON_TextDot::Cast(geometry(input,dotRef.ModelComponent()->Id())->Geometry(nullptr));component=geometry(result,dotRef.ModelComponent()->Id());auto actualDot=component?ON_TextDot::Cast(component->Geometry(nullptr)):nullptr;require(actualDot&&actualDot->CenterPoint().DistanceTo(ON_3dPoint(10-18*scale,20+10*scale,30+28*scale))<1e-8&&ON_wString(actualDot->PrimaryText())==ON_wString(sourceDot->PrimaryText())&&ON_wString(actualDot->SecondaryText())==ON_wString(sourceDot->SecondaryText()),"dot point and Rhino5 source text fields transformed natively");
    ON_UUID copiedId,definitionId,instanceId;ON_CreateUuid(copiedId);ON_CreateUuid(definitionId);ON_CreateUuid(instanceId);
    QJsonObject copy{{"namespace",source["namespace"]},{"host_id","cloud-copy"},{"source_uuid",selection["source_uuid"]},{"output_uuid",uuid(copiedId)},{"member_matrix",matrix},{"follow_canonical",false}};
    QJsonObject definition{{"namespace",source["namespace"]},{"host_id","cloud-definition"},{"source_uuid",uuid(definitionId)},{"name","Retained cloud copy"},{"member_uuids",QJsonArray{uuid(copiedId)}}};
    QJsonObject instance{{"namespace",source["namespace"]},{"host_id","cloud-instance"},{"source_uuid",uuid(instanceId)},{"role","top-level"},{"instance_definition_uuid",uuid(definitionId)},{"instance_matrix",QJsonArray{1,0,0,100,0,1,0,200,0,0,1,300,0,0,0,1}}};
    auto copiedRequest=request;copiedRequest["selected"]=QJsonArray{};copiedRequest["member_copies"]=QJsonArray{copy};copiedRequest["new_definitions"]=QJsonArray{definition};copiedRequest["new_instances"]=QJsonArray{instance};writePreservedArchive(copiedRequest,output);auto copied=inspectArchive(output);component=geometry(copied,copiedId);auto copiedCloud=component?ON_PointCloud::Cast(component->Geometry(nullptr)):nullptr;
    require(copiedCloud&&copied.document["records"].toArray().size()==2&&!geometry(copied,cloudRef.ModelComponent()->Id()),"copied native cloud selected closure omits unrelated original roots");
    require(copiedCloud->m_P[0].DistanceTo(ON_3dPoint(10-6*scale,20+2*scale,30+12*scale))<1e-8&&(copiedCloud->m_N[0]-ON_3dVector(0,1,0)).Length()<1e-10&&(copiedCloud->m_N[1]-expectedNormal).Length()<1e-10&&copiedCloud->m_C[1]==cloud.m_C[1],"copied native cloud transforms local points normals and colors once");
    auto nativeDefinition=ON_InstanceDefinition::Cast(copied.nativeModel->ComponentFromId(ON_ModelComponent::Type::InstanceDefinition,definitionId).ModelComponent());auto nativeInstance=ON_InstanceRef::Cast(geometry(copied,instanceId)->Geometry(nullptr));require(nativeDefinition&&nativeInstance&&nativeDefinition->BoundingBox().IsValid()&&nativeInstance->m_bbox.IsValid()&&(nativeInstance->m_xform*copiedCloud->m_P[0]).DistanceTo(ON_3dPoint(110-6*scale,220+2*scale,330+12*scale))<1e-8,"copied cloud native definition bounds and world placement verified");
    auto memberTransform=selection;memberTransform["source_uuid"]=uuid(copiedId);memberTransform["host_id"]="current-cloud-member";memberTransform["geometry_matrix"]=QJsonArray{1,0,0,7,0,1,0,8,0,0,1,9,0,0,0,1};copiedRequest["dependency_overlays"]=QJsonArray{memberTransform};writePreservedArchive(copiedRequest,output);auto editedCopy=inspectArchive(output);auto editedCloud=ON_PointCloud::Cast(geometry(editedCopy,copiedId)->Geometry(nullptr));require(editedCloud&&editedCloud->m_P[0].DistanceTo(ON_3dPoint(17-6*scale,28+2*scale,39+12*scale))<1e-8&&(editedCloud->m_N[0]-ON_3dVector(0,1,0)).Length()<1e-10,"reachable retained member native transform overlay preserves local coordinates and normals");
    nativeDefinition=ON_InstanceDefinition::Cast(editedCopy.nativeModel->ComponentFromId(ON_ModelComponent::Type::InstanceDefinition,definitionId).ModelComponent());nativeInstance=ON_InstanceRef::Cast(geometry(editedCopy,instanceId)->Geometry(nullptr));auto cloudBounds=editedCloud->BoundingBox();auto worldBounds=cloudBounds;worldBounds.Transform(nativeInstance->m_xform);require(nativeDefinition->BoundingBox().m_min.DistanceTo(cloudBounds.m_min)<1e-8&&nativeDefinition->BoundingBox().m_max.DistanceTo(cloudBounds.m_max)<1e-8&&nativeInstance->m_bbox.m_min.DistanceTo(worldBounds.m_min)<1e-8&&nativeInstance->m_bbox.m_max.DistanceTo(worldBounds.m_max)<1e-8,"retained member native delta refreshes definition and reference bounds");
    auto badMember=memberTransform;badMember["source_uuid"]=selection["source_uuid"];copiedRequest["dependency_overlays"]=QJsonArray{badMember};reject(copiedRequest,output);
    ONX_Model blockModel;blockModel.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);blockModel.AddModelComponent(layer);auto memberAttributes=attributes;memberAttributes.SetMode(ON::idef_object);auto memberCloud=blockModel.AddModelGeometryComponent(&cloud,&memberAttributes);auto memberDot=blockModel.AddModelGeometryComponent(&dot,&memberAttributes);ON_InstanceDefinition sourceDefinition;sourceDefinition.SetName(L"Native selected members");sourceDefinition.AddInstanceGeometryId(memberCloud.ModelComponent()->Id());sourceDefinition.AddInstanceGeometryId(memberDot.ModelComponent()->Id());auto sourceDefinitionRef=blockModel.AddModelComponent(sourceDefinition);ON_InstanceRef sourceInstance;sourceInstance.m_instance_definition_uuid=sourceDefinitionRef.ModelComponent()->Id();sourceInstance.m_xform=ON_Xform::TranslationTransformation(ON_3dVector(100,200,300));auto rootAttributes=attributes;auto sourceInstanceRef=blockModel.AddModelGeometryComponent(&sourceInstance,&rootAttributes);
    auto blockPath=path.parent_path()/(scale==1?"om9-native-selected-members-mm.3dm":"om9-native-selected-members-cm.3dm");require(blockModel.Write(blockPath.c_str(),5,nullptr),"native selected-member source fixture write");auto blockBytes=bytes(blockPath);auto blockInput=inspectArchive(blockPath);auto blockSource=source;blockSource["snapshot"]=QString::fromStdWString(blockPath.wstring());blockSource["archive_sha256"]=blockInput.document["archive_sha256"];
    auto selectedCopy=copy;selectedCopy["source_uuid"]=uuid(memberCloud.ModelComponent()->Id());selectedCopy["role"]="top-level";QJsonObject selectedRoot{{"namespace",source["namespace"]},{"host_id","selected-native-cloud"},{"source_uuid",uuid(copiedId)},{"action","unchanged"}};QJsonObject selectedRequest{{"schema_version",1},{"sources",QJsonArray{blockSource}},{"selected",QJsonArray{selectedRoot}},{"member_copies",QJsonArray{selectedCopy}}};writePreservedArchive(selectedRequest,output);auto selectedCloudArchive=inspectArchive(output);auto selectedComponent=geometry(selectedCloudArchive,copiedId);auto selectedCloud=selectedComponent?ON_PointCloud::Cast(selectedComponent->Geometry(nullptr)):nullptr;require(selectedCloud&&selectedCloudArchive.document["records"].toArray().size()==1&&selectedCloudArchive.document["records"].toArray()[0].toObject()["role"]=="top-level"&&!selectedComponent->Attributes(nullptr)->IsInstanceDefinitionObject()&&selectedCloudArchive.nativeModel->ActiveComponentCount(ON_ModelComponent::Type::InstanceDefinition)==0,"native selected definition member becomes independent top-level geometry without ancestors");
    require(selectedCloud->m_P[0].DistanceTo(ON_3dPoint(10-6*scale,20+2*scale,30+12*scale))<1e-8&&(selectedCloud->m_N[1]-expectedNormal).Length()<1e-10&&selectedCloud->m_C[0]==cloud.m_C[0]&&selectedCloud->GetUserString(L"Cloud note",text)&&text==L"keep native point userdata","selected cloud current transform normal magnitude colors and native userdata");writePreservedArchive(selectedRequest,output);require(geometry(inspectArchive(output),copiedId)!=nullptr,"selected member repeat retains caller output UUID");
    auto sourceRoot=selectedRoot;sourceRoot["host_id"]="original-block-root";sourceRoot["source_uuid"]=uuid(sourceInstanceRef.ModelComponent()->Id());selectedRequest["selected"]=QJsonArray{selectedRoot,sourceRoot};writePreservedArchive(selectedRequest,output);auto mixedSelected=inspectArchive(output);require(mixedSelected.document["records"].toArray().size()==4&&geometry(mixedSelected,memberCloud.ModelComponent()->Id())&&geometry(mixedSelected,copiedId)&&mixedSelected.nativeModel->ActiveComponentCount(ON_ModelComponent::Type::InstanceDefinition)==1,"mixed selected block and independent member preserve both native identities and exact closure");
    for(auto bad:QJsonArray{QJsonValue("unknown"),QJsonValue(0),QJsonValue(QJsonObject{})}){auto malformedCopy=selectedCopy;malformedCopy["role"]=bad;auto malformed=selectedRequest;malformed["member_copies"]=QJsonArray{malformedCopy};reject(malformed,output);}auto omitted=selectedRequest;omitted["selected"]=QJsonArray{sourceRoot};reject(omitted,output);require(bytes(blockPath)==blockBytes,"selected member native source and block ownership remain immutable");
    auto unchanged=selection;unchanged["action"]="unchanged";unchanged.remove("geometry_matrix");request["selected"]=QJsonArray{unchanged};writePreservedArchive(request,output);auto untouched=inspectArchive(output);auto initial=geometry(input,cloudRef.ModelComponent()->Id());component=geometry(untouched,cloudRef.ModelComponent()->Id());auto untouchedCloud=component?ON_PointCloud::Cast(component->Geometry(nullptr)):nullptr;require(untouchedCloud&&(untouchedCloud->m_N[0]-cloud.m_N[0]).Length()<1e-10&&untouchedCloud->m_C[0]==cloud.m_C[0],"untransformed native optional fields retained");if(scale==1)require(component->Geometry(nullptr)->DataCRC(0)==initial->Geometry(nullptr)->DataCRC(0),"unchanged cloud native checksum retained");
    request["selected"]=QJsonArray{selection};for(auto bad:QJsonArray{QJsonArray{},QJsonArray{1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1},QJsonArray{1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1},QJsonArray{1,0,0,"bad",0,1,0,0,0,0,1,0,0,0,0,1}}){auto invalid=selection;invalid["geometry_matrix"]=bad;auto malformed=request;malformed["selected"]=QJsonArray{invalid};reject(malformed,output);}
    auto ambiguous=selection;ambiguous["instance_matrix"]=matrix;request["selected"]=QJsonArray{ambiguous};reject(request,output);
    if(scale==1){auto newerPath=path.parent_path()/"om9-native-retained-transform-v6.3dm";require(model.Write(newerPath.c_str(),6,nullptr),"Rhino6 secondary text source write");auto newer=inspectArchive(newerPath);auto newerDot=ON_TextDot::Cast(geometry(newer,dotRef.ModelComponent()->Id())->Geometry(nullptr));require(newerDot&&ON_wString(newerDot->SecondaryText())==L"Native secondary","Rhino6 source retains secondary text");auto newerSource=source;newerSource["snapshot"]=QString::fromStdWString(newerPath.wstring());newerSource["archive_sha256"]=newer.document["archive_sha256"];request["sources"]=QJsonArray{newerSource};request["selected"]=QJsonArray{dotSelection};reject(request,output);}
    require(bytes(path)==original,"native transform source stays immutable");
}
static void rationalCurveTransform(){
    ON_NurbsCurve source(2,true,3,3);source.SetCV(0,ON_4dPoint(0,0,0,1));source.SetCV(1,ON_4dPoint(4,6,0,2));source.SetCV(2,ON_4dPoint(2,-0.5,0,0.5));require(source.MakeClampedUniformKnotVector(1)&&source.IsValid(),"native rational2D transform fixture");
    ON_Xform matrix=ON_Xform::IdentityTransformation;matrix[0][0]=-2;matrix[1][1]=3;matrix[2][3]=9;auto curve=source;transformNativeGeometry(curve,matrix);require(curve.Dimension()==3&&curve.IsRational()&&curve.Order()==source.Order()&&curve.KnotCount()==source.KnotCount(),"out-of-plane rational2D transform explicitly promotes dimensions without changing basis");
    for(int i=0;i<curve.KnotCount();++i)require(curve.Knot(i)==source.Knot(i),"native promoted curve keeps exact knot vector");
    for(int i=0;i<curve.CVCount();++i){ON_3dPoint before,after;require(source.GetCV(i,before)&&curve.GetCV(i,after)&&(matrix*before).DistanceTo(after)<1e-10&&curve.Weight(i)==source.Weight(i),"native promoted curve keeps exact weights and analytic3D control points");}
    ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);ON_Layer layer;layer.SetName(L"Rational plane");model.AddModelComponent(layer);ON_3dmObjectAttributes attributes;attributes.SetMode(ON::idef_object);auto member=model.AddModelGeometryComponent(&source,&attributes);ON_InstanceDefinition definition;definition.SetName(L"Rational2D plane");definition.AddInstanceGeometryId(member.ModelComponent()->Id());auto target=model.AddModelComponent(definition);ON_InstanceRef instance;instance.m_instance_definition_uuid=target.ModelComponent()->Id();instance.m_xform=matrix;attributes.SetMode(ON::normal_object);model.AddModelGeometryComponent(&instance,&attributes);auto path=std::filesystem::temp_directory_path()/"om9-native-rational-plane.3dm";require(model.Write(path.c_str(),5,nullptr),"rational plane fixture write");auto archive=readArchive(path);require(archive.items.size()==1,"rational block geometry-only expansion");BRepAdaptor_Curve expanded(TopoDS::Edge(std::get<TopoDS_Shape>(archive.items[0].geometry)));auto expected=matrix*source.PointAt(0.5);require(expanded.Value(0.5).Distance(gp_Pnt(expected.x,expected.y,expected.z))<1e-9,"geometry-only2D rational block transform retains out-of-plane point");
    matrix[2][3]=0;auto planar=source;transformNativeGeometry(planar,matrix);require(planar.Dimension()==2,"plane-preserving native curve copy retains2D dimension");require(source.Dimension()==2,"native source curve remains immutable");
}
int main(){try{ON::Begin();rationalCurveTransform();run(ON::LengthUnitSystem::Millimeters);run(ON::LengthUnitSystem::Centimeters);std::cout<<"Native retained transforms and selected members passed: rational2D/3D, TextDot and point cloud coordinates, normals, colors, userdata, mm/cm, atomic invalid matrices\n";return 0;}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
