#include "ThreeDmArchive.h"
#include "ThreeDmInventory.h"
#include "ThreeDmMerge.h"
#include "ThreeDmHatch.h"
#include <limits>
#include <QJsonArray>
#include <QFile>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool ok,const char* message){if(!ok)throw ExchangeError(message);}
static QString uuid(ON_UUID id){char text[37]{};ON_UuidToString(id,text);return QString::fromLatin1(text);}
static QJsonObject find(const QJsonArray& rows,const QString& id){for(auto value:rows)if(value.toObject()["source_uuid"]==id)return value.toObject();throw ExchangeError("Missing hatch test row");}
static const ON_Hatch* nativeHatch(const ArchiveInventory& archive,const QString& id){auto component=ON_ModelGeometryComponent::Cast(archive.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(id.toLatin1().constData())).ModelComponent());return component?ON_Hatch::Cast(component->Geometry(nullptr)):nullptr;}
int main(){try{ON::Begin();
    for(auto invalid:{std::numeric_limits<double>::quiet_NaN(),std::numeric_limits<double>::infinity()}){ON_HatchPattern pattern;pattern.SetName(L"Invalid dashes");pattern.SetFillType(ON_HatchPattern::HatchFillType::Lines);ON_HatchLine line;line.AppendDash(invalid);pattern.AddHatchLine(line);bool rejected=false;try{hatchPatternFacts(pattern);}catch(const ExchangeError&){rejected=true;}require(rejected,"Native IsValid omits dash finiteness; inventory must reject nonfinite dash values");}
    for(auto units:{ON::LengthUnitSystem::Millimeters,ON::LengthUnitSystem::Centimeters}){
    ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(units);ON_Layer layer;layer.SetName(L"Hatches");model.AddModelComponent(layer);ON_HatchPattern unused;unused.SetName(L"Unused solid");model.AddModelComponent(unused);ON_HatchPattern pattern;pattern.SetName(L"Native dashed pattern");pattern.SetDescription(L"Keep spacing dash and orientation");pattern.SetFillType(ON_HatchPattern::HatchFillType::Lines);ON_SimpleArray<double> dashes;dashes.Append(3.123456789012345);dashes.Append(-1.234567890123456);dashes.Append(0);ON_HatchLine line(0.234567890123456,ON_2dPoint(0.123456789012345,0.5),ON_2dVector(0.25,2.345678901234567),dashes);pattern.AddHatchLine(line);pattern.SetUserString(L"Pattern",L"Preserve table userdata");auto patternRef=model.AddModelComponent(pattern);auto actualPattern=ON_HatchPattern::Cast(patternRef.ModelComponent());require(actualPattern&&actualPattern->Index()>0,"nonzero custom pattern index");
    ON_NurbsCurve outer,inner;require(ON_Circle(ON_xy_plane,10).GetNurbForm(outer)&&ON_Circle(ON_xy_plane,2).GetNurbForm(inner),"rational loop creation");outer.ChangeDimension(2);inner.ChangeDimension(2);ON_SimpleArray<const ON_Curve*> loops;loops.Append(&outer);loops.Append(&inner);ON_Hatch hatch;require(hatch.Create(ON_Plane(ON_3dPoint(10,20,30),ON_3dVector(0,0,1)),loops,actualPattern->Index(),0.345678901234567,2.123456789012345),"native hatch create");hatch.SetBasePoint(ON_2dPoint(1.123456789012345,2.234567890123456));hatch.SetUserString(L"Hatch",L"Preserve native rational loops");ON_3dmObjectAttributes attributes;attributes.m_name=L"Hatch";auto ref=model.AddModelGeometryComponent(&hatch,&attributes);auto id=uuid(ref.ModelComponent()->Id());auto patternId=uuid(patternRef.ModelComponent()->Id());auto path=std::filesystem::temp_directory_path()/(units==ON::LengthUnitSystem::Millimeters?"om9-hatch-mm.3dm":"om9-hatch-cm.3dm");require(model.Write(path.c_str(),5,nullptr),"hatch fixture write");auto source=inspectArchive(path);auto row=find(source.document["records"].toArray(),id);require(row["dependencies"].toArray().contains(patternId),"Hatch requires exact custom HatchPattern UUID dependency");require(row["hatch"].isObject()&&find(source.document["components"].toArray(),patternId)["hatch_pattern"].isObject(),"inventory includes native hatch and pattern semantic facts");
    QJsonObject selected{{"namespace","00000000-0000-4000-8000-000000000077"},{"source_uuid",id},{"host_id","hatch"},{"action","unchanged"}};QJsonObject sourceRow{{"namespace",selected["namespace"]},{"snapshot",QString::fromStdWString(path.wstring())},{"archive_sha256",source.document["archive_sha256"]},{"scale_mm",source.document["scale_mm"]}};QJsonObject request{{"schema_version",1},{"sources",QJsonArray{sourceRow}},{"selected",QJsonArray{selected}}};auto output=path.parent_path()/"om9-hatch-output.3dm";writePreservedArchive(request,output);auto checked=inspectArchive(output);auto after=nativeHatch(checked,id);require(after&&after->LoopCount()==2&&ON_NurbsCurve::Cast(after->Loop(0)->Curve())->IsRational(),"native rational hatch loops survive selected Rhino5 write");require(find(checked.document["components"].toArray(),patternId)["hatch_pattern"]==find(source.document["components"].toArray(),patternId)["hatch_pattern"],"exact pattern lines and dashes survive selected closure");require(find(checked.document["records"].toArray(),id)["dependencies"].toArray().contains(patternId),"native hatch pattern reference survives table selection");double scale=units==ON::LengthUnitSystem::Centimeters?10:1;require(std::abs(after->PatternScale()-hatch.PatternScale()*scale)<1e-12,"unit normalization must scale hatch pattern spacing");
    auto rigid=hatch;auto delta=ON_Xform::TranslationTransformation(ON_3dVector(5,6,7));transformNativeGeometry(rigid,delta);ON_BoundingBox originalBox,movedBox;require(hatch.GetTightBoundingBox(originalBox)&&rigid.GetTightBoundingBox(movedBox),"hatch rigid bounds");require(movedBox.m_min.DistanceTo(originalBox.m_min+ON_3dVector(5,6,7))<1e-10&&rigid.PatternScale()==hatch.PatternScale(),"rigid hatch placement moves full boundary without changing pattern spacing");
    auto rejectedHatch=hatch;auto before=nativeGeometryFacts(rejectedHatch);ON_Xform matrix=ON_Xform::IdentityTransformation;matrix[0][1]=0.5;bool rejected=false;try{transformNativeGeometry(rejectedHatch,matrix);}catch(const ExchangeError&){rejected=true;}require(rejected&&nativeGeometryFacts(rejectedHatch)==before,"affine hatch pattern transform without model context must reject without changing fields");
    std::cout<<(scale==1?"mm":"cm")<<": selected native hatch rational loops, exact pattern reference and spacing PASS\n";
}return 0;}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
