#include "ThreeDmMerge.h"
#include "ThreeDmNativeReferences.h"
#include "ThreeDmCurveOnSurface.h"
#include "opennurbs_polyedgecurve.h"
#include <QDir>
#include <QFile>
#include <QTemporaryDir>
#include <QJsonDocument>
#include <QUuid>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static int checks=0;
static void require(bool v,const char* message){++checks;if(!v)throw ExchangeError(message);}
static QByteArray bytes(QString path){QFile f(path);require(f.open(QIODevice::ReadOnly),"Read immutable fixture");return f.readAll();}
static QString alias(QString source,QString ns){return QUuid::createUuidV5(QUuid(ns),QByteArrayLiteral("OpenMatrix9.3dm.merge:")+source.toLatin1()+":0").toString(QUuid::WithoutBraces);}
static QJsonObject remapped(QJsonObject fields,QString owner){
    if(fields.contains("object_uuid"))fields["object_uuid"]=owner;
    if(!fields.value("object_references").toArray().isEmpty())fields["object_references"]=QJsonArray{owner};
    for(auto key:{"parameter","approximation","surface"})if(fields.value(key).isObject())fields[key]=remapped(fields.value(key).toObject(),owner);
    if(fields.contains("segments")){QJsonArray children;for(auto child:fields["segments"].toArray())children.append(remapped(child.toObject(),owner));fields["segments"]=children;}
    return fields;
}
static QJsonObject record(const ArchiveInventory& inv,QString uuid){for(auto v:inv.document["records"].toArray())if(v.toObject()["source_uuid"]==uuid)return v.toObject();throw ExchangeError("Expected namespace root UUID");}
int main(){QJsonArray evidence;try{ON::Begin();QTemporaryDir temp;require(temp.isValid(),"Owned remap staging directory");const QString ns1="11223344-1122-3344-5566-112233445566",ns2="22334455-2233-4455-6677-223344556677";
    for(auto folder:{"rhino5-standalone-reference-20261008","rhino5-mixed-reference-20261008"}){
        QDir fixtures(QStringLiteral(OM9_REMAP_FROZEN)+"/"+folder);auto oracle=QJsonDocument::fromJson(bytes(fixtures.filePath("oracle.json"))).object();
        for(auto value:oracle["cases"].toArray()){auto wanted=value.toObject();auto objects=wanted["objects"].toArray();auto owner=objects[0].toObject()["uuid"].toString(),root=objects[1].toObject()["uuid"].toString();auto source=fixtures.filePath(wanted["fixture"].toString());auto baseline=bytes(source);auto input=inspectArchive(std::filesystem::path(source.toStdWString()));require(input.document["issues"].toArray().isEmpty()&&input.document["archive_sha256"]==wanted["source_sha256"],"Independent source graph and oracle byte binding");
            for(bool copied:{false,true}){
                QJsonArray sources,selected;for(auto ns:{ns1,ns2}){sources.append(QJsonObject{{"namespace",ns},{"snapshot",source},{"archive_sha256",input.document["archive_sha256"]},{"scale_mm",1}});selected.append(QJsonObject{{"namespace",ns},{"source_uuid",root},{"host_id","root"},{"action","unchanged"}});if(copied)selected.append(QJsonObject{{"namespace",ns},{"source_uuid",root},{"host_id","copy"},{"action","duplicate"},{"duplicate_action","unchanged"}});}
                QJsonObject request{{"schema_version",1},{"sources",sources},{"selected",selected}};auto path=std::filesystem::path(temp.filePath("merged.3dm").toStdWString());writeGeometryStagingArchive(request,path);auto output=inspectArchive(path);
                require(output.document["issues"].toArray().isEmpty()&&output.document["records"].toArray().size()==(copied?6:4),"Complete current graph, independent owners and copied roots");
                for(auto ns:{ns1,ns2})for(bool duplicate:{false,true}){if(duplicate&&!copied)continue;auto original=duplicate?QUuid::createUuidV5(QUuid(ns),QByteArrayLiteral("OpenMatrix9.3dm.source-copy:")+root.toLatin1()+":copy").toString(QUuid::WithoutBraces):root;auto uuid=ns==ns1||duplicate?original:alias(original,ns2);auto ownerId=ns==ns1?owner:alias(owner,ns2);auto row=record(output,uuid);
                    require(row["poly_edge_native"].toObject()["object_references"].toArray()==QJsonArray{ownerId},"Every root references its own namespace owner, including repeated import/copy");
                    auto expectedFields=remapped(wanted["native_reference_fields"].toObject(),ownerId);
                    if(row["poly_edge_native"].toObject()!=expectedFields){QFile debug(QStringLiteral(OM9_REMAP_RESULTS)+".mismatch.json");if(debug.open(QIODevice::WriteOnly))debug.write(QJsonDocument(QJsonObject{{"actual",row["poly_edge_native"]},{"expected",expectedFields}}).toJson());}
                    require(row["poly_edge_native"].toObject()==expectedFields,"UUID-only remap preserves native class, domains, reversal and metadata");
                    require(row["native_reference_analysis"].toObject()["status"]=="linked"&&row["dependencies"].toArray().contains(ownerId),"Exact owner closure linked after serialize/read");auto graph=output.nativeReferences->graphs.at(uuid);auto curve=ON_Curve::Cast(graph->geometry.at(uuid).get());auto samples=objects[1].toObject()["samples"].toArray();
                    for(int i=0;i<samples.size();++i){auto p=samples[i].toArray();require(curve->PointAt(curve->Domain().ParameterAt(i/double(samples.size()-1))).DistanceTo(ON_3dPoint(p[0].toDouble(),p[1].toDouble(),p[2].toDouble()))<=1e-12,"Independent interior samples unchanged after remap");}
                    require(graph->geometry.contains(ownerId)||!graph->source->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(ownerId.toLatin1().constData())).IsEmpty(),"Graph owns exact namespace target lifetime");
                }
                auto first=bytes(QString::fromStdWString(path.wstring()));writeGeometryStagingArchive(request,path);auto repeated=inspectArchive(path);require(repeated.document["records"]==output.document["records"],"Repeat export preserves deterministic graph identities and fields");
                QFile target(temp.filePath("protected.3dm"));require(target.open(QIODevice::WriteOnly),"Prepare protected public destination");target.write("keep-target");target.close();bool refused=false;try{writePreservedArchive(request,std::filesystem::path(target.fileName().toStdWString()));}catch(const ExchangeError&){refused=true;}require(refused&&bytes(target.fileName())=="keep-target","V5 target incompatibility remains refused atomically");require(bytes(source)==baseline,"Namespace remap never mutates source archive");
                evidence.append(QJsonObject{{"fixture",wanted["fixture"]},{"source_sha256",wanted["source_sha256"]},{"copied",copied},{"passed",true}});
            }
        }
    }
    QDir fixtures(QStringLiteral(OM9_REMAP_FROZEN)+"/rhino5-standalone-reference-20261008");auto wanted=QJsonDocument::fromJson(bytes(fixtures.filePath("oracle.json"))).object()["cases"].toArray()[0].toObject();auto objects=wanted["objects"].toArray();auto owner=objects[0].toObject()["uuid"].toString(),root=objects[1].toObject()["uuid"].toString();auto inv=inspectArchive(std::filesystem::path(fixtures.filePath(wanted["fixture"].toString()).toStdWString()));auto component=ON_ModelGeometryComponent::Cast(inv.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(root.toLatin1().constData())).ModelComponent());auto source=ON_PolyEdgeCurve::Cast(component->Geometry(nullptr));require(source,"Independent native remap negative controls");
    std::map<QString,ON_UUID> aliases{{owner,ON_UuidFromString(alias(owner,ns2).toLatin1().constData())}};
    for(int kind=0;kind<4;++kind){auto copy=std::unique_ptr<ON_Curve>(ON_Curve::Cast(source->Duplicate()));auto map=aliases;NativeReferenceLimits limits;if(kind==0)map.clear();if(kind==1)map[owner]=ON_nil_uuid;if(kind==2)limits.nodes=0;if(kind==3)copy->SetUserString(L"OwnerIdentity",owner.toStdWString().c_str());auto before=nativeCurveTreeFields(*copy);bool rejected=false;try{remapDeferredNativeReferences(*copy,map,limits);}catch(const ExchangeError&){rejected=true;}require(rejected&&nativeCurveTreeFields(*copy)==before,"Missing/nil alias, work limit and opaque text refuse before native mutation");}
    ON_PolyCurve late;require(late.Append(ON_Curve::Cast(source->SegmentCurve(0)->Duplicate()))&&late.Append(ON_Curve::Cast(source->SegmentCurve(0)->Duplicate())),"Independent two-slot failure tree");static_cast<ON_PolyEdgeSegment*>(late.SegmentCurve(1))->m_object_id=ON_UuidFromString("00000000-0000-4000-8000-000000004002");auto before=nativeCurveTreeFields(late);bool rejected=false;try{remapDeferredNativeReferences(late,aliases);}catch(const ExchangeError&){rejected=true;}require(rejected&&nativeCurveTreeFields(late)==before,"Late missing owner does not partially remap earlier slot");
    auto graph=inv.nativeReferences->graphs.at(root);auto live=ON_Curve::Cast(graph->geometry.at(root).get());before=nativeCurveTreeFields(*live);rejected=false;try{remapDeferredNativeReferences(*live,aliases);}catch(const ExchangeError&){rejected=true;}require(rejected&&nativeCurveTreeFields(*live)==before&&live->PointAt(39).IsValid(),"Live proxy graph cannot be redirected through deferred-tree API");
    ONX_Model textModel;require(textModel.Read(std::filesystem::path(fixtures.filePath(wanted["fixture"].toString()).toStdWString()).c_str(),nullptr),"Independent attribute reference refusal fixture");auto textRoot=ON_ModelGeometryComponent::Cast(textModel.ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(root.toLatin1().constData())).ModelComponent());const_cast<ON_ModelGeometryComponent*>(textRoot)->ExclusiveAttributes()->SetUserString(L"OwnerIdentity",owner.toStdWString().c_str());auto textPath=temp.filePath("text-reference.3dm");require(textModel.Write(std::filesystem::path(textPath.toStdWString()).c_str(),5,nullptr),"Serialize opaque identity text fixture");auto textInput=inspectArchive(std::filesystem::path(textPath.toStdWString()));QJsonArray textSources,textSelected;
    for(auto ns:{ns1,ns2}){textSources.append(QJsonObject{{"namespace",ns},{"snapshot",textPath},{"archive_sha256",textInput.document["archive_sha256"]},{"scale_mm",1}});textSelected.append(QJsonObject{{"namespace",ns},{"source_uuid",root},{"host_id","root"},{"action","unchanged"}});}
    QFile protectedText(temp.filePath("opaque-protected.3dm"));require(protectedText.open(QIODevice::WriteOnly),"Protected opaque text destination");protectedText.write("keep-target");protectedText.close();rejected=false;try{writeGeometryStagingArchive(QJsonObject{{"schema_version",1},{"sources",textSources},{"selected",textSelected}},std::filesystem::path(protectedText.fileName().toStdWString()));}catch(const ExchangeError& e){rejected=std::string(e.what()).find("user text identity")!=std::string::npos;}require(rejected&&bytes(protectedText.fileName())=="keep-target","Opaque attribute identity cannot bind to old namespace or overwrite destination");
    require(evidence.size()==36,"Independent 18-fixture two-mode matrix completed");QFile report(QStringLiteral(OM9_REMAP_RESULTS));require(report.open(QIODevice::WriteOnly),"Write remap evidence");report.write(QJsonDocument(QJsonObject{{"ok",true},{"checks",checks},{"cases",evidence},{"negative_controls",7},{"scope","internal SDK80 current graph; public V5 incompatibility unchanged"}}).toJson());std::cout<<checks<<" reference remap checks passed\n";return 0;
}catch(const std::exception& e){std::cerr<<"Check "<<checks<<": "<<e.what()<<"\n";return 1;}}
