// SPDX-License-Identifier: LGPL-2.1-or-later
#include "EditSpecialTypes.h"
#include "ThreeDmExplode.h"
#include "RetainedArchive.h"
#include <Mod/Part/App/TopoShape.h>
#include <Mod/Part/App/TopoShapePy.h>
#include <App/DocumentObjectPy.h>
#include <Gui/Application.h>
#include <Gui/Document.h>
#include <Gui/ViewProvider.h>
#include <Inventor/actions/SoCallbackAction.h>
#include <Inventor/SoPrimitiveVertex.h>
#include <Inventor/nodes/SoAsciiText.h>
#include <Inventor/nodes/SoText2.h>
#include <Inventor/nodes/SoShape.h>
#include <Inventor/nodes/SoSwitch.h>
#include <QFile>
#include <QCryptographicHash>
#include <QFontDatabase>
#include <QTextLayout>
#include <QGlyphRun>
#include <QPainterPath>
#include <QRawFont>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QUuid>
#include <filesystem>
#include <sstream>
#include <set>
#include <map>
#include <cmath>
namespace {
using namespace OpenMatrix9Gui;using Ref=CurvePyRef;
// Keep detached source attributes alongside the immutable prepared geometry.
// Weak ownership keys never reuse borrowed PyObject addresses after cancel.
std::map<std::weak_ptr<CurvePyRef>,QJsonObject,std::owner_less<std::weak_ptr<CurvePyRef>>> metadata;
EditShape owned(PyObject* p){return std::make_shared<Ref>(p);}
std::string text(PyObject* p){const char* s=PyUnicode_AsUTF8(p);if(!s)throw std::runtime_error("Invalid annotation text");return s;}
std::string string(PyObject* p,const char* k){Ref v(PyObject_GetAttrString(p,k));return text(v.value);}
bool has(PyObject* p,const char* k){return PyObject_HasAttrString(p,k)==1;}
double number(PyObject* p,const char* k){Ref v(PyObject_GetAttrString(p,k));double d=PyFloat_AsDouble(v.value);if(PyErr_Occurred()||!std::isfinite(d))throw std::runtime_error("Invalid special-object parameter");return d;}
Ref vector(double x,double y,double z){Ref app(PyImport_ImportModule("FreeCAD"));return Ref(PyObject_CallMethod(app.value,"Vector","ddd",x,y,z));}
void append(PyObject* l,PyObject* p){if(PyList_Append(l,p)<0)throw std::runtime_error("Cannot collect special components");}
void set(PyObject* p,const char* k,PyObject* v){if(PyObject_SetAttrString(p,k,v)<0)throw std::runtime_error(std::string("Cannot assign special output: ")+k);}
void put(PyObject* d,const char* k,PyObject* v){if(PyDict_SetItemString(d,k,v)<0)throw std::runtime_error("Cannot prepare text payload");}
std::string proxyType(PyObject* p){if(!has(p,"Proxy"))return {};Ref proxy(PyObject_GetAttrString(p,"Proxy"));return proxy.value!=Py_None&&has(proxy.value,"Type")?string(proxy.value,"Type"):std::string{};}
EditShapes elements(PyObject* p,const char* k){Ref list(PyObject_GetAttrString(p,k));EditShapes out;for(Py_ssize_t i=0;i<PySequence_Size(list.value);++i)out.push_back(owned(PySequence_GetItem(list.value,i)));return out;}
bool block(PyObject* p){Ref app(PyImport_ImportModule("FreeCAD"));Ref answer(PyObject_CallMethod(p,"isDerivedFrom","s","App::Link"));return PyObject_IsTrue(answer.value)==1;}
Ref worldFrame(PyObject* p,unsigned depth=0){if(depth>64)throw std::runtime_error("Cyclic special-object parent hierarchy");Ref app(PyImport_ImportModule("FreeCAD"));if(has(p,"getGlobalPlacement")){Ref pl(PyObject_CallMethod(p,"getGlobalPlacement",nullptr));return Ref(PyObject_CallMethod(pl.value,"toMatrix",nullptr));}Ref local(PyObject_CallMethod(app.value,"Matrix",nullptr));if(has(p,"Placement")){Ref pl(PyObject_GetAttrString(p,"Placement"));local=Ref(PyObject_CallMethod(pl.value,"toMatrix",nullptr));}else if(has(p,"Position")){Ref pos(PyObject_GetAttrString(p,"Position")),rot(PyObject_CallMethod(app.value,"Rotation",nullptr)),pl(PyObject_CallMethod(app.value,"Placement","OO",pos.value,rot.value));local=Ref(PyObject_CallMethod(pl.value,"toMatrix",nullptr));}if(has(p,"TextFrame")){Ref tf(PyObject_GetAttrString(p,"TextFrame"));local=Ref(PyNumber_Multiply(local.value,tf.value));}if(has(p,"getParentGeoFeatureGroup")){Ref group(PyObject_CallMethod(p,"getParentGeoFeatureGroup",nullptr));if(group.value!=Py_None){auto parent=worldFrame(group.value,depth+1);return Ref(PyNumber_Multiply(parent.value,local.value));}}return local;}

void transform(EditShape& s,PyObject* matrix){if(isExplodedText(s->value)){Ref old(Py_NewRef(PyDict_GetItemString(s->value,"frame"))),next(PyNumber_Multiply(matrix,old.value));put(s->value,"frame",next.value);}else if(isEditMesh(s->value)){Ref transformed(PyObject_CallMethod(s->value,"transform","O",matrix));}else{Ref moved(PyObject_CallMethod(s->value,"transformShape","OO",matrix,Py_False));}}
EditShape label(const std::string& value,const std::string& font,double height,PyObject* frame){auto d=owned(PyDict_New());Ref t(PyUnicode_FromString(value.c_str())),f(PyUnicode_FromString(font.c_str())),h(PyFloat_FromDouble(height));put(d->value,"_om9_text",Py_True);put(d->value,"text",t.value);put(d->value,"font",f.value);put(d->value,"height",h.value);put(d->value,"frame",frame);return d;}
void line(EditShapes& out,PyObject* a,PyObject* b){Ref delta(PyNumber_Subtract(a,b));if(number(delta.value,"Length")<=1e-9)return;Ref part(PyImport_ImportModule("Part"));out.push_back(owned(PyObject_CallMethod(part.value,"makeLine","OO",a,b)));}
struct DimensionGraphics {
    std::set<std::array<double,6>> segments;
    void add(SoCallbackAction* action,const SoPrimitiveVertex* a,const SoPrimitiveVertex* b){
        SbVec3f p,q;action->getModelMatrix().multVecMatrix(a->getPoint(),p);action->getModelMatrix().multVecMatrix(b->getPoint(),q);
        std::array<double,3> start{p[0],p[1],p[2]},end{q[0],q[1],q[2]};if(end<start)std::swap(start,end);if(start==end)return;
        segments.insert({start[0],start[1],start[2],end[0],end[1],end[2]});
    }
};
EditShapes dimensionGraphics(PyObject* object){
    auto* native=static_cast<App::DocumentObjectPy*>(object)->getDocumentObjectPtr();auto* document=Gui::Application::Instance->getDocument(native->getDocument());auto* provider=document?document->getViewProvider(native):nullptr;
    if(!provider)throw std::runtime_error("Dimension graphics are unavailable; input preserved");DimensionGraphics data;SoCallbackAction action;
    auto prune=[](void*,SoCallbackAction*,const SoNode*){return SoCallbackAction::PRUNE;};action.addPreCallback(SoAsciiText::getClassTypeId(),prune,nullptr);action.addPreCallback(SoText2::getClassTypeId(),prune,nullptr);
    // Draft retains the analytic angular circle separately. Its Coin arc is
    // only a display polyline; collect arrows/extensions and use that circle.
    if(proxyType(object)=="AngularDimension"){const auto arc=SoType::fromName("SoBrepEdgeSet");if(!arc.isBad())action.addPreCallback(arc,prune,nullptr);}
    action.addLineSegmentCallback(SoShape::getClassTypeId(),[](void* data,SoCallbackAction* a,const SoPrimitiveVertex* p,const SoPrimitiveVertex* q){static_cast<DimensionGraphics*>(data)->add(a,p,q);},&data);
    // Filled native arrows have no Part shape. Retain their displayed wire
    // geometry using Coin's primitive tessellation rather than inventing symbols.
    action.addTriangleCallback(SoShape::getClassTypeId(),[](void* data,SoCallbackAction* a,const SoPrimitiveVertex* p,const SoPrimitiveVertex* q,const SoPrimitiveVertex* r){auto* d=static_cast<DimensionGraphics*>(data);d->add(a,p,q);d->add(a,q,r);d->add(a,r,p);},&data);
    auto* mode=provider->getDisplayMaskMode(provider->getActiveDisplayMode().c_str());
    if(!mode)throw std::runtime_error("Dimension display mode is unavailable; input preserved");
    action.apply(mode);EditShapes out;for(auto p:data.segments){auto a=vector(p[0],p[1],p[2]),b=vector(p[3],p[4],p[5]);line(out,a.value,b.value);}if(out.empty())throw std::runtime_error("Dimension has no visible explodable graphics");return out;
}
EditShapes annotation(PyObject* object){
    const auto type=proxyType(object);Ref view(PyObject_GetAttrString(object,"ViewObject"));auto frame=worldFrame(object);EditShapes out;
    if(has(view.value,"DisplayMode")&&string(view.value,"DisplayMode")=="Screen")throw std::runtime_error("View-dependent screen annotation cannot be detached without a fixed drawing plane; input preserved");
    if(type=="Label"){Ref proxy(PyObject_GetAttrString(view.value,"Proxy")),node(PyObject_GetAttrString(proxy.value,"textpos")),field(PyObject_GetAttrString(node.value,"translation")),v(PyObject_CallMethod(field.value,"getValue",nullptr)),xyz(PyObject_CallMethod(v.value,"getValue",nullptr)),app(PyImport_ImportModule("FreeCAD")),factory(PyObject_GetAttrString(app.value,"Vector")),base(PyObject_CallObject(factory.value,xyz.value)),own(PyObject_GetAttrString(object,"Placement")),rot(PyObject_GetAttrString(own.value,"Rotation")),pl(PyObject_CallMethod(app.value,"Placement","OO",base.value,rot.value)),m(PyObject_CallMethod(pl.value,"toMatrix",nullptr)),inv(PyObject_CallMethod(own.value,"inverse",nullptr)),im(PyObject_CallMethod(inv.value,"toMatrix",nullptr)),parent(PyNumber_Multiply(frame.value,im.value));frame=Ref(PyNumber_Multiply(parent.value,m.value));}

    if(has(object,"String")&&has(object,"FontFile")){
        const auto font=string(object,"FontFile");if(font.empty()||!std::filesystem::is_regular_file(std::filesystem::u8path(font)))throw std::runtime_error("Font source is missing; text input preserved");
        Ref source(PyObject_GetAttrString(object,"Shape"));out=elements(source.value,"Edges");
        if(has(object,"Placement")){Ref pl(PyObject_GetAttrString(object,"Placement")),inverse(PyObject_CallMethod(pl.value,"inverse",nullptr)),m(PyObject_CallMethod(inverse.value,"toMatrix",nullptr)),parent(PyNumber_Multiply(frame.value,m.value));for(auto& s:out)transform(s,parent.value);}return out;
    }
    if(type=="LinearDimension"||type=="Dimension"||type=="AngularDimension"){
        Ref proxy(PyObject_GetAttrString(view.value,"Proxy"));if(proxy.value==Py_None||!has(proxy.value,"coords")||(!has(proxy.value,"line")&&!has(proxy.value,"arc"))||!has(proxy.value,"string"))throw std::runtime_error("Dimension view data is unavailable; input preserved");
        out=dimensionGraphics(object);
        if(type=="AngularDimension"){const bool split=has(view.value,"DisplayMode")&&string(view.value,"DisplayMode")=="Screen";if(split){if(!has(proxy.value,"circle1")||!has(proxy.value,"circle2"))throw std::runtime_error("Angular dimension gap has no analytic arcs; input preserved");for(const char* key:{"circle1","circle2"}){Ref circle(PyObject_GetAttrString(proxy.value,key));out.push_back(owned(PyObject_CallMethod(circle.value,"copy",nullptr)));}}else{Ref circle(PyObject_GetAttrString(proxy.value,"circle"));out.push_back(owned(PyObject_CallMethod(circle.value,"copy",nullptr)));}for(const char* key:{"p1","p4"}){Ref a(PyObject_GetAttrString(proxy.value,key)),b(PyObject_GetAttrString(proxy.value,std::string(key)=="p1"?"p2":"p3"));line(out,a.value,b.value);}}
        Ref app(PyImport_ImportModule("FreeCAD")),base(PyObject_GetAttrString(proxy.value,"tbase")),textNode(PyObject_GetAttrString(proxy.value,"textpos")),rotationField(PyObject_GetAttrString(textNode.value,"rotation")),rotationValue(PyObject_CallMethod(rotationField.value,"getValue",nullptr)),q(has(proxy.value,"trot")?PyObject_GetAttrString(proxy.value,"trot"):PyObject_CallMethod(rotationValue.value,"getValue",nullptr)),factory(PyObject_GetAttrString(app.value,"Rotation")),rotation(PyObject_CallObject(factory.value,q.value)),placement(PyObject_CallMethod(app.value,"Placement","OO",base.value,rotation.value)),textFrame(PyObject_CallMethod(placement.value,"toMatrix",nullptr));
        // Draft's dimension data are in document coordinates; containing Part
        // contributes only its parent frame, not the annotation's local placement.
        Ref own(has(object,"Placement")?PyObject_GetAttrString(object,"Placement"):PyObject_CallMethod(app.value,"Placement",nullptr)),inv(PyObject_CallMethod(own.value,"inverse",nullptr)),im(PyObject_CallMethod(inv.value,"toMatrix",nullptr)),parent(PyNumber_Multiply(frame.value,im.value));for(auto& s:out)transform(s,parent.value);Ref tf(PyNumber_Multiply(parent.value,textFrame.value));
        const auto font=has(view.value,"FontName")?string(view.value,"FontName"):"Arial";if(!QFontDatabase::families().contains(QString::fromStdString(font),Qt::CaseInsensitive))throw std::runtime_error("Dimension source font is unavailable; input preserved");const double height=(has(view.value,"FontSize")?number(view.value,"FontSize"):3)*(has(view.value,"ScaleMultiplier")?number(view.value,"ScaleMultiplier"):1);auto payload=label(string(proxy.value,"string"),font,height,tf.value);Ref align(PyUnicode_FromString("Center"));put(payload->value,"justification",align.value);out.push_back(payload);return out;
    }
    Ref source(PyObject_GetAttrString(object,has(object,"LabelText")?"LabelText":"Text"));if(type=="Text"||type=="Label"){Ref proxy(PyObject_GetAttrString(view.value,"Proxy")),node(PyObject_GetAttrString(proxy.value,"text_wld")),field(PyObject_GetAttrString(node.value,"string"));source=Ref(PyObject_CallMethod(field.value,"getValues",nullptr));}QString content;
    if(PyUnicode_Check(source.value))content=QString::fromStdString(text(source.value));else for(Py_ssize_t i=0;i<PySequence_Size(source.value);++i){Ref t(PySequence_GetItem(source.value,i));if(i)content+='\n';content+=QString::fromStdString(text(t.value));}
    const auto family=has(view.value,"FontName")?QString::fromStdString(string(view.value,"FontName")):QString("Arial");if(!QFontDatabase::families().contains(family,Qt::CaseInsensitive))throw std::runtime_error("Requested native font family is unavailable; input preserved");const double height=(has(view.value,"FontSize")?number(view.value,"FontSize"):3)*(has(view.value,"ScaleMultiplier")?number(view.value,"ScaleMultiplier"):1);if(height<=0)throw std::runtime_error("Text height must be positive");
    const auto alignment=has(view.value,"Justification")?string(view.value,"Justification"):"Left";const double spacing=has(view.value,"LineSpacing")?number(view.value,"LineSpacing"):1;if(!std::isfinite(spacing)||spacing<=0)throw std::runtime_error("Invalid text line spacing");
    QFont font(family);font.setPixelSize(1000);content.replace('\n',QChar::LineSeparator);QTextLayout layout(content,font);layout.beginLayout();double y=0;while(true){auto l=layout.createLine();if(!l.isValid())break;l.setLineWidth(1e9);const double x=alignment=="Center"?-l.naturalTextWidth()/2:alignment=="Right"?-l.naturalTextWidth():0;l.setPosition(QPointF(x,y-l.ascent()));y+=1000*(type=="Label"?std::max(1.,spacing):spacing);}layout.endLayout();Ref part(PyImport_ImportModule("Part"));
    for(const auto& run:layout.glyphRuns()){auto glyphs=run.glyphIndexes();auto positions=run.positions();const auto raw=run.rawFont();for(qsizetype n=0;n<glyphs.size();++n){if(glyphs[n]==0)throw std::runtime_error("A glyph is missing; text input preserved");auto path=raw.pathForGlyph(glyphs[n]);path.translate(positions[n]);QPointF start,previous;auto v=[&](QPointF p){return vector(p.x()*height/1000,-p.y()*height/1000,0);};
        for(int i=0;i<path.elementCount();++i){auto e=path.elementAt(i);QPointF p(e.x,e.y);if(e.isMoveTo()){start=previous=p;continue;}if(e.isLineTo()){auto a=v(previous),b=v(p);line(out,a.value,b.value);previous=p;}else if(e.type==QPainterPath::CurveToElement){if(i+2>=path.elementCount())throw std::runtime_error("Invalid glyph contour");auto e2=path.elementAt(++i),e3=path.elementAt(++i);Ref poles(PyList_New(0));for(auto q:{previous,p,QPointF(e2.x,e2.y),QPointF(e3.x,e3.y)}){auto pole=v(q);append(poles.value,pole.value);}Ref curve(PyObject_CallMethod(part.value,"BezierCurve",nullptr)),made(PyObject_CallMethod(curve.value,"setPoles","O",poles.value));out.push_back(owned(PyObject_CallMethod(curve.value,"toShape",nullptr)));previous=QPointF(e3.x,e3.y);}}
    }}for(auto& s:out){transform(s,frame.value);if(has(view.value,"TextColor")){Ref color(PyObject_GetAttrString(view.value,"TextColor"));QJsonArray rgb;for(int k=0;k<3;++k){Ref item(PySequence_GetItem(color.value,k));rgb.append(PyFloat_AsDouble(item.value));}metadata[s]=QJsonObject{{"LineColor",rgb},{"role","text-contour"}};}}if(out.empty())throw std::runtime_error("Text has no explodable glyph contours");if(type=="Label"){auto parts=dimensionGraphics(object);auto global=worldFrame(object);Ref own(PyObject_GetAttrString(object,"Placement")),inv(PyObject_CallMethod(own.value,"inverse",nullptr)),im(PyObject_CallMethod(inv.value,"toMatrix",nullptr)),parent(PyNumber_Multiply(global.value,im.value));for(auto& part:parts){transform(part,parent.value);out.push_back(part);}}return out;
}
EditShapes archive(PyObject* object,bool allow){const auto cls=string(object,"OM9SourceClass");if((cls=="ON_InstanceRef"||cls=="ON_InstanceRef2")&&!allow)throw std::runtime_error("Explode menu preserves blocks; type Explode in CMD to expand");
    const auto verified=verifiedRetainedArchive(object);const auto& uuid=verified.sourceUuid;const auto& space=verified.importNamespace;const auto scale=verified.scaleMm;
    auto result=ThreeDm::explodeArchiveRecord(verified.archiveBytes,uuid,scale);if(std::abs(result.scaleMm-scale)>1e-10*std::max(1.,scale))throw std::runtime_error("Retained source unit scale mismatch");EditShapes out;Ref app(PyImport_ImportModule("FreeCAD"));
    for(const auto& c:result.components){if(auto shape=std::get_if<TopoDS_Shape>(&c.geometry))out.push_back(owned(new Part::TopoShapePy(new Part::TopoShape(*shape))));else if(auto m=std::get_if<ThreeDm::MeshData>(&c.geometry)){Ref module(PyImport_ImportModule("Mesh")),triangles(PyList_New(0));for(auto f:m->faces){auto triangle=[&](int i,int j,int k){Ref t(PyTuple_New(3));int ids[]={i,j,k};for(int n=0;n<3;++n){auto p=m->vertices.at(ids[n]);auto v=vector(p[0],p[1],p[2]);PyTuple_SET_ITEM(t.value,n,Py_NewRef(v.value));}append(triangles.value,t.value);};triangle(f[0],f[1],f[2]);if(f[3]!=f[2])triangle(f[0],f[2],f[3]);}out.push_back(owned(PyObject_CallMethod(module.value,"Mesh","O",triangles.value)));}else{const auto& t=std::get<ThreeDm::ExplodeText>(c.geometry);Ref frame(PyObject_CallMethod(app.value,"Matrix",nullptr));for(int i=0;i<4;++i)for(int j=0;j<4;++j){const auto key="A"+std::to_string(i+1)+std::to_string(j+1);Ref value(PyFloat_FromDouble(t.worldTransform[4*i+j]/(i<3&&j<3?result.scaleMm:1)));set(frame.value,key.c_str(),value.value);}out.push_back(label(t.text,t.fontFamily,t.heightMm,frame.value));}
        QJsonObject data{{"name",QString::fromStdString(c.name)},{"layer",QString::fromStdString(c.layer)},{"source_uuid",QString::fromStdString(c.sourceUuid)},{"source_class",QString::fromStdString(c.sourceClass)},{"role",QString::fromStdString(c.role)},{"visible",c.visible},{"locked",c.locked},{"color",QJsonArray{c.color[0],c.color[1],c.color[2]}},{"source_record_uuid",QString::fromStdString(uuid)},{"import_namespace",QString::fromStdString(space)},{"scale_mm",result.scaleMm}};
        if(c.cage){const auto& cage=*c.cage;QJsonArray counts,degrees,points,weights,knots;for(int i=0;i<3;++i){counts.append(cage.counts[i]);degrees.append(cage.degrees[i]);QJsonArray row;for(auto value:cage.knots[i])row.append(value);knots.append(row);}for(auto p:cage.points)points.append(QJsonArray{p[0],p[1],p[2]});for(auto value:cage.weights)weights.append(value);data.insert("cage",QJsonObject{{"counts",counts},{"degrees",degrees},{"control_points_mm",points},{"weights",weights},{"knots",knots}});}
        metadata[out.back()]=data;
    }
    return out;
}
}
namespace OpenMatrix9Gui {
bool isExplodedText(PyObject* p){return PyDict_Check(p)&&PyDict_GetItemString(p,"_om9_text");}
void transformExplodedText(PyObject* p,PyObject* matrix){Ref frame(PyNumber_Multiply(matrix,PyDict_GetItemString(p,"frame")));put(p,"frame",frame.value);}
bool specialExplodeSource(PyObject* p){const auto t=proxyType(p);return block(p)||has(p,"OM9CageComponents")||has(p,"OM9SourceUUID")&&has(p,"OM9Capability")&&string(p,"OM9Capability")!="editable"||has(p,"String")&&has(p,"FontFile")||t=="Text"||t=="Label"||t=="Dimension"||t=="LinearDimension"||t=="AngularDimension"||has(p,"LabelText");}
EditShapes specialExplodeComponents(PyObject* p,bool allow){
    for(auto it=metadata.begin();it!=metadata.end();)if(it->first.expired())it=metadata.erase(it);else ++it;
    if(has(p,"OM9SourceUUID")&&has(p,"OM9Capability")&&string(p,"OM9Capability")!="editable")return archive(p,allow);
    if(block(p)){if(!allow)throw std::runtime_error("Explode menu preserves blocks; type Explode in CMD to expand");EditShapes out;std::set<PyObject*> ancestry;
        auto visit=[&](auto&& self,PyObject* object,const std::string& path,unsigned depth)->void{if(depth>64||!ancestry.insert(object).second)throw std::runtime_error("Cyclic or excessively nested block definition");Ref target(block(object)?PyObject_CallMethod(object,"getLinkedObject","O",Py_True):Py_NewRef(object));if(has(target.value,"Group")){Ref children(PyObject_GetAttrString(target.value,"Group"));for(Py_ssize_t i=0;i<PySequence_Size(children.value);++i){Ref child(PySequence_GetItem(children.value,i));self(self,child.value,path+string(child.value,"Name")+".",depth+1);}}else if(block(target.value))self(self,target.value,path,depth+1);else if(specialExplodeSource(target.value)){auto pieces=specialExplodeComponents(target.value,true);auto sourceFrame=worldFrame(target.value);Ref inverse(PyObject_CallMethod(sourceFrame.value,"inverse",nullptr)),instance(PyObject_CallMethod(p,"getSubObject","si",path.c_str(),4)),delta(PyNumber_Multiply(instance.value,inverse.value));for(auto& piece:pieces){transform(piece,delta.value);out.push_back(piece);}}else{Ref geometry(PyObject_CallMethod(p,"getSubObject","s",path.c_str()));if(geometry.value==Py_None)throw std::runtime_error("Missing block member geometry");if(!has(geometry.value,"ShapeType")&&!isEditMesh(geometry.value))throw std::runtime_error("Block member requires an annotation/control adapter");out.push_back(owned(Py_NewRef(geometry.value)));QJsonObject data{{"name",QString::fromStdString(string(target.value,"Label"))},{"native_source",QString::fromStdString(string(target.value,"Name"))}};Ref view(PyObject_GetAttrString(target.value,"ViewObject"));for(const auto* key:{"ShapeColor","LineColor","PointColor"})if(has(view.value,key)){Ref color(PyObject_GetAttrString(view.value,key));QJsonArray row;for(int k=0;k<3;++k){Ref item(PySequence_GetItem(color.value,k));row.append(PyFloat_AsDouble(item.value));}data.insert(key,row);}for(const auto* key:{"Transparency","LineWidth","PointSize"})if(has(view.value,key))data.insert(key,number(view.value,key));metadata[out.back()]=data;}ancestry.erase(object);};visit(visit,p,"",0);if(out.empty())throw std::runtime_error("Block definition has no embedded components");auto global=worldFrame(p);Ref local(PyObject_GetAttrString(p,"Placement")),inv(PyObject_CallMethod(local.value,"inverse",nullptr)),m(PyObject_CallMethod(inv.value,"toMatrix",nullptr)),parent(PyNumber_Multiply(global.value,m.value));for(auto& component:out)transform(component,parent.value);return out;
    }
    if(has(p,"OM9CageComponents")){Ref children(PyObject_GetAttrString(p,"OM9CageComponents")),doc(PyObject_GetAttrString(p,"Document"));EditShapes out;for(Py_ssize_t i=0;i<PySequence_Size(children.value);++i){Ref child(PySequence_GetItem(children.value,i)),cdoc(PyObject_GetAttrString(child.value,"Document"));if(cdoc.value!=doc.value||child.value==p||!has(child.value,"Shape"))throw std::runtime_error("Invalid native cage component link");Ref shape(PyObject_GetAttrString(child.value,"Shape"));auto copy=owned(PyObject_CallMethod(shape.value,"copy",nullptr));auto global=worldFrame(child.value);Ref local(PyObject_GetAttrString(child.value,"Placement")),inv(PyObject_CallMethod(local.value,"inverse",nullptr)),m(PyObject_CallMethod(inv.value,"toMatrix",nullptr)),parent(PyNumber_Multiply(global.value,m.value));transform(copy,parent.value);out.push_back(copy);}if(out.empty())throw std::runtime_error("Native cage has no control components");return out;}
    return annotation(p);
}
EditShape specialExplodePreview(const EditShapes& parts){Ref module(PyImport_ImportModule("Part")),list(PyList_New(0));for(const auto& s:parts)if(!isExplodedText(s->value)&&!isEditMesh(s->value))append(list.value,s->value);if(PyList_Size(list.value))return owned(PyObject_CallMethod(module.value,"makeCompound","O",list.value));for(const auto& s:parts)if(isEditMesh(s->value))return s;throw std::runtime_error("Special object has no drawable components");}
std::string specialExplodeSignature(PyObject* p){auto parts=specialExplodeComponents(p,true);std::ostringstream out;out<<std::hexfloat;auto parameters=[&](PyObject* o,std::initializer_list<const char*> keys){for(const auto* key:keys)if(has(o,key)){Ref value(PyObject_GetAttrString(o,key)),r(PyObject_Repr(value.value));out<<key<<'='<<text(r.value)<<';';}};parameters(p,{"String","FontFile","Text","LabelText","TextFrame","Placement","OM9SourceUUID","OM9ImportNamespace","OM9SourceClass","OM9Capability","OM9CageComponents"});Ref view(PyObject_GetAttrString(p,"ViewObject"));parameters(view.value,{"FontName","FontSize","ScaleMultiplier","Justification","LineSpacing","TextAlignment","MaxChars","DisplayMode","TextColor","LineColor","Frame","Line","ArrowTypeStart","ArrowTypeEnd","ArrowSizeStart","ArrowSizeEnd"});for(const auto& s:parts){if(isExplodedText(s->value)){for(const char* k:{"text","font","height"}){Ref r(PyObject_Repr(PyDict_GetItemString(s->value,k)));out<<text(r.value)<<';';}auto* matrix=PyDict_GetItemString(s->value,"frame");for(int i=1;i<=4;++i)for(int j=1;j<=4;++j)out<<number(matrix,("A"+std::to_string(i)+std::to_string(j)).c_str())<<';';}else if(isEditMesh(s->value))out<<editMeshSignature(s->value);else{Ref b(PyObject_CallMethod(s->value,"exportBrepToString",nullptr));out<<text(b.value);}}return out.str();}
void applyExplodeMetadata(PyObject* object,const EditShape& component){auto it=metadata.find(component);if(it==metadata.end())return;const auto& d=it->second;Ref prop(PyObject_CallMethod(object,"addProperty","sss","App::PropertyString","ExplodeSourceMetadata","Explode")),json(PyUnicode_FromString(QJsonDocument(d).toJson(QJsonDocument::Compact).constData()));set(object,"ExplodeSourceMetadata",json.value);Ref readonly(PyObject_CallMethod(object,"setEditorMode","si","ExplodeSourceMetadata",1));Ref title(PyUnicode_FromString(d.value("name").toString().toUtf8().constData()));if(!d.value("name").toString().isEmpty())set(object,"Label",title.value);Ref view(PyObject_GetAttrString(object,"ViewObject"));if(d.contains("color")){const auto color=d.value("color").toArray();Ref rgb(Py_BuildValue("(ddd)",color[0].toInt()/255.,color[1].toInt()/255.,color[2].toInt()/255.));for(const char* key:{"ShapeColor","LineColor","TextColor"})if(has(view.value,key))set(view.value,key,rgb.value);}for(const auto* key:{"ShapeColor","LineColor","PointColor"})if(d.contains(key)&&has(view.value,key)){auto color=d.value(key).toArray();Ref rgb(Py_BuildValue("(ddd)",color[0].toDouble(),color[1].toDouble(),color[2].toDouble()));set(view.value,key,rgb.value);}for(const auto* key:{"Transparency","LineWidth","PointSize"})if(d.contains(key)&&has(view.value,key)){Ref v(std::string(key)=="Transparency"?PyLong_FromLong(d.value(key).toInt()):PyFloat_FromDouble(d.value(key).toDouble()));set(view.value,key,v.value);}if(d.contains("visible"))set(view.value,"Visibility",d.value("visible").toBool()?Py_True:Py_False);if(d.value("locked").toBool()&&has(view.value,"Selectable"))set(view.value,"Selectable",Py_False);}
CurvePyRef createExplodedText(PyObject* doc,PyObject* payload){Ref object(PyObject_CallMethod(doc,"addObject","ss","OpenMatrix9Gui::ExplodedText","ExplodedDimensionText")),list(PyList_New(0));append(list.value,PyDict_GetItemString(payload,"text"));set(object.value,"LabelText",list.value);set(object.value,"TextFrame",PyDict_GetItemString(payload,"frame"));Ref view(PyObject_GetAttrString(object.value,"ViewObject"));set(view.value,"FontName",PyDict_GetItemString(payload,"font"));set(view.value,"FontSize",PyDict_GetItemString(payload,"height"));Ref mode(PyUnicode_FromString("World"));set(view.value,"DisplayMode",mode.value);if(auto* align=PyDict_GetItemString(payload,"justification"))set(view.value,"Justification",align);return object;}
}
