#include "ThreeDmInventory.h"
#include "ThreeDmCurveOnSurface.h"
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>
#include <QCryptographicHash>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static int checks=0;
static void require(bool value,const char* text){++checks;if(!value)throw ExchangeError(text);}
static QByteArray bytes(QString path){QFile f(path);require(f.open(QIODevice::ReadOnly),"Read frozen actual target bytes");return f.readAll();}
static QString sha(QString path){return QString::fromLatin1(QCryptographicHash::hash(bytes(path),QCryptographicHash::Sha256).toHex());}
int main(){try{ON::Begin();QDir root(QStringLiteral(OM9_SEAM_RHINO));auto oracle=QJsonDocument::fromJson(bytes(root.filePath("oracle.json"))).object(),actual=QJsonDocument::fromJson(bytes(root.filePath("rhino5-gui-profile-results.json"))).object();require(actual["ok"].toBool()&&actual["cases"].toArray().size()==8&&oracle["cases"].toArray().size()==8,"Actual eight-case GUI completion");require(actual["oracle_sha256"]==sha(root.filePath("oracle.json"))&&actual["probe_sha256"]==sha(root.filePath("rhino5-seam-profiles-probe.py")),"Actual target binds independent oracle and probe");QJsonArray cases;
    for(int i=0;i<8;++i){auto wanted=oracle["cases"].toArray()[i].toObject(),row=actual["cases"].toArray()[i].toObject();auto source=root.filePath(row["fixture"].toString()),saved=root.filePath(QFileInfo(row["saved_fixture"].toString()).fileName());require(row["fixture"]==wanted["fixture"]&&row["passed"].toBool()&&row["bad_objects"].toInt()==0&&row["source_unchanged"].toBool(),"Actual GUI source/read/SaveAs/reread passed with no bad objects");require(sha(source)==wanted["source_sha256"]&&row["source_sha256"]==wanted["source_sha256"]&&sha(saved)==row["saved_sha256"],"Original and actual saved bytes bound");auto before=inspectArchive(std::filesystem::path(source.toStdWString())),after=inspectArchive(std::filesystem::path(saved.toStdWString()));require(before.document["issues"].toArray().isEmpty()&&after.document["issues"].toArray().isEmpty()&&after.document["source_version"]==50&&after.document["records"].toArray().size()==1,"Complete target graph decoded in pinned SDK");auto a=before.document["records"].toArray()[0].toObject(),b=after.document["records"].toArray()[0].toObject();auto expected=wanted["objects"].toArray()[0].toObject();require(a["source_uuid"]==b["source_uuid"]&&b["source_uuid"]==expected["uuid"]&&a["class_name"]=="ON_CurveOnSurface"&&b["class_name"]==a["class_name"]&&a["curve_on_surface_native"]==b["curve_on_surface_native"]&&b["curve_on_surface_native"]==wanted["native_fields"]&&a["geometry_crc"]==b["geometry_crc"],"Exact native UUID/class/UV/surface/domain/reversal/metadata/graph CRC after actual SaveAs");auto uuid=b["source_uuid"].toString();auto component=ON_ModelGeometryComponent::Cast(after.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(uuid.toLatin1().constData())).ModelComponent());auto curve=component?ON_CurveOnSurface::Cast(component->Geometry(nullptr)):nullptr;require(curve&&curve->IsValid()&&!curve->m_c3,"No optional child added or substituted");auto samples=expected["samples"].toArray();for(int j=0;j<17;++j){auto point=samples[j].toArray();require(curve->PointAt(31+j).DistanceTo(ON_3dPoint(point[0].toDouble(),point[1].toDouble(),point[2].toDouble()))<=1e-12,"Actual target native analytic seam/pole/closed-circle interior samples");}
        cases.append(QJsonObject{{"fixture",wanted["fixture"]},{"source_sha256",wanted["source_sha256"]},{"saved_sha256",row["saved_sha256"]},{"native_fields",b["curve_on_surface_native"]},{"passed",true}});
    }
    QFile result(QStringLiteral(OM9_SEAM_RHINO_RESULTS));require(result.open(QIODevice::WriteOnly),"Write native actual-target evidence");auto reportHash=sha(root.filePath("rhino5-gui-profile-results.json"));result.write(QJsonDocument(QJsonObject{{"ok",true},{"checks",checks},{"rhino_report_sha256",reportHash},{"cases",cases}}).toJson());std::cout<<checks<<" actual seam target checks passed\n";return 0;
}catch(const std::exception& e){std::cerr<<"Check "<<checks<<": "<<e.what()<<"\n";return 1;}}
