// Named SDK2013 oracle with a declared child Read correction, not the pristine reader.
#include "opennurbs.h"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <stdexcept>
#include <cmath>
static void require(bool v,const char* m){if(!v)throw std::runtime_error(m);}
static void text(std::ostream& out,const char* value){out<<'"';for(auto p=value;p&&*p;++p){unsigned char c=*p;if(c=='"'||c=='\\')out<<'\\'<<c;else if(c<32)out<<"\\u00"<<std::hex<<std::setw(2)<<std::setfill('0')<<int(c)<<std::dec;else out<<c;}out<<'"';}
static void text(std::ostream& out,const ON_wString& v){ON_String utf8(v);text(out,utf8.Array());}
static void strings(std::ostream& out,const ON_Object& o){ON_ClassArray<ON_UserString> values;o.GetUserStrings(values);out<<'[';for(int i=0;i<values.Count();++i){if(i)out<<',';out<<"{\"key\":";text(out,values[i].m_key);out<<",\"value\":";text(out,values[i].m_string_value);out<<'}';}out<<']';}
static void number(std::ostream& out,double v){require(std::isfinite(v),"Nonfinite legacy field");out<<v;}
static void arc(std::ostream& out,const ON_Curve* c){if(!c){out<<"null";return;}auto a=ON_ArcCurve::Cast(c);require(a&&a->IsValid(),"Named oracle requires native Arc child");out<<"{\"class_name\":\"ON_ArcCurve\",\"dimension\":"<<a->Dimension()<<",\"domain\":[";number(out,a->Domain()[0]);out<<',';number(out,a->Domain()[1]);out<<"],\"radius\":";number(out,a->m_arc.radius);out<<",\"plane\":[";bool first=true;auto p=a->m_arc.plane;for(auto v:{p.origin,ON_3dPoint(p.xaxis),ON_3dPoint(p.yaxis),ON_3dPoint(p.zaxis)})for(int i=0;i<3;++i){if(!first)out<<',';first=false;number(out,v[i]);}for(double v:{p.plane_equation.x,p.plane_equation.y,p.plane_equation.z,p.plane_equation.d}){out<<',';number(out,v);}out<<"],\"angle_domain\":[";number(out,a->m_arc.Domain()[0]);out<<',';number(out,a->m_arc.Domain()[1]);out<<"],\"user_strings\":";strings(out,*a);out<<'}';}
static void surface(std::ostream& out,const ON_Surface* s){auto n=ON_NurbsSurface::Cast(s);require(n&&n->IsValid(),"Named oracle requires native NURBS surface");out<<"{\"class_name\":\"ON_NurbsSurface\",\"dimension\":"<<n->Dimension()<<",\"rational\":"<<(n->IsRational()?"true":"false")<<",\"orders\":["<<n->Order(0)<<','<<n->Order(1)<<"],\"domains\":[";for(int d=0;d<2;++d){if(d)out<<',';out<<'[';number(out,n->Domain(d)[0]);out<<',';number(out,n->Domain(d)[1]);out<<']';}out<<"],\"knots\":[";for(int d=0;d<2;++d){if(d)out<<',';out<<'[';for(int i=0;i<n->KnotCount(d);++i){if(i)out<<',';number(out,n->Knot(d,i));}out<<']';}out<<"],\"cvs\":[";for(int i=0;i<n->CVCount(0);++i){if(i)out<<',';out<<'[';for(int j=0;j<n->CVCount(1);++j){if(j)out<<',';out<<'[';for(int k=0;k<n->CVSize();++k){if(k)out<<',';number(out,n->CV(i,j)[k]);}out<<']';}out<<']';}out<<"],\"user_strings\":";strings(out,*n);out<<'}';}
int main(int argc,char** argv){try{
    require(argc==4,"usage: CurveOnSurfaceLegacyReader input output report");ON::Begin();require(ON::Version()==201307115,"Unexpected legacy SDK revision");auto input=std::filesystem::u8path(argv[1]),output=std::filesystem::u8path(argv[2]),reportPath=std::filesystem::u8path(argv[3]);require(std::filesystem::file_size(input)<=512ULL*1024*1024&&!std::filesystem::exists(output)&&!std::filesystem::exists(reportPath),"Bounded input and fresh outputs required");
    ONX_Model model;require(model.Read(input.c_str(),nullptr)&&model.m_3dm_file_version==50,"Read native version5 model");std::ofstream report(reportPath,std::ios::binary);report.imbue(std::locale::classic());report<<std::setprecision(17)<<"{\"sdk_version\":201307115,\"source_version\":50,\"read_repair\":\"OM9 CurveOnSurface::Read only\",\"curves\":[";bool first=true;int count=0;
    for(int i=0;i<model.m_object_table.Count();++i){auto& entry=model.m_object_table[i];auto c=ON_CurveOnSurface::Cast(entry.m_object);if(!c)continue;require(c->IsValid()&&c->IsClosed(),"Valid closed surface curve");if(!first)report<<',';first=false;++count;char id[37]{};ON_UuidToString(entry.m_attributes.m_uuid,id);report<<"{\"uuid\":";text(report,id);report<<",\"class_name\":\"ON_CurveOnSurface\",\"dimension\":"<<c->Dimension()<<",\"parameter\":";arc(report,c->m_c2);report<<",\"approximation\":";arc(report,c->m_c3);report<<",\"surface\":";surface(report,c->m_s);report<<",\"samples\":[";bool sampleFirst=true;for(double t:{11.,12.125,17.,22.75,23.}){if(!sampleFirst)report<<',';sampleFirst=false;auto p=c->PointAt(t);report<<'[';for(int j=0;j<3;++j){if(j)report<<',';number(report,p[j]);}report<<']';}report<<"],\"user_strings\":";strings(report,*c);report<<'}';}
    require(count>0,"No named CurveOnSurface source decoded");report<<"]}\n";require(report.good(),"Report write");require(model.Write(output.c_str(),5,"OM9 SDK2013 named CurveOnSurface repaired reader",nullptr),"Independent legacy reencode");std::cout<<"SDK201307115 declared child Read repair: "<<count<<" exact native curves\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
