#include "ThreeDmInventory.h"
#include "ThreeDmNativeReferences.h"
#include "ThreeDmCurveOnSurface.h"
#include "opennurbs_polyedgecurve.h"
#include <QFile>
#include <QDir>
#include <QFileInfo>
#include <QTemporaryDir>
#include <QCryptographicHash>
#include <QJsonDocument>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static int checks=0;
static void require(bool v,const char* text){++checks;if(!v)throw ExchangeError(text);}
static QJsonObject json(QString path){QFile f(path);require(f.open(QIODevice::ReadOnly),"Read frozen mixed oracle/report");return QJsonDocument::fromJson(f.readAll()).object();}
static QString sha(QString path){QFile f(path);require(f.open(QIODevice::ReadOnly),"Read bound source bytes");return QString::fromLatin1(QCryptographicHash::hash(f.readAll(),QCryptographicHash::Sha256).toHex());}
static QJsonObject record(const ArchiveInventory& inv,QString uuid){for(auto v:inv.document["records"].toArray())if(v.toObject()["source_uuid"]==uuid)return v.toObject();throw ExchangeError("Missing mixed root UUID");}
static const ON_Curve* rootCurve(const ONX_Model& model,QString uuid){auto c=ON_ModelGeometryComponent::Cast(model.ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ON_UuidFromString(uuid.toLatin1().constData())).ModelComponent());return c?ON_Curve::Cast(c->Geometry(nullptr)):nullptr;}
int main(){try{ON::Begin();QDir root(QStringLiteral(OM9_MIXED_FROZEN));auto oracle=json(root.filePath("oracle.json")),actual=json(root.filePath("rhino5-gui-profile-results.json"));auto cases=oracle["cases"].toArray(),measured=actual["cases"].toArray();
    require(cases.size()==6&&measured.size()==6&&!actual["ok"].toBool(),"Actual six-case target failure, no script abort");
    require(sha(root.filePath("oracle.json"))==actual["oracle_sha256"]&&sha(root.filePath("rhino5-mixed-reference-gui-probe.py"))==actual["probe_sha256"],"Target report binds independent oracle/probe");
    QJsonArray decoded;
    for(int i=0;i<6;++i){auto wanted=cases[i].toObject(),row=measured[i].toObject();auto uuid=wanted["objects"].toArray()[1].toObject()["uuid"].toString();auto saved=root.filePath(QFileInfo(row["saved_fixture"].toString()).fileName());ONX_Model model;require(model.Read(std::filesystem::path(saved.toStdWString()).c_str(),nullptr),"Decode actual Rhino SaveAs");auto c=rootCurve(model,uuid);require(c,"Saved UUID exists");decoded.append(QJsonObject{{"fixture",wanted["fixture"]},{"saved_class",c->ClassId()->ClassName()},{"source_fields",wanted["native_reference_fields"]},{"saved_fields",nativeCurveTreeFields(*c)}});}
    QFile decode(QStringLiteral(OM9_MIXED_RESULTS)+".decoded.json");require(decode.open(QIODevice::WriteOnly),"Write complete native decode before testing adapter");decode.write(QJsonDocument(QJsonObject{{"cases",decoded}}).toJson());decode.close();
    QJsonArray evidence;
    for(int i=0;i<6;++i){auto wanted=cases[i].toObject(),target=measured[i].toObject();auto uuid=wanted["objects"].toArray()[1].toObject()["uuid"].toString(),owner=wanted["objects"].toArray()[0].toObject()["uuid"].toString();auto original=root.filePath(wanted["fixture"].toString()),saved=root.filePath(QFileInfo(target["saved_fixture"].toString()).fileName());
        require(wanted["fixture"]==target["fixture"]&&sha(original)==wanted["source_sha256"]&&wanted["source_sha256"]==target["source_sha256"]&&sha(saved)==target["saved_sha256"],"Original and actual saved bytes bound");
        for(auto phase:{"first_read","reread"}){bool invalid=false,ownerValid=false;for(auto v:target[phase].toObject()["objects"].toArray()){auto obj=v.toObject();if(obj["uuid"]==uuid){invalid=!obj["valid"].toBool()&&obj["samples"].toArray().size()==17;for(auto p:obj["samples"].toArray())for(auto x:p.toArray())invalid=invalid&&x.toDouble()==ON_UNSET_VALUE;for(auto valid:obj["sample_validity"].toArray())invalid=invalid&&!valid.toBool();}if(obj["uuid"]==owner)ownerValid=obj["valid"].toBool();}require(invalid&&ownerValid&&target["bad_objects"].toInt()==1,"Actual invalid parent with valid owner; not tolerance discrepancy");}
        for(auto file:{original,saved}){auto inv=inspectArchive(std::filesystem::path(file.toStdWString()));auto row=record(inv,uuid);auto source=rootCurve(*inv.nativeModel,uuid);require(source&&source->ClassId()==&ON_CLASS_RTTI(ON_PolyCurve),"Native parent class retained");auto fields=nativeCurveTreeFields(*source);auto crc=source->DataCRC(0);
            auto expected=wanted["native_reference_fields"].toObject();auto children=expected["segments"].toArray();auto wrapper=children[0].toObject();auto segment=wrapper["segments"].toArray()[0].toObject();const bool lostDirection=segment["reversed"].toBool();
            if(file==saved){segment["reversed"]=false;children[0]=segment;expected["segments"]=children;}
            require(fields==expected,"Exact observed SaveAs child flattening, wrapper metadata loss and reversal loss; remaining fields match");
            require(row["poly_edge_native"].toObject()==fields&&row["capability"]=="retained"&&row["dependencies"].toArray().contains(owner),"Mixed parent typed inventory retains native tree and owner closure");
            if(file==saved&&lostDirection){require(row["native_reference_analysis"].toObject()["status"]=="invalid"&&!inv.nativeReferences->graphs.contains(uuid)&&!inv.document["issues"].toArray().isEmpty(),"Saved reversal loss creates a disconnected parent; reject graph rather than pretend repaired equivalence");require(source->DataCRC(0)==crc,"Corrupted target snapshot remains immutable");continue;}
            require(row["native_reference_analysis"].toObject()["status"]=="linked"&&inv.document["issues"].toArray().isEmpty(),"Mixed reference graph resolves without mutating deferred source");auto graph=inv.nativeReferences->graphs.at(uuid);auto live=ON_Curve::Cast(graph->geometry.at(uuid).get());require(live&&live->IsValid()&&live->ClassId()==source->ClassId(),"Class-preserving native parent owner/lifetime");
            if(file==original){require(fields==wanted["native_reference_fields"],"Original decoded fields exact");auto points=wanted["objects"].toArray()[1].toObject()["samples"].toArray();for(int j=0;j<17;++j){auto p=points[j].toArray();require(live->PointAt(31+2*j).DistanceTo(ON_3dPoint(p[0].toDouble(),p[1].toDouble(),p[2].toDouble()))<=1e-12,"Independent parent interior/joint/line samples");}}
            require(source->DataCRC(0)==crc,"Source fields remain immutable");auto publicRead=readArchive(std::filesystem::path(file.toStdWString()),1,true);bool retained=false;for(auto& item:publicRead.items)if(item.sourceUuid==uuid.toStdString())retained=item.retained;require(retained,"Public reader retains mixed parent rather than aborting or editing unresolved curve");
            QTemporaryDir temp;require(temp.isValid(),"Owned protected destination folder");QFile protectedFile(temp.filePath("protected.3dm"));require(protectedFile.open(QIODevice::WriteOnly),"Prepare protected destination");protectedFile.write("unchanged-target");protectedFile.close();bool refused=false;try{writeModelRhino5(*inv.nativeModel,std::filesystem::path(protectedFile.fileName().toStdWString()));}catch(const ExchangeError& e){refused=std::string(e.what()).find("nested PolyEdge")!=std::string::npos;}require(refused,"Common writer refuses nested PolyEdge before opening target");require(protectedFile.open(QIODevice::ReadOnly)&&protectedFile.readAll()=="unchanged-target","Nested V5 refusal atomic");protectedFile.close();inv=ArchiveInventory{};require(live->PointAt(55).IsValid()&&graph->source,"Graph lifetime after inventory release");
        }
        evidence.append(QJsonObject{{"fixture",wanted["fixture"]},{"native_original_mapping",true},{"rhino5_invalid_parent",true},{"preservation_retained",true},{"v5_refused_atomically",true}});
    }
    QTemporaryDir malformed;require(malformed.isValid(),"Owned malformed fixture directory");auto first=cases[0].toObject();auto uuid=first["objects"].toArray()[1].toObject()["uuid"].toString();
    for(int kind=0;kind<3;++kind){ONX_Model model;require(model.Read(std::filesystem::path(root.filePath(first["fixture"].toString()).toStdWString()).c_str(),nullptr),"Independent source for invalid nested owner");auto poly=ON_PolyCurve::Cast(const_cast<ON_Curve*>(rootCurve(model,uuid)));auto ref=ON_PolyEdgeCurve::Cast(poly->SegmentCurve(0));auto segment=ref->SegmentCurve(0);segment->m_object_id=kind==0?ON_nil_uuid:kind==1?ON_UuidFromString("00000000-0000-4000-8000-000000002902"):ON_UuidFromString(uuid.toLatin1().constData());auto path=std::filesystem::path(malformed.filePath(QString("invalid-%1.3dm").arg(kind)).toStdWString());require(model.Write(path.c_str(),5,nullptr),"Serialize malformed reference directly for negative control");auto inv=inspectArchive(path);require(record(inv,uuid)["native_reference_analysis"].toObject()["status"]=="invalid"&&!inv.nativeReferences->graphs.contains(uuid)&&!inv.document["issues"].toArray().isEmpty(),"Nil/missing/cyclic nested owners rejected without exposing partial graph");}
    auto bounded=inspectArchive(std::filesystem::path(root.filePath(first["fixture"].toString()).toStdWString()));NativeReferenceLimits limits;limits.nodes=0;auto limited=resolveNativeReferences(bounded.nativeModel,bounded.document["records"].toArray(),limits);require(limited->diagnostics[uuid].toObject()["status"]=="limit"&&limited->graphs.empty(),"Nested parent obeys aggregate graph node budget");
    ON_PolyCurve plain;require(plain.Append(new ON_LineCurve(ON_3dPoint(0,0,0),ON_3dPoint(1,0,0)))&&plain.Append(new ON_LineCurve(ON_3dPoint(1,0,0),ON_3dPoint(2,0,0))),"Independent ordinary polycurve control");require(nativeGeometryFacts(plain).isEmpty(),"Ordinary owned polycurve remains outside reference retention and rejection");
    ONX_Model ordinary;ordinary.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);ON_Layer layer;layer.SetName(L"Ordinary polycurve control");ordinary.AddModelComponent(layer);require(!ordinary.AddModelGeometryComponent(&plain,nullptr).IsEmpty(),"Independent ordinary model");auto positive=std::filesystem::path(malformed.filePath("ordinary.3dm").toStdWString());require(writeModelRhino5(ordinary,positive),"Ordinary owned polycurve public writer remains available");auto ordinaryRead=readArchive(positive);require(ordinaryRead.items.size()==1&&!ordinaryRead.items[0].retained,"Ordinary polycurve public geometry reader remains editable");
    std::unique_ptr<ON_Curve> deep(new ON_LineCurve(ON_3dPoint(0,0,0),ON_3dPoint(1,0,0)));for(int i=0;i<65;++i){auto parent=std::make_unique<ON_PolyCurve>();require(parent->Append(deep.release()),"Construct independent deep owning control");deep=std::move(parent);}bool limit=false;try{nativeGeometryFacts(*deep);}catch(const ExchangeError& e){limit=std::string(e.what()).find("depth/node/cycle")!=std::string::npos;}require(limit,"Reference admission scan bounded before nested tree expansion");
    QFile output(QStringLiteral(OM9_MIXED_RESULTS));require(output.open(QIODevice::WriteOnly),"Write mixed retention evidence");output.write(QJsonDocument(QJsonObject{{"ok",true},{"checks",checks},{"cases",evidence},{"full_exchange_complete",false}}).toJson());std::cout<<"Mixed reference native retention PASS "<<checks<<" checks\n";return 0;
}catch(const std::exception& e){std::cerr<<"Mixed reference failure: "<<e.what()<<'\n';return 1;}}
