#include "ThreeDmInventory.h"
#include "ThreeDmNativeReferences.h"
#include "ThreeDmCurveOnSurface.h"
#include <QFile>
#include <QDir>
#include <QJsonDocument>
#include <QCryptographicHash>
#include <iostream>
using namespace OpenMatrix9Gui::ThreeDm;
static void require(bool v,const char* text){if(!v)throw ExchangeError(text);}
static QString id(const ON_UUID& value){char text[37]{};ON_UuidToString(value,text);return QString::fromLatin1(text);}
int main(){try{ON::Begin();QDir input(QStringLiteral(OM9_MIXED_SOURCE)),out(QStringLiteral(OM9_MIXED_OUTPUT));require(QDir().mkpath(out.path()),"Create mixed reference fixture folder");QFile file(input.filePath("oracle.json"));require(file.open(QIODevice::ReadOnly),"Independent standalone source oracle");auto cases=QJsonDocument::fromJson(file.readAll()).object()["cases"].toArray();QJsonArray reports;
    for(auto value:cases){auto wanted=value.toObject();if(wanted["root_class"]!="ON_PolyEdgeCurve")continue;auto objects=wanted["objects"].toArray();auto owner=objects[0].toObject(),reference=objects[1].toObject();
        auto source=inspectArchive(std::filesystem::path(input.filePath(wanted["fixture"].toString()).toStdWString()));auto uuid=reference["uuid"].toString();auto graph=source.nativeReferences->graphs.at(uuid);auto live=ON_Curve::Cast(graph->geometry.at(uuid).get());require(live&&live->IsValid(),"Live immutable standalone derived owner graph");
        ONX_Model model;model.m_settings.m_ModelUnitsAndTolerances.m_unit_system=ON_UnitSystem(ON::LengthUnitSystem::Millimeters);ON_Layer layer;layer.SetName(L"Mixed native reference fixture");model.AddModelComponent(layer);
        auto ownerId=ON_UuidFromString(owner["uuid"].toString().toLatin1().constData());auto ownerComponent=ON_ModelGeometryComponent::Cast(source.nativeModel->ComponentFromId(ON_ModelComponent::Type::ModelGeometry,ownerId).ModelComponent());require(ownerComponent&&!model.AddModelGeometryComponent(ownerComponent->Geometry(nullptr),ownerComponent->Attributes(nullptr),false).IsEmpty(),"Clone owner into independent fixture model without mutating graph source");
        auto child=ON_Curve::Cast(live->Duplicate());require(child&&child->ClassId()==live->ClassId(),"Class-preserving owning reference child");auto poly=new ON_PolyCurve;require(poly->Append(child),"Owning mixed reference child");auto points=reference["samples"].toArray();auto end=points[16].toArray();ON_3dPoint first(end[0].toDouble(),end[1].toDouble(),end[2].toDouble()),last=first+ON_3dVector(1,2,3);auto line=new ON_LineCurve(first,last);require(line->SetDomain(47,63)&&poly->Append(line)&&poly->SetDomain(31,63)&&poly->IsValid(),"Coherent independent owned line plus native reference child");poly->SetUserString(L"Scope",L"Mixed PolyCurve reference target compatibility pending");
        QJsonArray samples;for(int i=0;i<17;++i){ON_3dPoint expected;if(i<=8){auto p=points[2*i].toArray();expected=ON_3dPoint(p[0].toDouble(),p[1].toDouble(),p[2].toDouble());}else expected=first+ON_3dVector(1,2,3)*((i-8)/8.);require(poly->PointAt(31+2*i).DistanceTo(expected)<=1e-12,"Independent17-point composition including joint and both segment interiors");samples.append(QJsonArray{expected.x,expected.y,expected.z});}
        auto added=model.AddManagedModelGeometryComponent(poly,nullptr);require(!added.IsEmpty(),"Own mixed root; derived graph remains alive through raw SDK serialization");auto name=wanted["fixture"].toString().replace("standalone-kind-0","mixed-polycurve");auto path=std::filesystem::path(out.filePath(name).toStdWString());require(model.Write(path.c_str(),5,nullptr),"Independent direct SDK V5 fixture, not public OM9 target admission");QFile archive(QString::fromStdWString(path.wstring()));require(archive.open(QIODevice::ReadOnly),"Hash mixed source");auto bytes=archive.readAll();auto hash=QString::fromLatin1(QCryptographicHash::hash(bytes,QCryptographicHash::Sha256).toHex());ONX_Model reread;require(reread.Read(path.c_str(),nullptr),"Read native mixed fixture");auto component=ON_ModelGeometryComponent::Cast(reread.ComponentFromId(ON_ModelComponent::Type::ModelGeometry,added.ModelComponent()->Id()).ModelComponent());auto decoded=component?ON_Curve::Cast(component->Geometry(nullptr)):nullptr;require(decoded&&decoded->ClassId()==poly->ClassId(),"Exact ON_PolyCurve root after direct SDK read");auto fields=nativeCurveTreeFields(*decoded);require(fields["object_references"].toArray()==QJsonArray{owner["uuid"]},"Nested owner UUID persists in raw native tree");
        reports.append(QJsonObject{{"fixture",name},{"source_sha256",hash},{"native_reference_fields",fields},{"root_class","ON_PolyCurve"},{"objects",QJsonArray{owner,QJsonObject{{"uuid",id(added.ModelComponent()->Id())},{"domain",QJsonArray{31,63}},{"samples",samples}}}},{"passed",true}});
    }
    require(reports.size()==6,"Six mixed owner/direction target controls");QFile report(out.filePath("oracle.json"));require(report.open(QIODevice::WriteOnly),"Write independent mixed target oracle");report.write(QJsonDocument(QJsonObject{{"ok",true},{"cases",reports},{"actual_target_verified",false}}).toJson());std::cout<<"Mixed PolyCurve independent SDK target fixtures PASS6\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
