// Independent SDK20130711 semantic inventory. No modern SDK/Qt adapter calls.
#include <set>
struct LegacyLoopBudget {
    unsigned nodes=0;size_t numbers=0;std::set<const ON_Curve*> active;
    void reserve(size_t n){require(n<=2000000-numbers,"legacy loop numeric budget exceeded");numbers+=n;}
};
static void loopPoint(std::ostream& out,const ON_3dPoint& p){out<<'[';number(out,p.x);out<<',';number(out,p.y);out<<',';number(out,p.z);out<<']';}
static void loopPlane(std::ostream& out,const ON_Plane& p){out<<'[';bool first=true;for(auto v:{p.origin,ON_3dPoint(p.xaxis),ON_3dPoint(p.yaxis),ON_3dPoint(p.zaxis)})for(int i=0;i<3;++i){if(!first)out<<',';first=false;number(out,v[i]);}for(auto v:{p.plane_equation.x,p.plane_equation.y,p.plane_equation.z,p.plane_equation.d}){out<<',';number(out,v);}out<<']';}
static void loopData(std::ostream& out,const ON_Object& object){out<<'[';bool first=true;for(auto d=object.FirstUserData();d;d=d->Next()){if(!first)out<<',';first=false;out<<"{\"class_name\":";text(out,d->ClassId()->ClassName());out<<",\"class_uuid\":";id(out,d->ClassId()->Uuid());out<<",\"userdata_uuid\":";id(out,d->m_userdata_uuid);out<<",\"application_uuid\":";id(out,d->m_application_uuid);out<<'}';}out<<']';}
static void nativeCurve(std::ostream& out,const ON_Curve& curve,unsigned depth,LegacyLoopBudget& budget){
    require(depth<64&&++budget.nodes<=16384&&budget.active.insert(&curve).second,"legacy loop depth/node/cycle budget exceeded");require(curve.IsValid(),"invalid independent native curve");auto cls=curve.ClassId();out<<"{\"class_name\":";text(out,cls->ClassName());out<<",\"class_uuid\":";id(out,cls->Uuid());out<<",\"dimension\":"<<curve.Dimension()<<",\"domain\":[";number(out,curve.Domain()[0]);out<<',';number(out,curve.Domain()[1]);out<<"],\"user_strings\":";strings(out,curve);out<<",\"userdata\":";loopData(out,curve);
    if(cls==ON_CLASS_ID(ON_NurbsCurve)){const auto& n=static_cast<const ON_NurbsCurve&>(curve);budget.reserve(static_cast<size_t>(n.CVCount())*n.CVSize()+n.KnotCount());out<<",\"order\":"<<n.Order()<<",\"rational\":"<<(n.IsRational()?"true":"false")<<",\"cvs\":[";for(int i=0;i<n.CVCount();++i){if(i)out<<',';out<<'[';for(int j=0;j<n.CVSize();++j){if(j)out<<',';number(out,n.CV(i)[j]);}out<<']';}out<<"],\"knots\":[";for(int i=0;i<n.KnotCount();++i){if(i)out<<',';number(out,n.Knot(i));}out<<']';}
    else if(cls==ON_CLASS_ID(ON_ArcCurve)){const auto& n=static_cast<const ON_ArcCurve&>(curve);out<<",\"plane\":";loopPlane(out,n.m_arc.plane);out<<",\"radius\":";number(out,n.m_arc.radius);out<<",\"angle_domain\":[";number(out,n.m_arc.Domain()[0]);out<<',';number(out,n.m_arc.Domain()[1]);out<<']';}
    else if(cls==ON_CLASS_ID(ON_LineCurve)){const auto& n=static_cast<const ON_LineCurve&>(curve);out<<",\"points\":[";loopPoint(out,n.m_line.from);out<<',';loopPoint(out,n.m_line.to);out<<']';}
    else if(cls==ON_CLASS_ID(ON_PolylineCurve)){const auto& n=static_cast<const ON_PolylineCurve&>(curve);budget.reserve(static_cast<size_t>(n.m_pline.Count())*3+n.m_t.Count());out<<",\"points\":[";for(int i=0;i<n.m_pline.Count();++i){if(i)out<<',';loopPoint(out,n.m_pline[i]);}out<<"],\"parameters\":[";for(int i=0;i<n.m_t.Count();++i){if(i)out<<',';number(out,n.m_t[i]);}out<<']';}
    else if(cls==ON_CLASS_ID(ON_PolyCurve)){const auto& n=static_cast<const ON_PolyCurve&>(curve);out<<",\"segments\":[";for(int i=0;i<n.Count();++i){if(i)out<<',';require(n.SegmentCurve(i)!=nullptr,"missing native segment");nativeCurve(out,*n.SegmentCurve(i),depth+1,budget);}out<<"],\"parameters\":[";auto& params=n.SegmentParameters();for(int i=0;i<params.Count();++i){if(i)out<<',';number(out,params[i]);}out<<']';}
    else throw std::runtime_error(std::string("independent legacy curve requires explicit reference/surface inventory: ")+cls->ClassName());
    out<<'}';budget.active.erase(&curve);
}
static void nativeLoops(std::ostream& out,const ON_Hatch& h){out<<'[';LegacyLoopBudget budget;for(int i=0;i<h.LoopCount();++i){if(i)out<<',';auto loop=h.Loop(i);require(loop&&loop->Curve()&&loop->IsValid(),"invalid independent loop");out<<"{\"type\":"<<static_cast<int>(loop->Type())<<",\"curve\":";nativeCurve(out,*loop->Curve(),0,budget);out<<'}';}out<<']';}
