#include "opennurbs.h"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <iostream>
#include <cmath>
#include <stdexcept>
#include <type_traits>
#include <utility>
template<class T,class=void>struct HasGradient:std::false_type{};
template<class T>struct HasGradient<T,std::void_t<decltype(std::declval<T>().GetGradientType())>>:std::true_type{};
static_assert(!HasGradient<ON_Hatch>::value,"Independent Rhino5 reader must have no modern gradient API");
static void require(bool ok,const char* message){if(!ok)throw std::runtime_error(message);}
static constexpr size_t maxReport=32ULL*1024*1024;
class Buffer:public std::streambuf{
public:std::string data;
protected:std::streamsize xsputn(const char* p,std::streamsize n)override{if(n<0||static_cast<size_t>(n)>maxReport-data.size())throw std::runtime_error("legacy report exceeds32MiB");data.append(p,static_cast<size_t>(n));return n;}
int_type overflow(int_type c)override{if(traits_type::eq_int_type(c,traits_type::eof()))return traits_type::not_eof(c);char v=traits_type::to_char_type(c);xsputn(&v,1);return c;}
};
static void text(std::ostream& out,const char* value){out<<'"';for(auto p=reinterpret_cast<const unsigned char*>(value);p&&*p;++p){auto c=*p;switch(c){case '"':out<<"\\\"";break;case '\\':out<<"\\\\";break;case '\n':out<<"\\n";break;case '\r':out<<"\\r";break;case '\t':out<<"\\t";break;default:if(c<32){out<<"\\u00"<<std::hex<<std::setw(2)<<std::setfill('0')<<static_cast<int>(c)<<std::dec<<std::setfill(' ');}else out<<static_cast<char>(c);}}out<<'"';}
static void text(std::ostream& out,const ON_wString& value){ON_String utf8(value);text(out,utf8.Array());}
static void id(std::ostream& out,ON_UUID value){char v[37]{};ON_UuidToString(value,v);text(out,v);}
static void number(std::ostream& out,double value){require(std::isfinite(value),"invalid legacy numeric field");out<<value;}
static void strings(std::ostream& out,const ON_Object& object){ON_ClassArray<ON_UserString> values;object.GetUserStrings(values);out<<'[';for(int i=0;i<values.Count();++i){if(i)out<<',';out<<"{\"key\":";text(out,values[i].m_key);out<<",\"value\":";text(out,values[i].m_string_value);out<<'}';}out<<']';}
#include "hatch_loop_inventory.h"
static void pattern(std::ostream& out,const ON_HatchPattern& p){require(p.IsValid(),"invalid legacy hatch pattern");out<<"{\"uuid\":";id(out,p.m_hatchpattern_id);out<<",\"name\":";text(out,ON_wString(p.Name()));out<<",\"fill_type\":"<<static_cast<int>(p.FillType())<<",\"description\":";text(out,ON_wString(p.Description()));out<<",\"lines\":[";
    for(int i=0;i<p.HatchLineCount();++i){if(i)out<<',';auto line=p.HatchLine(i);require(line&&line->IsValid(),"invalid legacy hatch line");out<<"{\"angle\":";number(out,line->Angle());auto base=line->Base();auto offset=line->Offset();out<<",\"base\":[";number(out,base.x);out<<',';number(out,base.y);out<<"],\"offset\":[";number(out,offset.x);out<<',';number(out,offset.y);out<<"],\"dashes\":[";for(int j=0;j<line->DashCount();++j){if(j)out<<',';number(out,line->Dash(j));}out<<"]}";}out<<"],\"user_strings\":";strings(out,p);out<<'}';
}
static void hatch(std::ostream& out,const ON_Hatch& h,const ON_3dmObjectAttributes& a,const ONX_Model& model){require(h.IsValid(),"invalid legacy hatch");require(h.PatternIndex()>=0&&h.PatternIndex()<model.m_hatch_pattern_table.Count(),"legacy reader requires materialized pattern identity");auto& p=model.m_hatch_pattern_table[h.PatternIndex()];out<<"{\"uuid\":";id(out,a.m_uuid);out<<",\"name\":";text(out,a.m_name);out<<",\"pattern_uuid\":";id(out,p.m_hatchpattern_id);out<<",\"plane\":[";auto plane=h.Plane();bool first=true;for(auto v:{plane.origin,ON_3dPoint(plane.xaxis),ON_3dPoint(plane.yaxis),ON_3dPoint(plane.zaxis)})for(int k=0;k<3;++k){if(!first)out<<',';first=false;number(out,v[k]);}for(auto v:{plane.plane_equation.x,plane.plane_equation.y,plane.plane_equation.z,plane.plane_equation.d}){out<<',';number(out,v);}auto base=h.BasePoint2d();out<<"],\"base_point\":[";number(out,base.x);out<<',';number(out,base.y);out<<"],\"rotation\":";number(out,h.PatternRotation());out<<",\"scale\":";number(out,h.PatternScale());out<<",\"loops\":[";
    for(int i=0;i<h.LoopCount();++i){if(i)out<<',';auto loop=h.Loop(i);require(loop&&loop->IsValid()&&loop->Curve(),"invalid legacy hatch loop");auto curve=loop->Curve();auto n=ON_NurbsCurve::Cast(curve);if(!n){out<<"{\"type\":"<<static_cast<int>(loop->Type())<<",\"class_name\":";text(out,curve->ClassId()->ClassName());out<<"}";continue;}require(n->IsValid(),"invalid legacy NURBS");out<<"{\"type\":"<<static_cast<int>(loop->Type())<<",\"class_name\":";text(out,curve->ClassId()->ClassName());out<<",\"dimension\":"<<n->Dimension()<<",\"order\":"<<n->Order()<<",\"rational\":"<<(n->IsRational()?"true":"false")<<",\"cvs\":[";for(int j=0;j<n->CVCount();++j){if(j)out<<',';out<<'[';auto cv=n->CV(j);for(int k=0;k<n->CVSize();++k){if(k)out<<',';number(out,cv[k]);}out<<']';}out<<"],\"knots\":[";for(int j=0;j<n->KnotCount();++j){if(j)out<<',';number(out,n->Knot(j));}out<<"],\"user_strings\":";strings(out,*curve);out<<'}';}
    out<<"],\"native_loops\":";nativeLoops(out,h);out<<",\"user_strings\":";strings(out,h);out<<",\"attribute_user_strings\":";strings(out,a);out<<",\"userdata\":[";first=true;for(auto data=h.FirstUserData();data;data=data->Next()){if(!first)out<<',';first=false;out<<"{\"class_uuid\":";id(out,data->ClassId()->Uuid());out<<",\"userdata_uuid\":";id(out,data->m_userdata_uuid);out<<'}';}out<<"]}";
}
int main(int argc,char** argv){try{
    require(argc==4||(argc==5&&std::string(argv[4])=="--raw-attributes"),"usage: Rhino5HatchReader input.3dm output.3dm report.json [--raw-attributes]");ON::Begin();require(ON::Version()==201307115,"Unexpected legacy SDK revision");auto input=std::filesystem::u8path(argv[1]),output=std::filesystem::u8path(argv[2]),reportPath=std::filesystem::u8path(argv[3]);require(std::filesystem::file_size(input)<=512ULL*1024*1024,"legacy input exceeds512MiB");require(!std::filesystem::exists(output)&&!std::filesystem::exists(reportPath),"legacy outputs must be fresh staging paths");ONX_Model model;ON_TextLog log(stderr);require(model.Read(input.c_str(),&log),"independent legacy read failed");require(model.m_3dm_file_version==50,"independent reader accepts version5/50 only");
    int stale=0,repairs=0;for(int i=0;i<model.m_object_table.Count();++i){auto& attrs=model.m_object_table[i].m_attributes;bool needs=false;for(auto data=attrs.FirstUserData();data;data=data->Next())if(data->Owner()!=&attrs)needs=true;if(needs){++stale;if(argc==4){attrs.MemoryRelocate();++repairs;for(auto data=attrs.FirstUserData();data;data=data->Next())require(data->Owner()==&attrs,"legacy attribute ownership rebind failed");}}}
    Buffer buffer;std::ostream report(&buffer);report.exceptions(std::ios::badbit|std::ios::failbit);report.imbue(std::locale::classic());report<<std::setprecision(17)<<"{\"sdk_version\":"<<ON::Version()<<",\"source_version\":"<<model.m_3dm_file_version<<",\"gradient_api_available\":false,\"patterns\":[";
    for(int i=0;i<model.m_hatch_pattern_table.Count();++i){if(i)report<<',';pattern(report,model.m_hatch_pattern_table[i]);}report<<"],\"hatches\":[";bool first=true;int count=0;
    for(int i=0;i<model.m_object_table.Count();++i){auto& object=model.m_object_table[i];auto value=ON_Hatch::Cast(object.m_object);if(!value)continue;if(!first)report<<',';first=false;++count;hatch(report,*value,object.m_attributes,model);}
    report<<"],\"stale_attribute_owners\":"<<stale<<",\"attribute_owner_repairs\":"<<repairs<<",\"definitions\":[";for(int i=0;i<model.m_idef_table.Count();++i){if(i)report<<',';auto& def=model.m_idef_table[i];report<<"{\"uuid\":";id(report,def.m_uuid);report<<",\"members\":[";for(int j=0;j<def.m_object_uuid.Count();++j){if(j)report<<',';id(report,def.m_object_uuid[j]);}report<<"]}";}
    report<<"],\"instances\":[";first=true;for(int i=0;i<model.m_object_table.Count();++i){auto& object=model.m_object_table[i];auto instance=ON_InstanceRef::Cast(object.m_object);if(!instance)continue;if(!first)report<<',';first=false;report<<"{\"uuid\":";id(report,object.m_attributes.m_uuid);report<<",\"definition_uuid\":";id(report,instance->m_instance_definition_uuid);report<<",\"matrix\":[";for(int j=0;j<16;++j){if(j)report<<',';number(report,instance->m_xform[j/4][j%4]);}report<<"]}";}report<<"]}\n";require(count>0,"no native Hatch decoded by legacy SDK");
    require(model.Write(output.c_str(),5,"OpenMatrix9 independent legacy Hatch reader",&log),"independent legacy write failed");std::ofstream saved(reportPath,std::ios::binary);saved<<buffer.data;require(saved.good(),"legacy report write failed");std::cout<<"SDK201307115 exact Hatch report/read/write: "<<count<<" hatches\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
