# OM9-FILE-012: audited generated SDK source, never mutate the dependency checkout.
function(om9_repair_curve_on_surface_read target sdk_root expected_sha)
    set(original_path "${sdk_root}/opennurbs_curveonsurface.cpp")
    set(repair_path "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../Gui/ThreeDmCurveOnSurfaceRead.inc")
    file(READ "${original_path}" source)
    string(REPLACE "\r\n" "\n" source "${source}")
    string(SHA256 actual_sha "${source}")
    if(NOT actual_sha STREQUAL expected_sha)
        message(FATAL_ERROR "Unverified SDK CurveOnSurface source; refuse Read repair: ${actual_sha}")
    endif()
    string(FIND "${source}" "bool \nON_CurveOnSurface::Read(" start)
    set(read_return bool)
    if(start LESS 0)
        string(FIND "${source}" "ON_BOOL32 \nON_CurveOnSurface::Read(" start)
        set(read_return ON_BOOL32)
    endif()
    string(FIND "${source}" "int \nON_CurveOnSurface::Dimension()" finish)
    if(start LESS 0 OR finish LESS_EQUAL start)
        message(FATAL_ERROR "Verified CurveOnSurface Read boundaries missing")
    endif()
    file(READ "${repair_path}" repair)
    string(REPLACE "bool\nON_CurveOnSurface::Read" "${read_return}\nON_CurveOnSurface::Read" repair "${repair}")
    string(SUBSTRING "${source}" 0 ${start} prefix)
    string(SUBSTRING "${source}" ${finish} -1 suffix)
    set(directory "${CMAKE_CURRENT_BINARY_DIR}/om9-sdk-repairs/${target}")
    file(MAKE_DIRECTORY "${directory}")
    set(generated "${directory}/opennurbs_curveonsurface.cpp")
    file(CONFIGURE OUTPUT "${generated}" CONTENT "${prefix}${repair}${suffix}" @ONLY)
    get_target_property(original_sources ${target} SOURCES)
    set(updated)
    set(replaced 0)
    foreach(entry IN LISTS original_sources)
        get_filename_component(name "${entry}" NAME)
        if(name STREQUAL "opennurbs_curveonsurface.cpp")
            list(APPEND updated "${generated}")
            math(EXPR replaced "${replaced}+1")
        else()
            list(APPEND updated "${entry}")
        endif()
    endforeach()
    if(NOT replaced EQUAL 1)
        message(FATAL_ERROR "Expected one CurveOnSurface source in ${target}, found ${replaced}")
    endif()
    set_property(TARGET ${target} PROPERTY SOURCES "${updated}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original_path}" "${repair_path}")
    file(CONFIGURE OUTPUT "${directory}/repair.txt" CONTENT
        "OM9-FILE-012 CurveOnSurface::Read only\nupstream_normalized_sha256=${actual_sha}\nupstream_source=${original_path}\nrepair_source=${repair_path}\n" @ONLY)
    message(STATUS "OM9 audited CurveOnSurface child Read repair for ${target}; original SDK source unchanged")
endfunction()
