# Only the separate, explicitly repaired SDK20130711 test oracle uses this.
# Original SDK files and existing independent readers remain unchanged.
function(om9_repair_legacy_polyedge_read target sdkroot)
    set(original "${sdkroot}/opennurbs_polyedgecurve.cpp")
    file(READ "${original}" source)
    string(SHA256 sha "${source}")
    if(NOT sha STREQUAL "53497cf7b0ec9de4000582da2656ff5dc1b3c3fc76a4d07baf91d6bd5853f4f8")
        message(FATAL_ERROR "Unverified SDK2013 PolyEdge source: ${sha}")
    endif()
    set(before "    if ( bReversed)\n      ON_CurveProxy::Reverse();\n    ON_CurveProxy::SetDomain(this_domain);")
    set(after "    // OM9 SDK2013: establish a valid evaluation domain before Reverse().\n    // The public2013 API has no reversed-flag setter. Restore the exact domain.\n    if ( bReversed)\n    {\n      if (!ON_CurveProxy::SetDomain(this_domain)) { rc = false; break; }\n      ON_CurveProxy::Reverse();\n    }\n    ON_CurveProxy::SetDomain(this_domain);")
    string(FIND "${source}" "${before}" location)
    if(location LESS 0)
        message(FATAL_ERROR "SDK2013 PolyEdge Read boundaries missing")
    endif()
    string(REPLACE "${before}" "${after}" repaired "${source}")
    set(directory "${CMAKE_CURRENT_BINARY_DIR}/om9-sdk-repairs/${target}")
    file(MAKE_DIRECTORY "${directory}")
    set(generated "${directory}/opennurbs_polyedgecurve.cpp")
    file(CONFIGURE OUTPUT "${generated}" CONTENT "${repaired}" @ONLY)
    get_target_property(entries ${target} SOURCES)
    set(updated)
    set(count 0)
    foreach(entry IN LISTS entries)
        get_filename_component(name "${entry}" NAME)
        if(name STREQUAL "opennurbs_polyedgecurve.cpp")
            list(APPEND updated "${generated}")
            math(EXPR count "${count}+1")
        else()
            list(APPEND updated "${entry}")
        endif()
    endforeach()
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one SDK2013 PolyEdge source, got ${count}")
    endif()
    set_property(TARGET ${target} PROPERTY SOURCES "${updated}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}" "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
    file(CONFIGURE OUTPUT "${directory}/polyedge-repair.txt" CONTENT "OM9-FILE-012 SDK2013 PolyEdgeSegment::Read reversed flag only\nupstream_normalized_sha256=${sha}\nupstream_source=${original}\n" @ONLY)
    message(STATUS "OM9 declared SDK2013 PolyEdge Read correction; original source unchanged")
endfunction()
