# Pinned modern SDK only: preserve the archive's reversed flag before linkage.
# Original SDK source and the separate SDK2013 reader remain unchanged.
function(om9_repair_polyedge_read target sdkroot)
    set(original "${sdkroot}/opennurbs_polyedgecurve.cpp")
    file(READ "${original}" source)
    string(SHA256 sha "${source}")
    if(NOT sha STREQUAL "2942b4a3c8b9b2141312939d59c315b59b58c5cfc04c5d8d30b871cc1b0fc9da")
        message(FATAL_ERROR "Unverified PolyEdge source; refuse reversed-flag Read repair: ${sha}")
    endif()
    set(before "    if ( bReversed)\n      ON_CurveProxy::Reverse();\n    ON_CurveProxy::SetDomain(this_domain);")
    set(after "    // OM9: Reverse() cannot toggle an empty, not-yet-linked domain.\n    ON_CurveProxy::SetProxyCurveIsReversed(bReversed);\n    ON_CurveProxy::SetDomain(this_domain);")
    string(FIND "${source}" "${before}" location)
    if(location LESS 0)
        message(FATAL_ERROR "Verified PolyEdge reversed-flag Read boundaries missing")
    endif()
    string(REPLACE "${before}" "${after}" repaired "${source}")
    set(directory "${CMAKE_CURRENT_BINARY_DIR}/om9-sdk-repairs/${target}")
    file(MAKE_DIRECTORY "${directory}")
    set(generated "${directory}/opennurbs_polyedgecurve.cpp")
    file(CONFIGURE OUTPUT "${generated}" CONTENT "${repaired}" @ONLY)
    get_target_property(entries ${target} SOURCES)
    set(updated)
    set(count 0)
    foreach(entry IN LISTS entries)
        get_filename_component(name "${entry}" NAME)
        if(name STREQUAL "opennurbs_polyedgecurve.cpp")
            list(APPEND updated "${generated}")
            math(EXPR count "${count}+1")
        else()
            list(APPEND updated "${entry}")
        endif()
    endforeach()
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one PolyEdge source, found ${count}")
    endif()
    set_property(TARGET ${target} PROPERTY SOURCES "${updated}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}" "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
    file(CONFIGURE OUTPUT "${directory}/polyedge-repair.txt" CONTENT "OM9-FILE-012 PolyEdgeSegment::Read reversed flag only\nupstream_normalized_sha256=${sha}\nupstream_source=${original}\n" @ONLY)
    message(STATUS "OM9 audited PolyEdgeSegment Read reversed flag repair; original SDK source unchanged")
endfunction()
