# Pinned SDK: serialize genuine RDK3 (UTF8 XML without the RDK4 resource
# trailer) for Rhino5 documents without embedded files. Resource-bearing
# and newer archives keep the original RDK4 writer. Host preflight refuses
# unsupported embedded-resource Rhino5 exports before opening a destination.
function(om9_repair_rdk_document_write target sdkroot)
    set(original "${sdkroot}/opennurbs_extensions.cpp")
    file(READ "${original}" source)
    string(SHA256 sha "${source}")
    if(NOT sha STREQUAL "4b26c7f10bde1ae187bf81d9af57e295cd584bdb4e2030423bb95d5f633ed1b2")
        message(FATAL_ERROR "Unverified RDK document source: ${sha}")
    endif()
    string(FIND "${source}" "bool ONX_ModelPrivate::SetRDKDocumentInformation(" start)
    string(FIND "${source}" "// Object user data" finish)
    if(start LESS 0 OR finish LESS_EQUAL start)
        message(FATAL_ERROR "Verified RDK writer boundaries missing")
    endif()
    math(EXPR length "${finish}-${start}")
    string(SUBSTRING "${source}" ${start} ${length} writer)
    set(before "  int version = 4; // Where do I get this from?")
    set(after "  // OM9: version3 is the actual Rhino5 UTF8 layout without embedded files.\n  const bool rhino5 = (archive_3dm_version == 5 || archive_3dm_version == 50);\n  const auto num_embedded_files = int(m_model.ActiveComponentCount(ON_ModelComponent::Type::EmbeddedFile));\n  int version = (rhino5 && num_embedded_files == 0) ? 3 : 4;")
    string(FIND "${writer}" "${before}" marker)
    if(marker LESS 0)
        message(FATAL_ERROR "Pinned RDK version marker missing")
    endif()
    string(REPLACE "${before}" "${after}" writer "${writer}")
    set(before "  // Write the number of embedded files.\n  const auto num_embedded_files = int(m_model.ActiveComponentCount(ON_ModelComponent::Type::EmbeddedFile));")
    set(after "  if (version == 4)\n  {\n  // Write the number of embedded files.")
    string(FIND "${writer}" "${before}" marker)
    if(marker LESS 0)
        message(FATAL_ERROR "Pinned RDK resource trailer marker missing")
    endif()
    string(REPLACE "${before}" "${after}" writer "${writer}")
    string(REPLACE "  // Delete the old goo." "  } // RDK4 resource trailer; version3 ends immediately after XML.\n\n  // Delete the old goo." writer "${writer}")
    string(SUBSTRING "${source}" 0 ${start} prefix)
    string(SUBSTRING "${source}" ${finish} -1 suffix)
    set(directory "${CMAKE_CURRENT_BINARY_DIR}/om9-sdk-repairs/${target}")
    file(MAKE_DIRECTORY "${directory}")
    set(generated "${directory}/opennurbs_extensions.cpp")
    file(CONFIGURE OUTPUT "${generated}" CONTENT "${prefix}${writer}${suffix}" @ONLY)
    get_target_property(entries ${target} SOURCES)
    set(updated)
    set(count 0)
    foreach(entry IN LISTS entries)
        get_filename_component(name "${entry}" NAME)
        if(name STREQUAL "opennurbs_extensions.cpp")
            list(APPEND updated "${generated}")
            math(EXPR count "${count}+1")
        else()
            list(APPEND updated "${entry}")
        endif()
    endforeach()
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one SDK RDK writer source, found ${count}")
    endif()
    set_property(TARGET ${target} PROPERTY SOURCES "${updated}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}" "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
    file(CONFIGURE OUTPUT "${directory}/rdk-repair.txt" CONTENT "OM9-FILE-012 RDK3 document encoding for resource-free V5/V50 only\nupstream_normalized_sha256=${sha}\nupstream_source=${original}\nnewer/resource-bearing RDK4 payload unchanged\n" @ONLY)
    message(STATUS "OM9 audited resource-free Rhino5 RDK3 writer; original SDK source unchanged")
endfunction()
